-- ============================================================================
-- VIOLET ERP - BASE DE DATOS FIREBIRD SQL
-- Basado en ValeryProfesional / ANALISIS_TECNICO_COMPLETO.md
-- ============================================================================
-- Motor: Firebird 2.5.2
-- Caracter set: UTF8
-- Collation: UNICODE_CI_AI
-- ============================================================================

SET NAMES UTF8;
CREATE DATABASE 'localhost:C:\VIOLET_ERP\VIOLET3.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET UTF8
COLLATION UNICODE_CI_AI;

-- ============================================================================
-- 1. TABLAS BÁSICAS - CONFIGURACIÓN
-- ============================================================================

-- Tabla: CONFIGURACION
CREATE TABLE CONFIGURACION (
    PARAMETRO VARCHAR(50) NOT NULL,
    VALOR VARCHAR(500),
    DESCRIPCION VARCHAR(255),
    TIPO CHAR(1) DEFAULT 'T', -- T=Texto, N=Numérico, B=Booleano, F=Fecha
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CONFIGURACION PRIMARY KEY (PARAMETRO)
);

-- Datos iniciales de configuración
INSERT INTO CONFIGURACION (PARAMETRO, VALOR, DESCRIPCION, TIPO) VALUES
('EMPRESA_NOMBRE', 'MI EMPRESA C.A.', 'Nombre de la empresa', 'T'),
('EMPRESA_RIF', 'J-12345678-9', 'RIF de la empresa', 'T'),
('EMPRESA_DIRECCION', 'Dirección fiscal', 'Dirección de la empresa', 'T'),
('EMPRESA_TELEFONO', '', 'Teléfono de la empresa', 'T'),
('EMPRESA_EMAIL', '', 'Email de la empresa', 'T'),
('ALICUOTA_IVA', '16', 'Alícuota general de IVA', 'N'),
('ALICUOTA_IVA_REDUCIDA', '8', 'Alícuota reducida de IVA', 'N'),
('ALICUOTA_IVA_LUJO', '31', 'Alícuota de lujo de IVA', 'N'),
('PORC_RETENCION_IVA', '75', 'Porcentaje de retención IVA ordinario', 'N'),
('PORC_RETENCION_IVA_ESPECIAL', '100', 'Porcentaje de retención IVA especial', 'N'),
('TASA_IGTF', '3', 'Tasa del IGTF', 'N'),
('CONTRIBUYENTE_ESPECIAL', 'F', 'Es contribuyente especial', 'B'),
('MONEDA_LOCAL', 'VES', 'Moneda local', 'T'),
('EJERCICIO_FISCAL', '2026', 'Año del ejercicio fiscal', 'N'),
('PAIS', 'Venezuela', 'País', 'T'),
('ESTADO', '', 'Estado', 'T'),
('CIUDAD', '', 'Ciudad', 'T'),
('CODIGO_POSTAL', '', 'Código postal', 'T');

-- Tabla: SUCURSALES
CREATE TABLE SUCURSALES (
    CODIGO VARCHAR(15) NOT NULL,
    NOMBRE VARCHAR(160) NOT NULL,
    DIRECCION VARCHAR(255),
    TELEFONO VARCHAR(40),
    EMAIL VARCHAR(60),
    ESTATUS CHAR(1) DEFAULT 'A', -- A=Activo, I=Inactivo
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_SUCURSALES PRIMARY KEY (CODIGO)
);

-- Tabla: USUARIOS
CREATE TABLE USUARIOS (
    CODIGO VARCHAR(15) NOT NULL,
    NOMBRE VARCHAR(160) NOT NULL,
    LOGIN VARCHAR(50) NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(60),
    PERFIL VARCHAR(50),
    ESTATUS CHAR(1) DEFAULT 'A',
    ULTIMO_ACCESO TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_USUARIOS PRIMARY KEY (CODIGO),
    CONSTRAINT UK_USUARIOS_LOGIN UNIQUE (LOGIN)
);

-- Tabla: PERFILES
CREATE TABLE PERFILES (
    CODIGO VARCHAR(50) NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(255),
    PERMISOS BLOB SUB_TYPE TEXT,
    ESTATUS CHAR(1) DEFAULT 'A',
    CONSTRAINT PK_PERFILES PRIMARY KEY (CODIGO)
);

-- ============================================================================
-- 2. MÓDULO CLIENTES (CXC)
-- ============================================================================

-- Tabla: GRUPO_CLIENTES
CREATE TABLE GRUPO_CLIENTES (
    CODIGO VARCHAR(15) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(255),
    ESTATUS CHAR(1) DEFAULT 'A',
    CONSTRAINT PK_GRUPO_CLIENTES PRIMARY KEY (CODIGO)
);

-- Tabla: ZONAS_VENTAS
CREATE TABLE ZONAS_VENTAS (
    CODIGO VARCHAR(15) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    REFERENCIA VARCHAR(20),
    ESTATUS CHAR(1) DEFAULT 'A',
    CONSTRAINT PK_ZONAS_VENTAS PRIMARY KEY (CODIGO)
);

-- Tabla: LISTA_PRECIOS
CREATE TABLE LISTA_PRECIOS (
    CODIGO VARCHAR(15) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    PORC_DESCUENTO DECIMAL(5,2) DEFAULT 0,
    ESTATUS CHAR(1) DEFAULT 'A',
    CONSTRAINT PK_LISTA_PRECIOS PRIMARY KEY (CODIGO)
);

-- Tabla: CLIENTES
CREATE TABLE CLIENTES (
    CODIGO VARCHAR(15) NOT NULL,
    NOMBRE VARCHAR(160) NOT NULL,
    REFERENCIA VARCHAR(20),
    CONTACTO VARCHAR(50),
    VENDEDOR_CODIGO VARCHAR(15),
    ZONA_VENTA_CODIGO VARCHAR(15),
    LISTA_PRECIOS_CODIGO VARCHAR(15),
    CUENTA_CONTABLE VARCHAR(22),
    RIF VARCHAR(20) NOT NULL,
    NIT VARCHAR(20),
    DIRECCION VARCHAR(160),
    CIUDAD VARCHAR(40),
    ESTADO VARCHAR(40),
    PAIS VARCHAR(40),
    CODIGO_POSTAL VARCHAR(10),
    TELEFONOS VARCHAR(40),
    FAX VARCHAR(40),
    CORREO_ELECTRONICO VARCHAR(60),
    LIMITE_CREDITO DECIMAL(18,2) DEFAULT 0,
    DIAS_CREDITO SMALLINT DEFAULT 0,
    CREDITO_DISPONIBLE DECIMAL(18,2) COMPUTED BY (LIMITE_CREDITO - TOTAL_SALDO),
    TOTAL_DEBITOS DECIMAL(18,2) DEFAULT 0,
    TOTAL_CREDITOS DECIMAL(18,2) DEFAULT 0,
    TOTAL_ANTICIPOS DECIMAL(18,2) DEFAULT 0,
    TOTAL_SALDO DECIMAL(18,2) DEFAULT 0,
    DENOMINACION_FISCAL VARCHAR(2) DEFAULT 'CO', -- CO=Común, GB=Gran Contribuyente, NO=No contribuyente
    PRECIO_VENTA CHAR(1) DEFAULT '1', -- 1-7 (listas de precios)
    RETENCION DECIMAL(5,2) DEFAULT 0,
    DESCUENTO DECIMAL(5,2) DEFAULT 0,
    EDITAR_DATOS_FISCALES CHAR(1) DEFAULT 'F',
    ACEPTAR_CHEQUE CHAR(1) DEFAULT 'F',
    REQUIERE_CLAVE CHAR(1) DEFAULT 'F',
    NOTAS VARCHAR(120),
    MAXIMO_MONTO_VENTA DECIMAL(18,2),
    MAXIMO_CREDITO DECIMAL(18,2),
    ULTIMA_VENTA_CONTADO TIMESTAMP,
    MONTO_ULTIMA_VENTA_CONTADO DECIMAL(18,2),
    ULTIMA_VENTA_CREDITO TIMESTAMP,
    MONTO_ULTIMA_VENTA_CREDITO DECIMAL(18,2),
    ULTIMO_PAGO TIMESTAMP,
    MONTO_ULTIMO_PAGO DECIMAL(18,2),
    ESTATUS CHAR(1) DEFAULT 'A',
    FECHA_INICIO DATE,
    GRUPO_CLIENTES_CODIGO VARCHAR(15),
    MUNICIPIO VARCHAR(40),
    CONTRIBUYENTE_ESPECIAL CHAR(1) DEFAULT 'F',
    TIPO_VENTA CHAR(2),
    TIPO_CLIENTE CHAR(2),
    DV VARCHAR(2), -- Dígito verificador (Panamá)
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CLIENTES PRIMARY KEY (CODIGO),
    CONSTRAINT FK_CLIENTES_GRUPO FOREIGN KEY (GRUPO_CLIENTES_CODIGO) REFERENCES GRUPO_CLIENTES(CODIGO),
    CONSTRAINT FK_CLIENTES_ZONA FOREIGN KEY (ZONA_VENTA_CODIGO) REFERENCES ZONAS_VENTAS(CODIGO),
    CONSTRAINT FK_CLIENTES_LISTA FOREIGN KEY (LISTA_PRECIOS_CODIGO) REFERENCES LISTA_PRECIOS(CODIGO)
);

-- Índice para búsqueda por RIF
CREATE INDEX IDX_CLIENTES_RIF ON CLIENTES(RIF);
CREATE INDEX IDX_CLIENTES_NOMBRE ON CLIENTES(NOMBRE);
CREATE INDEX IDX_CLIENTES_ESTADO ON CLIENTES(ESTATUS);

-- Tabla: CXC (Cuentas por Cobrar)
CREATE TABLE CXC (
    CORRELATIVO INTEGER NOT NULL,
    CLIENTE_CODIGO VARCHAR(15) NOT NULL,
    DOCUMENTO VARCHAR(10) NOT NULL,
    TIPO_DOCUMENTO CHAR(3),
    FECHA DATE NOT NULL,
    FECHA_VENCIMIENTO DATE,
    TOTAL_OPERACION DECIMAL(18,2) NOT NULL,
    TOTAL_BASE_IMPONIBLE DECIMAL(18,2),
    TOTAL_IMPUESTO DECIMAL(18,2),
    SALDO DECIMAL(18,2) NOT NULL,
    ESTATUS CHAR(1) DEFAULT 'P', -- P=Pendiente, C=Cancelado
    VENTA_CORRELATIVO INTEGER,
    USUARIO_CODIGO VARCHAR(15),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CXC PRIMARY KEY (CORRELATIVO),
    CONSTRAINT FK_CXC_CLIENTE FOREIGN KEY (CLIENTE_CODIGO) REFERENCES CLIENTES(CODIGO),
    CONSTRAINT FK_CXC_VENTA FOREIGN KEY (VENTA_CORRELATIVO) REFERENCES VENTAS(CORRELATIVO)
);

CREATE INDEX IDX_CXC_CLIENTE ON CXC(CLIENTE_CODIGO);
CREATE INDEX IDX_CXC_DOCUMENTO ON CXC(DOCUMENTO);
CREATE INDEX IDX_CXC_ESTADO ON CXC(ESTATUS);
CREATE INDEX IDX_CXC_VENCIMIENTO ON CXC(FECHA_VENCIMIENTO);

-- Tabla: CXC_DESGLOSE_IMPUESTO
CREATE TABLE CXC_DESGLOSE_IMPUESTO (
    CORRELATIVO INTEGER NOT NULL,
    CODIGO INTEGER NOT NULL,
    ALICUOTA DECIMAL(5,2) NOT NULL,
    BASE_IMPONIBLE DECIMAL(18,2) NOT NULL,
    IMPUESTO DECIMAL(18,2) NOT NULL,
    EXENTO CHAR(1) DEFAULT 'F',
    CONSTRAINT PK_CXC_DESGLOSE_IMPUESTO PRIMARY KEY (CORRELATIVO, CODIGO, ALICUOTA),
    CONSTRAINT FK_CXC_DESGLOSE FOREIGN KEY (CORRELATIVO) REFERENCES CXC(CORRELATIVO) ON DELETE CASCADE
);

-- Tabla: PAGOS_CXC
CREATE TABLE PAGOS_CXC (
    CORRELATIVO INTEGER NOT NULL,
    CXC_CORRELATIVO INTEGER NOT NULL,
    DOCUMENTO VARCHAR(10) NOT NULL,
    FECHA DATE NOT NULL,
    MONTO DECIMAL(18,2) NOT NULL,
    FORMA_PAGO VARCHAR(20),
    REFERENCIA VARCHAR(50),
    NOTAS VARCHAR(255),
    USUARIO_CODIGO VARCHAR(15),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PAGOS_CXC PRIMARY KEY (CORRELATIVO),
    CONSTRAINT FK_PAGOS_CXC FOREIGN KEY (CXC_CORRELATIVO) REFERENCES CXC(CORRELATIVO)
);

CREATE INDEX IDX_PAGOS_CXC_DOCUMENTO ON PAGOS_CXC(DOCUMENTO);
CREATE INDEX IDX_PAGOS_CXC_FECHA ON PAGOS_CXC(FECHA);

-- ============================================================================
-- 3. MÓDULO PROVEEDORES (CXP)
-- ============================================================================

-- Tabla: PROVEEDORES
CREATE TABLE PROVEEDORES (
    CODIGO VARCHAR(15) NOT NULL,
    NOMBRE VARCHAR(160) NOT NULL,
    REFERENCIA VARCHAR(20),
    CONTACTO VARCHAR(50),
    LISTA_PRECIOS_CODIGO VARCHAR(15),
    CUENTA_CONTABLE VARCHAR(22),
    RIF VARCHAR(20) NOT NULL,
    NIT VARCHAR(20),
    DIRECCION VARCHAR(160),
    CIUDAD VARCHAR(40),
    ESTADO VARCHAR(40),
    PAIS VARCHAR(40),
    TELEFONOS VARCHAR(40),
    FAX VARCHAR(40),
    CORREO_ELECTRONICO VARCHAR(60),
    LIMITE_CREDITO DECIMAL(18,2),
    DIAS_CREDITO SMALLINT,
    CREDITO_DISPONIBLE DECIMAL(18,2) COMPUTED BY (LIMITE_CREDITO - TOTAL_SALDO),
    TOTAL_DEBITOS DECIMAL(18,2) DEFAULT 0,
    TOTAL_CREDITOS DECIMAL(18,2) DEFAULT 0,
    TOTAL_SALDO DECIMAL(18,2) DEFAULT 0,
    DENOMINACION_FISCAL VARCHAR(2) DEFAULT 'CO',
    RETENCION_IVA DECIMAL(5,2),
    RETENCION_ISLR DECIMAL(5,2),
    ESTATUS CHAR(1) DEFAULT 'A',
    CONTRIBUYENTE_ESPECIAL CHAR(1) DEFAULT 'F',
    TIEMPO_PAGO_PROMEDIO INTEGER DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PROVEEDORES PRIMARY KEY (CODIGO),
    CONSTRAINT FK_PROVEEDORES_LISTA FOREIGN KEY (LISTA_PRECIOS_CODIGO) REFERENCES LISTA_PRECIOS(CODIGO)
);

CREATE INDEX IDX_PROVEEDORES_RIF ON PROVEEDORES(RIF);
CREATE INDEX IDX_PROVEEDORES_NOMBRE ON PROVEEDORES(NOMBRE);

-- Tabla: CXP (Cuentas por Pagar)
CREATE TABLE CXP (
    CORRELATIVO INTEGER NOT NULL,
    PROVEEDOR_CODIGO VARCHAR(15) NOT NULL,
    DOCUMENTO VARCHAR(10) NOT NULL,
    TIPO_DOCUMENTO CHAR(3),
    FECHA DATE NOT NULL,
    FECHA_VENCIMIENTO DATE,
    TOTAL_OPERACION DECIMAL(18,2) NOT NULL,
    TOTAL_BASE_IMPONIBLE DECIMAL(18,2),
    TOTAL_IMPUESTO DECIMAL(18,2),
    SALDO DECIMAL(18,2) NOT NULL,
    ESTATUS CHAR(1) DEFAULT 'P', -- P=Pendiente, C=Cancelado
    COMPRA_CORRELATIVO INTEGER,
    USUARIO_CODIGO VARCHAR(15),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CXP PRIMARY KEY (CORRELATIVO),
    CONSTRAINT FK_CXP_PROVEEDOR FOREIGN KEY (PROVEEDOR_CODIGO) REFERENCES PROVEEDORES(CODIGO),
    CONSTRAINT FK_CXP_COMPRA FOREIGN KEY (COMPRA_CORRELATIVO) REFERENCES COMPRAS(CORRELATIVO)
);

CREATE INDEX IDX_CXP_PROVEEDOR ON CXP(PROVEEDOR_CODIGO);
CREATE INDEX IDX_CXP_DOCUMENTO ON CXP(DOCUMENTO);
CREATE INDEX IDX_CXP_ESTADO ON CXP(ESTATUS);

-- Tabla: CXP_DESGLOSE_IMPUESTO
CREATE TABLE CXP_DESGLOSE_IMPUESTO (
    CORRELATIVO INTEGER NOT NULL,
    CODIGO INTEGER NOT NULL,
    ALICUOTA DECIMAL(5,2) NOT NULL,
    BASE_IMPONIBLE DECIMAL(18,2) NOT NULL,
    IMPUESTO DECIMAL(18,2) NOT NULL,
    EXENTO CHAR(1) DEFAULT 'F',
    CONSTRAINT PK_CXP_DESGLOSE_IMPUESTO PRIMARY KEY (CORRELATIVO, CODIGO, ALICUOTA),
    CONSTRAINT FK_CXP_DESGLOSE FOREIGN KEY (CORRELATIVO) REFERENCES CXP(CORRELATIVO) ON DELETE CASCADE
);

-- Tabla: PAGOS_CXP
CREATE TABLE PAGOS_CXP (
    CORRELATIVO INTEGER NOT NULL,
    CXP_CORRELATIVO INTEGER NOT NULL,
    DOCUMENTO VARCHAR(10) NOT NULL,
    FECHA DATE NOT NULL,
    MONTO DECIMAL(18,2) NOT NULL,
    FORMA_PAGO VARCHAR(20),
    REFERENCIA VARCHAR(50),
    NOTAS VARCHAR(255),
    USUARIO_CODIGO VARCHAR(15),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PAGOS_CXP PRIMARY KEY (CORRELATIVO),
    CONSTRAINT FK_PAGOS_CXP FOREIGN KEY (CXP_CORRELATIVO) REFERENCES CXP(CORRELATIVO)
);

-- ============================================================================
-- 4. MÓDULO PRODUCTOS E INVENTARIO
-- ============================================================================

-- Tabla: UNIDADES
CREATE TABLE UNIDADES (
    CODIGO VARCHAR(15) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    ABREVIATURA VARCHAR(10),
    ESTATUS CHAR(1) DEFAULT 'A',
    CONSTRAINT PK_UNIDADES PRIMARY KEY (CODIGO)
);

-- Tabla: GRUPO_PRODUCTOS
CREATE TABLE GRUPO_PRODUCTOS (
    CODIGO VARCHAR(15) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(255),
    ESTATUS CHAR(1) DEFAULT 'A',
    CONSTRAINT PK_GRUPO_PRODUCTOS PRIMARY KEY (CODIGO)
);

-- Tabla: MARCAS
CREATE TABLE MARCAS (
    CODIGO VARCHAR(15) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(255),
    ESTATUS CHAR(1) DEFAULT 'A',
    CONSTRAINT PK_MARCAS PRIMARY KEY (CODIGO)
);

-- Tabla: LINEAS
CREATE TABLE LINEAS (
    CODIGO VARCHAR(15) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(255),
    ESTATUS CHAR(1) DEFAULT 'A',
    CONSTRAINT PK_LINEAS PRIMARY KEY (CODIGO)
);

-- Tabla: DEPOSITOS
CREATE TABLE DEPOSITOS (
    CODIGO VARCHAR(15) NOT NULL,
    NOMBRE VARCHAR(160) NOT NULL,
    DIRECCION VARCHAR(255),
    TELEFONO VARCHAR(40),
    ESTATUS CHAR(1) DEFAULT 'A',
    UBICACION VARCHAR(100),
    RESPONSABLE VARCHAR(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_DEPOSITOS PRIMARY KEY (CODIGO)
);

-- Tabla: PRODUCTOS
CREATE TABLE PRODUCTOS (
    CODIGO VARCHAR(15) NOT NULL,
    NOMBRE VARCHAR(160) NOT NULL,
    DESCRIPCION VARCHAR(255),
    CODIGO_BARRA VARCHAR(50),
    REFERENCIA VARCHAR(20),
    GRUPO_CODIGO VARCHAR(15),
    MARCA_CODIGO VARCHAR(15),
    UNIDAD_CODIGO VARCHAR(15),
    LINEA_CODIGO VARCHAR(15),
    DEPOSITO_CODIGO VARCHAR(15),
    CUENTA_CONTABLE VARCHAR(22),
    PRECIO_COSTO DECIMAL(18,4) DEFAULT 0,
    PRECIO_VENTA DECIMAL(18,4) DEFAULT 0,
    PRECIO_MAYOR DECIMAL(18,4) DEFAULT 0,
    PRECIO_OFERTA DECIMAL(18,4) DEFAULT 0,
    PRECIO_MINIMO DECIMAL(18,4) DEFAULT 0,
    PRECIO_MAXIMO DECIMAL(18,4) DEFAULT 0,
    PRECIO_1 DECIMAL(18,4) DEFAULT 0,
    PRECIO_2 DECIMAL(18,4) DEFAULT 0,
    PRECIO_3 DECIMAL(18,4) DEFAULT 0,
    PRECIO_4 DECIMAL(18,4) DEFAULT 0,
    PRECIO_5 DECIMAL(18,4) DEFAULT 0,
    PRECIO_6 DECIMAL(18,4) DEFAULT 0,
    PRECIO_7 DECIMAL(18,4) DEFAULT 0,
    ALICUOTA_IVA DECIMAL(5,2) DEFAULT 16,
    EXISTENCIA DECIMAL(18,4) DEFAULT 0,
    STOCK_MINIMO DECIMAL(18,4) DEFAULT 0,
    STOCK_MAXIMO DECIMAL(18,4),
    ESTATUS CHAR(1) DEFAULT 'A',
    TIPO CHAR(1) DEFAULT 'P', -- P=Producto, S=Servicio, C=Compuesto
    REQUIERE_SERIAL CHAR(1) DEFAULT 'F',
    CONTROLA_LOTE CHAR(1) DEFAULT 'F',
    FECHA_VENCIMIENTO DATE,
    PESO DECIMAL(18,4),
    VOLUMEN DECIMAL(18,4),
    LARGO DECIMAL(18,4),
    ANCHO DECIMAL(18,4),
    ALTO DECIMAL(18,4),
    IMAGEN BLOB SUB_TYPE BINARY,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PRODUCTOS PRIMARY KEY (CODIGO),
    CONSTRAINT FK_PRODUCTOS_GRUPO FOREIGN KEY (GRUPO_CODIGO) REFERENCES GRUPO_PRODUCTOS(CODIGO),
    CONSTRAINT FK_PRODUCTOS_MARCA FOREIGN KEY (MARCA_CODIGO) REFERENCES MARCAS(CODIGO),
    CONSTRAINT FK_PRODUCTOS_UNIDAD FOREIGN KEY (UNIDAD_CODIGO) REFERENCES UNIDADES(CODIGO),
    CONSTRAINT FK_PRODUCTOS_LINEA FOREIGN KEY (LINEA_CODIGO) REFERENCES LINEAS(CODIGO),
    CONSTRAINT FK_PRODUCTOS_DEPOSITO FOREIGN KEY (DEPOSITO_CODIGO) REFERENCES DEPOSITOS(CODIGO)
);

CREATE INDEX IDX_PRODUCTOS_CODIGO_BARRA ON PRODUCTOS(CODIGO_BARRA);
CREATE INDEX IDX_PRODUCTOS_NOMBRE ON PRODUCTOS(NOMBRE);
CREATE INDEX IDX_PRODUCTOS_GRUPO ON PRODUCTOS(GRUPO_CODIGO);
CREATE INDEX IDX_PRODUCTOS_ESTADO ON PRODUCTOS(ESTATUS);

-- Tabla: EXISTENCIAS (Inventario por depósito)
CREATE TABLE EXISTENCIAS (
    PRODUCTO_CODIGO VARCHAR(15) NOT NULL,
    DEPOSITO_CODIGO VARCHAR(15) NOT NULL,
    CANTIDAD DECIMAL(18,4) DEFAULT 0,
    COSTO_PROMEDIO DECIMAL(18,4) DEFAULT 0,
    ULTIMA_COMPRA DATE,
    ULTIMA_VENTA DATE,
    STOCK_MINIMO DECIMAL(18,4) DEFAULT 0,
    STOCK_MAXIMO DECIMAL(18,4),
    UBICACION VARCHAR(50),
    CONSTRAINT PK_EXISTENCIAS PRIMARY KEY (PRODUCTO_CODIGO, DEPOSITO_CODIGO),
    CONSTRAINT FK_EXISTENCIAS_PRODUCTO FOREIGN KEY (PRODUCTO_CODIGO) REFERENCES PRODUCTOS(CODIGO),
    CONSTRAINT FK_EXISTENCIAS_DEPOSITO FOREIGN KEY (DEPOSITO_CODIGO) REFERENCES DEPOSITOS(CODIGO)
);

-- Tabla: PRODUCTOS_COMPOSICION (Para productos compuestos)
CREATE TABLE PRODUCTOS_COMPOSICION (
    PRODUCTO_PADRE_CODIGO VARCHAR(15) NOT NULL,
    PRODUCTO_HIJO_CODIGO VARCHAR(15) NOT NULL,
    CANTIDAD DECIMAL(18,4) NOT NULL,
    UNIDAD_CODIGO VARCHAR(15),
    PORC_MERMA DECIMAL(5,2) DEFAULT 0,
    CONSTRAINT PK_PRODUCTOS_COMPOSICION PRIMARY KEY (PRODUCTO_PADRE_CODIGO, PRODUCTO_HIJO_CODIGO),
    CONSTRAINT FK_COMPOSICION_PADRE FOREIGN KEY (PRODUCTO_PADRE_CODIGO) REFERENCES PRODUCTOS(CODIGO),
    CONSTRAINT FK_COMPOSICION_HIJO FOREIGN KEY (PRODUCTO_HIJO_CODIGO) REFERENCES PRODUCTOS(CODIGO)
);

-- Tabla: SERIALES (Para productos que requieren serial)
CREATE TABLE SERIALES (
    CORRELATIVO INTEGER NOT NULL,
    PRODUCTO_CODIGO VARCHAR(15) NOT NULL,
    DEPOSITO_CODIGO VARCHAR(15),
    SERIAL VARCHAR(50) NOT NULL,
    FECHA_INGRESO DATE,
    FECHA_SALIDA DATE,
    DOCUMENTO_INGRESO VARCHAR(10),
    DOCUMENTO_SALIDA VARCHAR(10),
    ESTATUS CHAR(1) DEFAULT 'D', -- D=Disponible, V=Vendido, R=Reservado
    NOTAS VARCHAR(255),
    CONSTRAINT PK_SERIALES PRIMARY KEY (CORRELATIVO),
    CONSTRAINT FK_SERIALES_PRODUCTO FOREIGN KEY (PRODUCTO_CODIGO) REFERENCES PRODUCTOS(CODIGO),
    CONSTRAINT FK_SERIALES_DEPOSITO FOREIGN KEY (DEPOSITO_CODIGO) REFERENCES DEPOSITOS(CODIGO),
    CONSTRAINT UK_SERIAL UNIQUE (PRODUCTO_CODIGO, SERIAL)
);

CREATE INDEX IDX_SERIALES_SERIAL ON SERIALES(SERIAL);
CREATE INDEX IDX_SERIALES_ESTADO ON SERIALES(ESTATUS);

-- Tabla: LOTES (Para productos que controlan lote)
CREATE TABLE LOTES (
    CORRELATIVO INTEGER NOT NULL,
    PRODUCTO_CODIGO VARCHAR(15) NOT NULL,
    DEPOSITO_CODIGO VARCHAR(15),
    LOTE VARCHAR(50) NOT NULL,
    FECHA_FABRICACION DATE,
    FECHA_VENCIMIENTO DATE,
    CANTIDAD_INGRESO DECIMAL(18,4),
    CANTIDAD_SALIDA DECIMAL(18,4) DEFAULT 0,
    CANTIDAD_ACTUAL DECIMAL(18,4) COMPUTED BY (CANTIDAD_INGRESO - CANTIDAD_SALIDA),
    COSTO DECIMAL(18,4),
    DOCUMENTO_INGRESO VARCHAR(10),
    ESTATUS CHAR(1) DEFAULT 'A',
    CONSTRAINT PK_LOTES PRIMARY KEY (CORRELATIVO),
    CONSTRAINT FK_LOTES_PRODUCTO FOREIGN KEY (PRODUCTO_CODIGO) REFERENCES PRODUCTOS(CODIGO),
    CONSTRAINT FK_LOTES_DEPOSITO FOREIGN KEY (DEPOSITO_CODIGO) REFERENCES DEPOSITOS(CODIGO),
    CONSTRAINT UK_LOTE UNIQUE (PRODUCTO_CODIGO, LOTE)
);

CREATE INDEX IDX_LOTES_LOTE ON LOTES(LOTE);
CREATE INDEX IDX_LOTES_VENCIMIENTO ON LOTES(FECHA_VENCIMIENTO);

-- ============================================================================
-- CONTINUARÁ... (Más tablas en el siguiente archivo)
-- ============================================================================
