-- ============================================================================
-- VIOLET ERP - BASE DE DATOS FIREBIRD SQL - PARTE 2
-- MÓDULOS: VENTAS, COMPRAS, INVENTARIO, BANCO, CAJA
-- ============================================================================

SET NAMES UTF8;

-- ============================================================================
-- 5. MÓDULO VENTAS
-- ============================================================================

-- Tabla: TIPOS_DOCUMENTO_VENTA
CREATE TABLE TIPOS_DOCUMENTO_VENTA (
    CODIGO CHAR(3) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(255),
    IMPACTA_INVENTARIO CHAR(1) DEFAULT 'S',
    IMPACTA_CONTABILIDAD CHAR(1) DEFAULT 'S',
    REQUIERE_CLIENTE CHAR(1) DEFAULT 'S',
    REQUIERE_PRECIO CHAR(1) DEFAULT 'S',
    SECUENCIA INTEGER DEFAULT 0,
    ESTATUS CHAR(1) DEFAULT 'A',
    CONSTRAINT PK_TIPOS_DOCUMENTO_VENTA PRIMARY KEY (CODIGO)
);

-- Datos iniciales de tipos de documento
INSERT INTO TIPOS_DOCUMENTO_VENTA (CODIGO, NOMBRE, DESCRIPCION, IMPACTA_INVENTARIO, IMPACTA_CONTABILIDAD) VALUES
('FAC', 'Factura', 'Factura fiscal', 'S', 'S'),
('FCR', 'Factura Crédito', 'Factura a crédito', 'S', 'S'),
('NCR', 'Nota Crédito', 'Devolución/Saldo a favor', 'S', 'S'),
('NDB', 'Nota Débito', 'Cargo adicional', 'S', 'S'),
('PED', 'Pedido', 'Pedido de cliente', 'N', 'N'),
('ODD', 'Orden Despacho', 'Orden de entrega', 'N', 'N'),
('PRS', 'Presupuesto', 'Cotización', 'N', 'N'),
('NET', 'Nota Entrega', 'Entrega parcial', 'S', 'S'),
('FPV', 'Factura PV', 'Factura punto de venta', 'S', 'S');

-- Tabla: NUMERACION_DOCUMENTOS
CREATE TABLE NUMERACION_DOCUMENTOS (
    TIPO_DOCUMENTO VARCHAR(10) NOT NULL,
    DESCRIPCION VARCHAR(100),
    ULTIMO_NUMERO INTEGER DEFAULT 0,
    PREFIJO VARCHAR(5),
    LONGITUD INTEGER DEFAULT 8,
    SUCURSAL_CODIGO VARCHAR(15),
    ESTATUS CHAR(1) DEFAULT 'A',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_NUMERACION_DOCUMENTOS PRIMARY KEY (TIPO_DOCUMENTO, SUCURSAL_CODIGO)
);

-- Tabla: VENTAS (Encabezado)
CREATE TABLE VENTAS (
    CORRELATIVO INTEGER NOT NULL,
    CORRELATIVO_CODIGO SMALLINT,
    DOCUMENTO VARCHAR(10) NOT NULL,
    TIPO_DOCUMENTO CHAR(3) NOT NULL,
    CLIENTE_CODIGO VARCHAR(15) NOT NULL,
    CLIENTE_NOMBRE VARCHAR(160),
    CLIENTE_RIF VARCHAR(20),
    CLIENTE_NIT VARCHAR(20),
    CLIENTE_CONTACTO VARCHAR(50),
    CLIENTE_DIRECCION VARCHAR(160),
    CLIENTE_TELEFONOS VARCHAR(40),
    CLIENTE_FAX VARCHAR(40),
    CLIENTE_CORREO_E VARCHAR(60),
    CLIENTE_ZONA VARCHAR(15),
    CLIENTE_TIPO_PRECIO CHAR(1),
    DENOMINACION_FISCAL VARCHAR(2),
    MONEDA_CODIGO VARCHAR(15),
    FACTOR_CAMBIO DECIMAL(18,6) DEFAULT 1,
    FECHA_EMISION DATE NOT NULL,
    HORA_EMISION TIME,
    DIAS_VENCIMIENTO SMALLINT DEFAULT 0,
    FECHA_VENCIMIENTO DATE,
    DEPOSITO_CODIGO VARCHAR(15),
    VENDEDOR_CODIGO VARCHAR(15),
    ORDEN_DE_COMPRA VARCHAR(10),
    FECHA_ORDEN_COMPRA DATE,
    RETENCION DECIMAL(18,2) DEFAULT 0,
    CONTADO DECIMAL(18,2) DEFAULT 0,
    CREDITO DECIMAL(18,2) DEFAULT 0,
    ANTICIPO DECIMAL(18,2) DEFAULT 0,
    TOTAL_CANCELADO DECIMAL(18,2),
    VUELTO DECIMAL(18,2) DEFAULT 0,
    TOTAL_BRUTO_LINEAS DECIMAL(18,2),
    TOTAL_DESCUENTO_LINEAS DECIMAL(18,2),
    TOTAL_NETO_LINEAS DECIMAL(18,2),
    TOTAL_IMPUESTO_LINEAS DECIMAL(18,2),
    TOTAL_LINEAS DECIMAL(18,2),
    DESCUENTO_1 DECIMAL(18,2) DEFAULT 0,
    PORC_DESCUENTO_1 DECIMAL(5,2) DEFAULT 0,
    DESCUENTO_2 DECIMAL(18,2) DEFAULT 0,
    PORC_DESCUENTO_2 DECIMAL(5,2) DEFAULT 0,
    FLETE DECIMAL(18,2) DEFAULT 0,
    PORC_FLETE DECIMAL(5,2) DEFAULT 0,
    TOTAL_NETO DECIMAL(18,2),
    IMPUESTO DECIMAL(18,2),
    PORC_IMPUESTO DECIMAL(5,2) DEFAULT 16,
    TOTAL_IMPUESTO_MUNICIPAL DECIMAL(18,2) DEFAULT 0,
    TOTAL_IMPUESTO_ADICIONAL DECIMAL(18,2) DEFAULT 0,
    TOTAL_OPERACION DECIMAL(18,2),
    TOTAL_BASE_IMPONIBLE_LINEAS DECIMAL(18,2),
    TOTAL_IMPUESTO_FISCAL_LINEAS DECIMAL(18,2),
    TOTAL_EXENTO_LINEAS DECIMAL(18,2),
    TOTAL_BASE_IMPONIBLE DECIMAL(18,2),
    TOTAL_IMPUESTO_FISCAL DECIMAL(18,2),
    TOTAL_EXENTO DECIMAL(18,2),
    TOTAL_COSTO DECIMAL(18,2),
    ESTACION VARCHAR(30),
    USUARIO_CODIGO VARCHAR(15),
    TEMPORAL CHAR(1) DEFAULT 'F',
    ASIGNAR_COSTO DECIMAL(18,2),
    PORC_RETENCION DECIMAL(5,2),
    CORRELATIVO_CXC INTEGER,
    MOTIVO_CODIGO VARCHAR(15),
    TOTAL_COSTO_PROMEDIO DECIMAL(18,2),
    IMPUESTO_IVA_CODIGO VARCHAR(15),
    TOTAL_RETENCION_IVA DECIMAL(18,2) DEFAULT 0,
    PORC_RETENCION_IVA DECIMAL(5,2) DEFAULT 75,
    DOCUMENTO_RETENCION_IVA VARCHAR(20),
    CONTROL_INTERNO CHAR(2),
    DOCUMENTO_NCR VARCHAR(10),
    NUMERO_CONTROL VARCHAR(10),
    FECHA_RECEPCION_RTP DATE,
    FECHA_HORA_IMPRESION TIMESTAMP,
    FECHA_Y_HORA TIMESTAMP,
    TOTAL_IMPUESTO_AL_LICOR DECIMAL(18,2) DEFAULT 0,
    FECHA_HORA_REGISTRO TIMESTAMP,
    TOTAL_COSTO_IMP DECIMAL(18,2),
    TOTAL_COSTO_PROMEDIO_IMP DECIMAL(18,2),
    TOTAL_CANTIDAD_ITEMS DECIMAL(18,4),
    TOTAL_ITEMS INTEGER,
    TIPO_TRANSACCION VARCHAR(15),
    ESTATUS CHAR(1) DEFAULT 'R', -- R=Registrada, A=Anulada
    IMPACTA_INVENTARIO CHAR(1) DEFAULT 'S',
    IMPACTA_CONTABILIDAD CHAR(1) DEFAULT 'S',
    ANULADO_POR VARCHAR(15),
    FECHA_ANULACION DATE,
    MOTIVO_ANULACION VARCHAR(255),
    IMPRESO CHAR(1) DEFAULT 'F',
    FECHA_IMPRESION TIMESTAMP,
    ENVIADO CHAR(1) DEFAULT 'F',
    FECHA_ENVIO TIMESTAMP,
    EMAIL_ENVIO VARCHAR(60),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_VENTAS PRIMARY KEY (CORRELATIVO),
    CONSTRAINT FK_VENTAS_CLIENTE FOREIGN KEY (CLIENTE_CODIGO) REFERENCES CLIENTES(CODIGO),
    CONSTRAINT FK_VENTAS_DEPOSITO FOREIGN KEY (DEPOSITO_CODIGO) REFERENCES DEPOSITOS(CODIGO),
    CONSTRAINT FK_VENTAS_VENDEDOR FOREIGN KEY (VENDEDOR_CODIGO) REFERENCES USUARIOS(CODIGO),
    CONSTRAINT FK_VENTAS_USUARIO FOREIGN KEY (USUARIO_CODIGO) REFERENCES USUARIOS(CODIGO),
    CONSTRAINT FK_VENTAS_CXC FOREIGN KEY (CORRELATIVO_CXC) REFERENCES CXC(CORRELATIVO),
    CONSTRAINT UK_VENTAS_DOCUMENTO UNIQUE (TIPO_DOCUMENTO, DOCUMENTO)
);

CREATE INDEX IDX_VENTAS_DOCUMENTO ON VENTAS(DOCUMENTO);
CREATE INDEX IDX_VENTAS_CLIENTE ON VENTAS(CLIENTE_CODIGO);
CREATE INDEX IDX_VENTAS_FECHA ON VENTAS(FECHA_EMISION);
CREATE INDEX IDX_VENTAS_TIPO ON VENTAS(TIPO_DOCUMENTO);
CREATE INDEX IDX_VENTAS_ESTATUS ON VENTAS(ESTATUS);
CREATE INDEX IDX_VENTAS_VENDEDOR ON VENTAS(VENDEDOR_CODIGO);

-- Tabla: VENTAS_DESGLOSE (Detalle)
CREATE TABLE VENTAS_DESGLOSE (
    CORRELATIVO INTEGER NOT NULL,
    CODIGO INTEGER NOT NULL,
    TIPO_REGISTRO CHAR(1) DEFAULT 'P', -- P=Producto, S=Servicio
    PRODUCTO_CODIGO VARCHAR(15),
    PRODUCTO_NOMBRE VARCHAR(160),
    PRODUCTO_DESCRIPCION VARCHAR(255),
    PRODUCTO_REFERENCIA VARCHAR(20),
    CANTIDAD DECIMAL(18,4) NOT NULL,
    UNIDAD_CODIGO VARCHAR(15),
    PRECIO DECIMAL(18,6) NOT NULL,
    PORC_DESCUENTO DECIMAL(5,2) DEFAULT 0,
    DESCUENTO DECIMAL(18,2) DEFAULT 0,
    BRUTO DECIMAL(18,2),
    NETO DECIMAL(18,2),
    IMPUESTO DECIMAL(18,2),
    TOTAL DECIMAL(18,2),
    COSTO DECIMAL(18,4),
    COSTO_PROMEDIO DECIMAL(18,4),
    ALICUOTA_IVA DECIMAL(5,2) DEFAULT 16,
    IMPUESTO_IVA_CODIGO VARCHAR(15),
    EXENTO CHAR(1) DEFAULT 'F',
    IMPUESTO_MUNICIPAL DECIMAL(18,2) DEFAULT 0,
    IMPUESTO_ADICIONAL DECIMAL(18,2) DEFAULT 0,
    SERIAL VARCHAR(50),
    LOTE VARCHAR(50),
    FECHA_VENCIMIENTO DATE,
    DEPOSITO_CODIGO VARCHAR(15),
    ORDEN INTEGER,
    COMISION DECIMAL(18,2) DEFAULT 0,
    PORC_COMISION DECIMAL(5,2) DEFAULT 0,
    VENDEDOR_CODIGO VARCHAR(15),
    NOTAS VARCHAR(255),
    CONSTRAINT PK_VENTAS_DESGLOSE PRIMARY KEY (CORRELATIVO, CODIGO),
    CONSTRAINT FK_VENTAS_DESGLOSE_VENTA FOREIGN KEY (CORRELATIVO) REFERENCES VENTAS(CORRELATIVO) ON DELETE CASCADE,
    CONSTRAINT FK_VENTAS_DESGLOSE_PRODUCTO FOREIGN KEY (PRODUCTO_CODIGO) REFERENCES PRODUCTOS(CODIGO),
    CONSTRAINT FK_VENTAS_DESGLOSE_DEPOSITO FOREIGN KEY (DEPOSITO_CODIGO) REFERENCES DEPOSITOS(CODIGO)
);

CREATE INDEX IDX_VENTAS_DESGLOSE_PRODUCTO ON VENTAS_DESGLOSE(PRODUCTO_CODIGO);
CREATE INDEX IDX_VENTAS_DESGLOSE_LOTE ON VENTAS_DESGLOSE(LOTE);

-- Tabla: VENTAS_DESGLOSE_IMPUESTO
CREATE TABLE VENTAS_DESGLOSE_IMPUESTO (
    CORRELATIVO INTEGER NOT NULL,
    CODIGO INTEGER NOT NULL,
    ALICUOTA DECIMAL(5,2) NOT NULL,
    BASE_IMPONIBLE DECIMAL(18,2) NOT NULL,
    IMPUESTO DECIMAL(18,2) NOT NULL,
    EXENTO CHAR(1) DEFAULT 'F',
    PORC_ALICUOTA DECIMAL(5,2) DEFAULT 16,
    CONSTRAINT PK_VENTAS_DESGLOSE_IMPUESTO PRIMARY KEY (CORRELATIVO, CODIGO, ALICUOTA),
    CONSTRAINT FK_VENTAS_DESGLOSE_IMPUESTO FOREIGN KEY (CORRELATIVO) REFERENCES VENTAS(CORRELATIVO) ON DELETE CASCADE
);

-- Tabla: PAGOS_VENTAS
CREATE TABLE PAGOS_VENTAS (
    CORRELATIVO INTEGER NOT NULL,
    VENTA_CORRELATIVO INTEGER NOT NULL,
    DOCUMENTO VARCHAR(10) NOT NULL,
    FECHA DATE NOT NULL,
    MONTO DECIMAL(18,2) NOT NULL,
    FORMA_PAGO VARCHAR(20), -- CONTADO, CREDITO, TRANSFERENCIA, CHEQUE, DIVISAS
    REFERENCIA VARCHAR(50),
    BANCO_CODIGO VARCHAR(15),
    CUENTA_BANCARIA_CODIGO VARCHAR(15),
    MONTO_DIVISAS DECIMAL(18,2),
    TASA_CAMBIO DECIMAL(18,6),
    IGTF DECIMAL(18,2) DEFAULT 0,
    NOTAS VARCHAR(255),
    USUARIO_CODIGO VARCHAR(15),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PAGOS_VENTAS PRIMARY KEY (CORRELATIVO),
    CONSTRAINT FK_PAGOS_VENTAS FOREIGN KEY (VENTA_CORRELATIVO) REFERENCES VENTAS(CORRELATIVO),
    CONSTRAINT FK_PAGOS_VENTAS_BANCO FOREIGN KEY (BANCO_CODIGO) REFERENCES BANCOS(CODIGO)
);

CREATE INDEX IDX_PAGOS_VENTAS_DOCUMENTO ON PAGOS_VENTAS(DOCUMENTO);
CREATE INDEX IDX_PAGOS_VENTAS_FECHA ON PAGOS_VENTAS(FECHA);

-- Tabla: DEVOLUCIONES_VENTA
CREATE TABLE DEVOLUCIONES_VENTA (
    CORRELATIVO INTEGER NOT NULL,
    VENTA_CORRELATIVO INTEGER NOT NULL,
    DOCUMENTO VARCHAR(10) NOT NULL,
    FECHA DATE NOT NULL,
    CLIENTE_CODIGO VARCHAR(15) NOT NULL,
    TOTAL_DEVOLUCION DECIMAL(18,2) NOT NULL,
    MOTIVO VARCHAR(255),
    ESTATUS CHAR(1) DEFAULT 'P', -- P=Pendiente, A=Aprobada, R=Rechazada
    APROBADO_POR VARCHAR(15),
    FECHA_APROBACION DATE,
    USUARIO_CODIGO VARCHAR(15),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_DEVOLUCIONES_VENTA PRIMARY KEY (CORRELATIVO),
    CONSTRAINT FK_DEVOLUCIONES_VENTA FOREIGN KEY (VENTA_CORRELATIVO) REFERENCES VENTAS(CORRELATIVO),
    CONSTRAINT FK_DEVOLUCIONES_CLIENTE FOREIGN KEY (CLIENTE_CODIGO) REFERENCES CLIENTES(CODIGO)
);

-- Tabla: DEVOLUCIONES_VENTA_DESGLOSE
CREATE TABLE DEVOLUCIONES_VENTA_DESGLOSE (
    CORRELATIVO INTEGER NOT NULL,
    CODIGO INTEGER NOT NULL,
    VENTA_DESGLOSE_CODIGO INTEGER,
    PRODUCTO_CODIGO VARCHAR(15),
    CANTIDAD DECIMAL(18,4) NOT NULL,
    PRECIO DECIMAL(18,6),
    TOTAL DECIMAL(18,2),
    MOTIVO VARCHAR(255),
    REINGRESA_INVENTARIO CHAR(1) DEFAULT 'S',
    CONSTRAINT PK_DEVOLUCIONES_VENTA_DESGLOSE PRIMARY KEY (CORRELATIVO, CODIGO),
    CONSTRAINT FK_DEVOLUCIONES_DESGLOSE FOREIGN KEY (CORRELATIVO) REFERENCES DEVOLUCIONES_VENTA(CORRELATIVO) ON DELETE CASCADE
);

-- ============================================================================
-- 6. MÓDULO COMPRAS
-- ============================================================================

-- Tabla: TIPOS_DOCUMENTO_COMPRA
CREATE TABLE TIPOS_DOCUMENTO_COMPRA (
    CODIGO CHAR(3) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(255),
    IMPACTA_INVENTARIO CHAR(1) DEFAULT 'S',
    IMPACTA_CONTABILIDAD CHAR(1) DEFAULT 'S',
    REQUIERE_PROVEEDOR CHAR(1) DEFAULT 'S',
    ESTATUS CHAR(1) DEFAULT 'A',
    CONSTRAINT PK_TIPOS_DOCUMENTO_COMPRA PRIMARY KEY (CODIGO)
);

INSERT INTO TIPOS_DOCUMENTO_COMPRA (CODIGO, NOMBRE, DESCRIPCION, IMPACTA_INVENTARIO) VALUES
('FCM', 'Factura Compra', 'Factura de compra', 'S'),
('NCR', 'Nota Crédito', 'Nota de crédito de compra', 'S'),
('NDB', 'Nota Débito', 'Nota de débito de compra', 'S'),
('ODC', 'Orden Compra', 'Orden de compra', 'N'),
('RCP', 'Recepción', 'Recepción de mercancía', 'S');

-- Tabla: COMPRAS (Encabezado)
CREATE TABLE COMPRAS (
    CORRELATIVO INTEGER NOT NULL,
    DOCUMENTO VARCHAR(10) NOT NULL,
    TIPO_DOCUMENTO CHAR(3) NOT NULL,
    PROVEEDOR_CODIGO VARCHAR(15) NOT NULL,
    PROVEEDOR_NOMBRE VARCHAR(160),
    PROVEEDOR_RIF VARCHAR(20),
    FECHA_DOCUMENTO DATE NOT NULL,
    FECHA_REGISTRO DATE NOT NULL,
    FECHA_VENCIMIENTO DATE,
    DEPOSITO_CODIGO VARCHAR(15),
    MONEDA_CODIGO VARCHAR(15),
    FACTOR_CAMBIO DECIMAL(18,6) DEFAULT 1,
    TOTAL_BRUTO_LINEAS DECIMAL(18,2),
    TOTAL_DESCUENTO_LINEAS DECIMAL(18,2),
    TOTAL_NETO_LINEAS DECIMAL(18,2),
    TOTAL_IMPUESTO_LINEAS DECIMAL(18,2),
    TOTAL_LINEAS DECIMAL(18,2),
    TOTAL_NETO DECIMAL(18,2),
    IMPUESTO DECIMAL(18,2),
    TOTAL_OPERACION DECIMAL(18,2),
    TOTAL_BASE_IMPONIBLE DECIMAL(18,2),
    TOTAL_IMPUESTO_FISCAL DECIMAL(18,2),
    TOTAL_EXENTO DECIMAL(18,2),
    TOTAL_COSTO DECIMAL(18,2),
    TOTAL_RETENCION_IVA DECIMAL(18,2) DEFAULT 0,
    TOTAL_RETENCION_ISLR DECIMAL(18,2) DEFAULT 0,
    TOTAL_IGTF DECIMAL(18,2) DEFAULT 0,
    FLETE DECIMAL(18,2) DEFAULT 0,
    SEGURO DECIMAL(18,2) DEFAULT 0,
    OTROS_GASTOS DECIMAL(18,2) DEFAULT 0,
    ESTACION VARCHAR(30),
    USUARIO_CODIGO VARCHAR(15),
    ESTATUS CHAR(1) DEFAULT 'R', -- R=Registrada, A=Anulada, P=Pendiente
    ORDEN_COMPRA VARCHAR(10),
    FACTURA_AFECTA VARCHAR(10),
    NUMERO_CONTROL VARCHAR(20),
    FECHA_RECEPCION DATE,
    ANULADO_POR VARCHAR(15),
    FECHA_ANULACION DATE,
    MOTIVO_ANULACION VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_COMPRAS PRIMARY KEY (CORRELATIVO),
    CONSTRAINT FK_COMPRAS_PROVEEDOR FOREIGN KEY (PROVEEDOR_CODIGO) REFERENCES PROVEEDORES(CODIGO),
    CONSTRAINT FK_COMPRAS_DEPOSITO FOREIGN KEY (DEPOSITO_CODIGO) REFERENCES DEPOSITOS(CODIGO),
    CONSTRAINT FK_COMPRAS_USUARIO FOREIGN KEY (USUARIO_CODIGO) REFERENCES USUARIOS(CODIGO),
    CONSTRAINT UK_COMPRAS_DOCUMENTO UNIQUE (TIPO_DOCUMENTO, DOCUMENTO)
);

CREATE INDEX IDX_COMPRAS_DOCUMENTO ON COMPRAS(DOCUMENTO);
CREATE INDEX IDX_COMPRAS_PROVEEDOR ON COMPRAS(PROVEEDOR_CODIGO);
CREATE INDEX IDX_COMPRAS_FECHA ON COMPRAS(FECHA_DOCUMENTO);
CREATE INDEX IDX_COMPRAS_ESTATUS ON COMPRAS(ESTATUS);

-- Tabla: COMPRAS_DESGLOSE (Detalle)
CREATE TABLE COMPRAS_DESGLOSE (
    CORRELATIVO INTEGER NOT NULL,
    CODIGO INTEGER NOT NULL,
    PRODUCTO_CODIGO VARCHAR(15),
    PRODUCTO_NOMBRE VARCHAR(160),
    CANTIDAD DECIMAL(18,4) NOT NULL,
    UNIDAD_CODIGO VARCHAR(15),
    PRECIO DECIMAL(18,6) NOT NULL,
    PORC_DESCUENTO DECIMAL(5,2) DEFAULT 0,
    DESCUENTO DECIMAL(18,2) DEFAULT 0,
    BRUTO DECIMAL(18,2),
    NETO DECIMAL(18,2),
    IMPUESTO DECIMAL(18,2),
    TOTAL DECIMAL(18,2),
    COSTO DECIMAL(18,4),
    ALICUOTA_IVA DECIMAL(5,2) DEFAULT 16,
    EXENTO CHAR(1) DEFAULT 'F',
    SERIAL VARCHAR(50),
    LOTE VARCHAR(50),
    FECHA_VENCIMIENTO DATE,
    DEPOSITO_CODIGO VARCHAR(15),
    ORDEN INTEGER,
    PORC_IMPUESTO_ADICIONAL DECIMAL(5,2) DEFAULT 0,
    IMPUESTO_ADICIONAL DECIMAL(18,2) DEFAULT 0,
    NOTAS VARCHAR(255),
    CONSTRAINT PK_COMPRAS_DESGLOSE PRIMARY KEY (CORRELATIVO, CODIGO),
    CONSTRAINT FK_COMPRAS_DESGLOSE_COMPRA FOREIGN KEY (CORRELATIVO) REFERENCES COMPRAS(CORRELATIVO) ON DELETE CASCADE,
    CONSTRAINT FK_COMPRAS_DESGLOSE_PRODUCTO FOREIGN KEY (PRODUCTO_CODIGO) REFERENCES PRODUCTOS(CODIGO),
    CONSTRAINT FK_COMPRAS_DESGLOSE_DEPOSITO FOREIGN KEY (DEPOSITO_CODIGO) REFERENCES DEPOSITOS(CODIGO)
);

CREATE INDEX IDX_COMPRAS_DESGLOSE_PRODUCTO ON COMPRAS_DESGLOSE(PRODUCTO_CODIGO);

-- Tabla: COMPRAS_DESGLOSE_IMPUESTO
CREATE TABLE COMPRAS_DESGLOSE_IMPUESTO (
    CORRELATIVO INTEGER NOT NULL,
    CODIGO INTEGER NOT NULL,
    ALICUOTA DECIMAL(5,2) NOT NULL,
    BASE_IMPONIBLE DECIMAL(18,2) NOT NULL,
    IMPUESTO DECIMAL(18,2) NOT NULL,
    EXENTO CHAR(1) DEFAULT 'F',
    CONSTRAINT PK_COMPRAS_DESGLOSE_IMPUESTO PRIMARY KEY (CORRELATIVO, CODIGO, ALICUOTA),
    CONSTRAINT FK_COMPRAS_DESGLOSE_IMPUESTO FOREIGN KEY (CORRELATIVO) REFERENCES COMPRAS(CORRELATIVO) ON DELETE CASCADE
);

-- Tabla: PAGOS_COMPRAS
CREATE TABLE PAGOS_COMPRAS (
    CORRELATIVO INTEGER NOT NULL,
    COMPRA_CORRELATIVO INTEGER NOT NULL,
    DOCUMENTO VARCHAR(10) NOT NULL,
    FECHA DATE NOT NULL,
    MONTO DECIMAL(18,2) NOT NULL,
    FORMA_PAGO VARCHAR(20),
    REFERENCIA VARCHAR(50),
    BANCO_CODIGO VARCHAR(15),
    CUENTA_BANCARIA_CODIGO VARCHAR(15),
    NOTAS VARCHAR(255),
    USUARIO_CODIGO VARCHAR(15),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PAGOS_COMPRAS PRIMARY KEY (CORRELATIVO),
    CONSTRAINT FK_PAGOS_COMPRAS FOREIGN KEY (COMPRA_CORRELATIVO) REFERENCES COMPRAS(CORRELATIVO)
);

CREATE INDEX IDX_PAGOS_COMPRAS_DOCUMENTO ON PAGOS_COMPRAS(DOCUMENTO);
CREATE INDEX IDX_PAGOS_COMPRAS_FECHA ON PAGOS_COMPRAS(FECHA);

-- ============================================================================
-- 7. MÓDULO INVENTARIO
-- ============================================================================

-- Tabla: TIPOS_MOVIMIENTO_INVENTARIO
CREATE TABLE TIPOS_MOVIMIENTO_INVENTARIO (
    CODIGO CHAR(3) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(255),
    AFECTA_COSTO CHAR(1) DEFAULT 'S',
    AFECTA_INVENTARIO CHAR(1) DEFAULT 'S',
    AFECTA_CONTABILIDAD CHAR(1) DEFAULT 'S',
    SIGNO CHAR(1) DEFAULT '+', -- + para entrada, - para salida
    ESTATUS CHAR(1) DEFAULT 'A',
    CONSTRAINT PK_TIPOS_MOVIMIENTO_INVENTARIO PRIMARY KEY (CODIGO)
);

INSERT INTO TIPOS_MOVIMIENTO_INVENTARIO (CODIGO, NOMBRE, DESCRIPCION, AFECTA_COSTO, SIGNO) VALUES
('ENT', 'Entrada', 'Entrada de inventario', 'S', '+'),
('SAL', 'Salida', 'Salida de inventario', 'S', '-'),
('TRA', 'Traspaso', 'Traspaso entre depósitos', 'N', '0'),
('AJU', 'Ajuste', 'Ajuste de inventario', 'S', '+'),
('INV', 'Inventario', 'Conteo físico', 'S', '+'),
('DEV', 'Devolución', 'Devolución de venta', 'S', '+'),
('DSC', 'Descarte', 'Descarte de producto', 'N', '-');

-- Tabla: MOVIMIENTOS_INVENTARIO
CREATE TABLE MOVIMIENTOS_INVENTARIO (
    CORRELATIVO INTEGER NOT NULL,
    DOCUMENTO VARCHAR(10) NOT NULL,
    TIPO_DOCUMENTO CHAR(3) NOT NULL,
    FECHA DATE NOT NULL,
    HORA TIME,
    DEPOSITO_ORIGEN_CODIGO VARCHAR(15),
    DEPOSITO_DESTINO_CODIGO VARCHAR(15),
    PRODUCTO_CODIGO VARCHAR(15) NOT NULL,
    CANTIDAD DECIMAL(18,4) NOT NULL,
    COSTO DECIMAL(18,4),
    COSTO_PROMEDIO DECIMAL(18,4),
    COSTO_TOTAL DECIMAL(18,2),
    SERIAL VARCHAR(50),
    LOTE VARCHAR(50),
    FECHA_VENCIMIENTO DATE,
    REFERENCIA VARCHAR(50),
    NOTAS VARCHAR(255),
    USUARIO_CODIGO VARCHAR(15),
    ESTACION VARCHAR(30),
    DOCUMENTO_ORIGEN VARCHAR(10),
    DOCUMENTO_DESTINO VARCHAR(10),
    ESTATUS CHAR(1) DEFAULT 'R', -- R=Registrado, A=Anulado
    PROCESADO CHAR(1) DEFAULT 'F',
    FECHA_PROCESO TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_MOVIMIENTOS_INVENTARIO PRIMARY KEY (CORRELATIVO),
    CONSTRAINT FK_MOVIMIENTOS_DEPOSITO_ORIGEN FOREIGN KEY (DEPOSITO_ORIGEN_CODIGO) REFERENCES DEPOSITOS(CODIGO),
    CONSTRAINT FK_MOVIMIENTOS_DEPOSITO_DESTINO FOREIGN KEY (DEPOSITO_DESTINO_CODIGO) REFERENCES DEPOSITOS(CODIGO),
    CONSTRAINT FK_MOVIMIENTOS_PRODUCTO FOREIGN KEY (PRODUCTO_CODIGO) REFERENCES PRODUCTOS(CODIGO),
    CONSTRAINT FK_MOVIMIENTOS_USUARIO FOREIGN KEY (USUARIO_CODIGO) REFERENCES USUARIOS(CODIGO)
);

CREATE INDEX IDX_MOVIMIENTOS_DOCUMENTO ON MOVIMIENTOS_INVENTARIO(DOCUMENTO);
CREATE INDEX IDX_MOVIMIENTOS_FECHA ON MOVIMIENTOS_INVENTARIO(FECHA);
CREATE INDEX IDX_MOVIMIENTOS_PRODUCTO ON MOVIMIENTOS_INVENTARIO(PRODUCTO_CODIGO);
CREATE INDEX IDX_MOVIMIENTOS_LOTE ON MOVIMIENTOS_INVENTARIO(LOTE);
CREATE INDEX IDX_MOVIMIENTOS_ESTADO ON MOVIMIENTOS_INVENTARIO(ESTATUS);

-- Tabla: KARDEX (Historial de movimientos por producto)
CREATE TABLE KARDEX (
    PRODUCTO_CODIGO VARCHAR(15) NOT NULL,
    DEPOSITO_CODIGO VARCHAR(15) NOT NULL,
    FECHA DATE NOT NULL,
    HORA TIME,
    DOCUMENTO VARCHAR(10) NOT NULL,
    TIPO_MOVIMIENTO CHAR(3) NOT NULL,
    REFERENCIA VARCHAR(50),
    ENTRADA_CANTIDAD DECIMAL(18,4) DEFAULT 0,
    ENTRADA_COSTO DECIMAL(18,4) DEFAULT 0,
    ENTRADA_TOTAL DECIMAL(18,2) DEFAULT 0,
    SALIDA_CANTIDAD DECIMAL(18,4) DEFAULT 0,
    SALIDA_COSTO DECIMAL(18,4) DEFAULT 0,
    SALIDA_TOTAL DECIMAL(18,2) DEFAULT 0,
    SALDO_CANTIDAD DECIMAL(18,4) DEFAULT 0,
    SALDO_COSTO DECIMAL(18,4) DEFAULT 0,
    SALDO_TOTAL DECIMAL(18,2) DEFAULT 0,
    LOTE VARCHAR(50),
    SERIAL VARCHAR(50),
    USUARIO_CODIGO VARCHAR(15),
    CONSTRAINT PK_KARDEX PRIMARY KEY (PRODUCTO_CODIGO, DEPOSITO_CODIGO, FECHA, DOCUMENTO, TIPO_MOVIMIENTO),
    CONSTRAINT FK_KARDEX_PRODUCTO FOREIGN KEY (PRODUCTO_CODIGO) REFERENCES PRODUCTOS(CODIGO),
    CONSTRAINT FK_KARDEX_DEPOSITO FOREIGN KEY (DEPOSITO_CODIGO) REFERENCES DEPOSITOS(CODIGO)
);

CREATE INDEX IDX_KARDEX_FECHA ON KARDEX(FECHA);
CREATE INDEX IDX_KARDEX_DOCUMENTO ON KARDEX(DOCUMENTO);

-- Tabla: AJUSTES_INVENTARIO
CREATE TABLE AJUSTES_INVENTARIO (
    CORRELATIVO INTEGER NOT NULL,
    DOCUMENTO VARCHAR(10) NOT NULL,
    FECHA DATE NOT NULL,
    DEPOSITO_CODIGO VARCHAR(15) NOT NULL,
    MOTIVO VARCHAR(255),
    TOTAL_ITEMS INTEGER,
    TOTAL_DIFERENCIA DECIMAL(18,2),
    ESTATUS CHAR(1) DEFAULT 'P', -- P=Pendiente, A=Aprobado, R=Rechazado
    APROBADO_POR VARCHAR(15),
    FECHA_APROBACION DATE,
    USUARIO_CODIGO VARCHAR(15),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_AJUSTES_INVENTARIO PRIMARY KEY (CORRELATIVO),
    CONSTRAINT FK_AJUSTES_DEPOSITO FOREIGN KEY (DEPOSITO_CODIGO) REFERENCES DEPOSITOS(CODIGO)
);

-- Tabla: AJUSTES_INVENTARIO_DESGLOSE
CREATE TABLE AJUSTES_INVENTARIO_DESGLOSE (
    CORRELATIVO INTEGER NOT NULL,
    CODIGO INTEGER NOT NULL,
    PRODUCTO_CODIGO VARCHAR(15) NOT NULL,
    CANTIDAD_SISTEMA DECIMAL(18,4),
    CANTIDAD_FISICA DECIMAL(18,4),
    DIFERENCIA DECIMAL(18,4),
    COSTO DECIMAL(18,4),
    TOTAL_DIFERENCIA DECIMAL(18,2),
    MOTIVO VARCHAR(255),
    CONSTRAINT PK_AJUSTES_DESGLOSE PRIMARY KEY (CORRELATIVO, CODIGO),
    CONSTRAINT FK_AJUSTES_DESGLOSE FOREIGN KEY (CORRELATIVO) REFERENCES AJUSTES_INVENTARIO(CORRELATIVO) ON DELETE CASCADE,
    CONSTRAINT FK_AJUSTES_DESGLOSE_PRODUCTO FOREIGN KEY (PRODUCTO_CODIGO) REFERENCES PRODUCTOS(CODIGO)
);

-- ============================================================================
-- CONTINUARÁ... (Módulos Banco, Caja, Nómina, Contabilidad)
-- ============================================================================
