-- ============================================================================
-- VIOLET ERP - BASE DE DATOS FIREBIRD SQL - PARTE 3
-- MÓDULOS: BANCO, CAJA, NÓMINA, CONTABILIDAD
-- ============================================================================

SET NAMES UTF8;

-- ============================================================================
-- 8. MÓDULO BANCO
-- ============================================================================

-- Tabla: BANCOS
CREATE TABLE BANCOS (
    CODIGO VARCHAR(15) NOT NULL,
    NOMBRE VARCHAR(160) NOT NULL,
    CODIGO_BANCARIO VARCHAR(10),
    DIRECCION VARCHAR(255),
    TELEFONO VARCHAR(40),
    EMAIL VARCHAR(60),
    PAGINA_WEB VARCHAR(100),
    ESTATUS CHAR(1) DEFAULT 'A',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_BANCOS PRIMARY KEY (CODIGO)
);

-- Datos iniciales de bancos principales de Venezuela
INSERT INTO BANCOS (CODIGO, NOMBRE, CODIGO_BANCARIO) VALUES
('0102', 'Banco de Venezuela', '0102'),
('0104', 'Banco Mercantil', '0104'),
('0105', 'Banco Provincial', '0105'),
('0108', 'Banco Caroní', '0108'),
('0114', 'Bancaribe', '0114'),
('0115', 'Exterior Banco', '0115'),
('0116', 'Banco Occidental de Descuento', '0116'),
('0128', 'Banco Caroní', '0128'),
('0134', 'Banesco', '0134'),
('0137', 'Banco Sofitasa', '0137'),
('0138', 'Banco Activo', '0138'),
('0151', 'Banco Fondo Común', '0151'),
('0156', 'Banco del Tesoro', '0156'),
('0157', 'Delsur Banco Universal', '0157'),
('0163', 'Banco Agrícola', '0163'),
('0166', 'Banco de Venezuela', '0166'),
('0168', 'Bancrecer', '0168'),
('0169', 'Mi Banco', '0169'),
('0171', 'Banco Venezolano de Crédito', '0171'),
('0172', 'Bancamiga', '0172'),
('0174', 'Banco Bicentenario', '0174'),
('0175', 'Banco del Sur', '0175');

-- Tabla: CUENTAS_BANCARIAS
CREATE TABLE CUENTAS_BANCARIAS (
    CODIGO VARCHAR(15) NOT NULL,
    BANCO_CODIGO VARCHAR(15) NOT NULL,
    NUMERO_CUENTA VARCHAR(30) NOT NULL,
    TIPO_CUENTA CHAR(1) DEFAULT 'C', -- C=Corriente, A=Ahorro
    MONEDA_CODIGO VARCHAR(15),
    SALDO DECIMAL(18,2) DEFAULT 0,
    SALDO_INICIAL DECIMAL(18,2),
    FECHA_SALDO_INICIAL DATE,
    ESTATUS CHAR(1) DEFAULT 'A',
    SUCURSAL_CODIGO VARCHAR(15),
    RESPONSABLE VARCHAR(100),
    TELEFONO VARCHAR(40),
    EMAIL VARCHAR(60),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CUENTAS_BANCARIAS PRIMARY KEY (CODIGO),
    CONSTRAINT FK_CUENTAS_BANCO FOREIGN KEY (BANCO_CODIGO) REFERENCES BANCOS(CODIGO),
    CONSTRAINT UK_CUENTAS_NUMERO UNIQUE (NUMERO_CUENTA)
);

CREATE INDEX IDX_CUENTAS_BANCO ON CUENTAS_BANCARIAS(BANCO_CODIGO);
CREATE INDEX IDX_CUENTAS_ESTADO ON CUENTAS_BANCARIAS(ESTATUS);

-- Tabla: MOVIMIENTOS_BANCOS
CREATE TABLE MOVIMIENTOS_BANCOS (
    CORRELATIVO INTEGER NOT NULL,
    CUENTA_CODIGO VARCHAR(15) NOT NULL,
    DOCUMENTO VARCHAR(20) NOT NULL,
    TIPO_MOVIMIENTO CHAR(3) NOT NULL, -- DEP=Depósito, CHE=Cheque, TRA=Transferencia, NCR=Nota Crédito, NDB=Nota Débito
    FECHA DATE NOT NULL,
    FECHA_CONTABLE DATE,
    BENEFICIARIO VARCHAR(160),
    DESCRIPCION VARCHAR(255),
    REFERENCIA VARCHAR(50),
    DEBITO DECIMAL(18,2) DEFAULT 0,
    CREDITO DECIMAL(18,2) DEFAULT 0,
    SALDO_ANTERIOR DECIMAL(18,2),
    SALDO_ACTUAL DECIMAL(18,2),
    CONCILIADO CHAR(1) DEFAULT 'F',
    FECHA_CONCILIACION DATE,
    PERIODO_CONCILIACION VARCHAR(7), -- Formato YYYY-MM
    USUARIO_CODIGO VARCHAR(15),
    ESTATUS CHAR(1) DEFAULT 'R', -- R=Registrado, A=Anulado
    DOCUMENTO_RELACIONADO VARCHAR(20),
    CUENTA_CONTABLE VARCHAR(22),
    CENTRO_COSTO_CODIGO VARCHAR(15),
    NOTAS VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_MOVIMIENTOS_BANCOS PRIMARY KEY (CORRELATIVO),
    CONSTRAINT FK_MOVIMIENTOS_BANCO_CUENTA FOREIGN KEY (CUENTA_CODIGO) REFERENCES CUENTAS_BANCARIAS(CODIGO),
    CONSTRAINT FK_MOVIMIENTOS_BANCO_USUARIO FOREIGN KEY (USUARIO_CODIGO) REFERENCES USUARIOS(CODIGO)
);

CREATE INDEX IDX_MOVIMIENTOS_BANCO_CUENTA ON MOVIMIENTOS_BANCOS(CUENTA_CODIGO);
CREATE INDEX IDX_MOVIMIENTOS_BANCO_FECHA ON MOVIMIENTOS_BANCOS(FECHA);
CREATE INDEX IDX_MOVIMIENTOS_BANCO_DOCUMENTO ON MOVIMIENTOS_BANCOS(DOCUMENTO);
CREATE INDEX IDX_MOVIMIENTOS_BANCO_CONCILIADO ON MOVIMIENTOS_BANCOS(CONCILIADO);
CREATE INDEX IDX_MOVIMIENTOS_BANCO_ESTADO ON MOVIMIENTOS_BANCOS(ESTATUS);

-- Tabla: CHEQUES
CREATE TABLE CHEQUES (
    CORRELATIVO INTEGER NOT NULL,
    CUENTA_CODIGO VARCHAR(15) NOT NULL,
    NUMERO_CHEQUE VARCHAR(20) NOT NULL,
    FECHA_EMISION DATE NOT NULL,
    BENEFICIARIO_CODIGO VARCHAR(15),
    BENEFICIARIO_NOMBRE VARCHAR(160),
    BENEFICIARIO_RIF VARCHAR(20),
    MONTO DECIMAL(18,2) NOT NULL,
    MONTO_LETRAS VARCHAR(255),
    ESTATUS CHAR(1) DEFAULT 'E', -- E=Emitido, C=Cobrado, A=Anulado, R=Rechazado
    FECHA_COBRO DATE,
    DOCUMENTO_PAGO VARCHAR(10),
    CUENTA_CONTABLE VARCHAR(22),
    CENTRO_COSTO_CODIGO VARCHAR(15),
    NOTAS VARCHAR(255),
    USUARIO_CODIGO VARCHAR(15),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CHEQUES PRIMARY KEY (CORRELATIVO),
    CONSTRAINT FK_CHEQUES_CUENTA FOREIGN KEY (CUENTA_CODIGO) REFERENCES CUENTAS_BANCARIAS(CODIGO),
    CONSTRAINT UK_CHEQUE_NUMERO UNIQUE (CUENTA_CODIGO, NUMERO_CHEQUE)
);

CREATE INDEX IDX_CHEQUES_NUMERO ON CHEQUES(NUMERO_CHEQUE);
CREATE INDEX IDX_CHEQUES_ESTADO ON CHEQUES(ESTATUS);
CREATE INDEX IDX_CHEQUES_FECHA ON CHEQUES(FECHA_EMISION);

-- Tabla: CONCILIACIONES_BANCARIAS
CREATE TABLE CONCILIACIONES_BANCARIAS (
    CORRELATIVO INTEGER NOT NULL,
    CUENTA_CODIGO VARCHAR(15) NOT NULL,
    PERIODO VARCHAR(7) NOT NULL, -- Formato YYYY-MM
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,
    SALDO_BANCO_INICIAL DECIMAL(18,2),
    SALDO_BANCO_FINAL DECIMAL(18,2),
    SALDO_LIBRO_INICIAL DECIMAL(18,2),
    SALDO_LIBRO_FINAL DECIMAL(18,2),
    DEPOSITOS_EN_TRANSITO DECIMAL(18,2) DEFAULT 0,
    CHEQUES_NO_COBRADOS DECIMAL(18,2) DEFAULT 0,
    NOTAS_DEBITO DECIMAL(18,2) DEFAULT 0,
    NOTAS_CREDITO DECIMAL(18,2) DEFAULT 0,
    ERRORES_BANCO DECIMAL(18,2) DEFAULT 0,
    ERRORES_LIBRO DECIMAL(18,2) DEFAULT 0,
    DIFERENCIA DECIMAL(18,2) DEFAULT 0,
    CONCILIADO CHAR(1) DEFAULT 'F',
    FECHA_CONCILIACION DATE,
    USUARIO_CODIGO VARCHAR(15),
    NOTAS VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CONCILIACIONES_BANCARIAS PRIMARY KEY (CORRELATIVO),
    CONSTRAINT FK_CONCILIACIONES_CUENTA FOREIGN KEY (CUENTA_CODIGO) REFERENCES CUENTAS_BANCARIAS(CODIGO),
    CONSTRAINT UK_CONCILIACIONES_PERIODO UNIQUE (CUENTA_CODIGO, PERIODO)
);

CREATE INDEX IDX_CONCILIACIONES_PERIODO ON CONCILIACIONES_BANCARIAS(PERIODO);
CREATE INDEX IDX_CONCILIACIONES_ESTADO ON CONCILIACIONES_BANCARIAS(CONCILIADO);

-- Tabla: TRANSFERENCIAS_BANCARIAS
CREATE TABLE TRANSFERENCIAS_BANCARIAS (
    CORRELATIVO INTEGER NOT NULL,
    DOCUMENTO VARCHAR(20) NOT NULL,
    FECHA DATE NOT NULL,
    CUENTA_ORIGEN_CODIGO VARCHAR(15) NOT NULL,
    CUENTA_DESTINO_CODIGO VARCHAR(15) NOT NULL,
    MONTO DECIMAL(18,2) NOT NULL,
    BENEFICIARIO VARCHAR(160),
    DESCRIPCION VARCHAR(255),
    REFERENCIA VARCHAR(50),
    ESTATUS CHAR(1) DEFAULT 'P', -- P=Pendiente, R=Realizada, A=Anulada
    FECHA_REALIZACION DATE,
    USUARIO_CODIGO VARCHAR(15),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TRANSFERENCIAS_BANCARIAS PRIMARY KEY (CORRELATIVO),
    CONSTRAINT FK_TRANSFERENCIAS_ORIGEN FOREIGN KEY (CUENTA_ORIGEN_CODIGO) REFERENCES CUENTAS_BANCARIAS(CODIGO),
    CONSTRAINT FK_TRANSFERENCIAS_DESTINO FOREIGN KEY (CUENTA_DESTINO_CODIGO) REFERENCES CUENTAS_BANCARIAS(CODIGO)
);

-- ============================================================================
-- 9. MÓDULO CAJA
-- ============================================================================

-- Tabla: CAJAS
CREATE TABLE CAJAS (
    CODIGO VARCHAR(15) NOT NULL,
    NOMBRE VARCHAR(160) NOT NULL,
    UBICACION VARCHAR(255),
    RESPONSABLE VARCHAR(100),
    SALDO_INICIAL DECIMAL(18,2) DEFAULT 0,
    SALDO_ACTUAL DECIMAL(18,2) DEFAULT 0,
    LIMITE_RETIRO DECIMAL(18,2),
    ESTATUS CHAR(1) DEFAULT 'A',
    SUCURSAL_CODIGO VARCHAR(15),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CAJAS PRIMARY KEY (CODIGO)
);

CREATE INDEX IDX_CAJAS_ESTADO ON CAJAS(ESTATUS);

-- Tabla: MOVIMIENTOS_CAJA
CREATE TABLE MOVIMIENTOS_CAJA (
    CORRELATIVO INTEGER NOT NULL,
    CAJA_CODIGO VARCHAR(15) NOT NULL,
    DOCUMENTO VARCHAR(10) NOT NULL,
    TIPO_MOVIMIENTO CHAR(3) NOT NULL, -- ING=Ingreso, EGR=Egreso
    FECHA_HORA TIMESTAMP NOT NULL,
    DESCRIPCION VARCHAR(255),
    REFERENCIA VARCHAR(50),
    MONTO DECIMAL(18,2) NOT NULL,
    FORMA_PAGO VARCHAR(20), -- EFECTIVO, CHEQUE, TRANSFERENCIA, TARJETA
    BANCO_CODIGO VARCHAR(15),
    CUENTA_BANCARIA_CODIGO VARCHAR(15),
    SALDO_ANTERIOR DECIMAL(18,2),
    SALDO_ACTUAL DECIMAL(18,2),
    CUENTA_CONTABLE VARCHAR(22),
    CENTRO_COSTO_CODIGO VARCHAR(15),
    USUARIO_CODIGO VARCHAR(15),
    ESTATUS CHAR(1) DEFAULT 'R', -- R=Registrado, A=Anulado
    NOTAS VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_MOVIMIENTOS_CAJA PRIMARY KEY (CORRELATIVO),
    CONSTRAINT FK_MOVIMIENTOS_CAJA FOREIGN KEY (CAJA_CODIGO) REFERENCES CAJAS(CODIGO),
    CONSTRAINT FK_MOVIMIENTOS_CAJA_USUARIO FOREIGN KEY (USUARIO_CODIGO) REFERENCES USUARIOS(CODIGO)
);

CREATE INDEX IDX_MOVIMIENTOS_CAJA_FECHA ON MOVIMIENTOS_CAJA(FECHA_HORA);
CREATE INDEX IDX_MOVIMIENTOS_CAJA_DOCUMENTO ON MOVIMIENTOS_CAJA(DOCUMENTO);
CREATE INDEX IDX_MOVIMIENTOS_CAJA_ESTADO ON MOVIMIENTOS_CAJA(ESTATUS);

-- Tabla: CIERRES_CAJA
CREATE TABLE CIERRES_CAJA (
    CORRELATIVO INTEGER NOT NULL,
    CAJA_CODIGO VARCHAR(15) NOT NULL,
    FECHA_INICIO TIMESTAMP NOT NULL,
    FECHA_FIN TIMESTAMP,
    SALDO_INICIAL DECIMAL(18,2),
    TOTAL_INGRESOS DECIMAL(18,2) DEFAULT 0,
    TOTAL_EGRESOS DECIMAL(18,2) DEFAULT 0,
    SALDO_SISTEMA DECIMAL(18,2),
    SALDO_FISICO DECIMAL(18,2),
    DIFERENCIA DECIMAL(18,2),
    MOTIVO_DIFERENCIA VARCHAR(255),
    USUARIO_CODIGO VARCHAR(15),
    SUPERVISOR_CODIGO VARCHAR(15),
    ESTATUS CHAR(1) DEFAULT 'A', -- A=Abierto, C=Cerrado
    FECHA_CIERRE TIMESTAMP,
    NOTAS VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CIERRES_CAJA PRIMARY KEY (CORRELATIVO),
    CONSTRAINT FK_CIERRES_CAJA FOREIGN KEY (CAJA_CODIGO) REFERENCES CAJAS(CODIGO),
    CONSTRAINT FK_CIERRES_USUARIO FOREIGN KEY (USUARIO_CODIGO) REFERENCES USUARIOS(CODIGO)
);

CREATE INDEX IDX_CIERRES_CAJA_FECHA ON CIERRES_CAJA(FECHA_INICIO);
CREATE INDEX IDX_CIERRES_CAJA_ESTADO ON CIERRES_CAJA(ESTATUS);

-- Tabla: RECIBOS_CAJA
CREATE TABLE RECIBOS_CAJA (
    CORRELATIVO INTEGER NOT NULL,
    NUMERO_RECIBO VARCHAR(20) NOT NULL,
    FECHA DATE NOT NULL,
    TIPO CHAR(1) NOT NULL, -- I=Ingreso, E=Egreso
    MONTO DECIMAL(18,2) NOT NULL,
    DESCRIPCION VARCHAR(255),
    BENEFICIARIO VARCHAR(160),
    FORMA_PAGO VARCHAR(20),
    CAJA_CODIGO VARCHAR(15),
    USUARIO_CODIGO VARCHAR(15),
    IMPRESO CHAR(1) DEFAULT 'F',
    FECHA_IMPRESION TIMESTAMP,
    NOTAS VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_RECIBOS_CAJA PRIMARY KEY (CORRELATIVO),
    CONSTRAINT FK_RECIBOS_CAJA FOREIGN KEY (CAJA_CODIGO) REFERENCES CAJAS(CODIGO),
    CONSTRAINT UK_RECIBOS_NUMERO UNIQUE (NUMERO_RECIBO)
);

CREATE INDEX IDX_RECIBOS_CAJA_FECHA ON RECIBOS_CAJA(FECHA);
CREATE INDEX IDX_RECIBOS_CAJA_NUMERO ON RECIBOS_CAJA(NUMERO_RECIBO);

-- Tabla: ARQUEOS_CAJA
CREATE TABLE ARQUEOS_CAJA (
    CORRELATIVO INTEGER NOT NULL,
    CAJA_CODIGO VARCHAR(15) NOT NULL,
    FECHA DATE NOT NULL,
    HORA TIME NOT NULL,
    SALDO_SISTEMA DECIMAL(18,2),
    SALDO_FISICO DECIMAL(18,2),
    DIFERENCIA DECIMAL(18,2),
    RESPONSABLE VARCHAR(100),
    SUPERVISOR VARCHAR(100),
    ESTATUS CHAR(1) DEFAULT 'P', -- P=Pendiente, C=Completado
    NOTAS VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_ARQUEOS_CAJA PRIMARY KEY (CORRELATIVO),
    CONSTRAINT FK_ARQUEOS_CAJA FOREIGN KEY (CAJA_CODIGO) REFERENCES CAJAS(CODIGO)
);

-- Tabla: DETALLE_ARQUEO (Billetes y monedas)
CREATE TABLE ARQUEOS_CAJA_DETALLE (
    CORRELATIVO INTEGER NOT NULL,
    CODIGO INTEGER NOT NULL,
    DENOMINACION DECIMAL(18,2) NOT NULL,
    CANTIDAD INTEGER NOT NULL,
    TOTAL DECIMAL(18,2) NOT NULL,
    TIPO CHAR(1) DEFAULT 'B', -- B=Billete, M=Moneda
    CONSTRAINT PK_ARQUEOS_DETALLE PRIMARY KEY (CORRELATIVO, CODIGO),
    CONSTRAINT FK_ARQUEOS_DETALLE FOREIGN KEY (CORRELATIVO) REFERENCES ARQUEOS_CAJA(CORRELATIVO) ON DELETE CASCADE
);

-- ============================================================================
-- 10. MÓDULO NÓMINA
-- ============================================================================

-- Tabla: DEPARTAMENTOS
CREATE TABLE DEPARTAMENTOS (
    CODIGO VARCHAR(15) NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(255),
    JEFE_CODIGO VARCHAR(15),
    PRESUPUESTO DECIMAL(18,2),
    ESTATUS CHAR(1) DEFAULT 'A',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_DEPARTAMENTOS PRIMARY KEY (CODIGO)
);

-- Tabla: CARGOS
CREATE TABLE CARGOS (
    CODIGO VARCHAR(15) NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(255),
    SUELDO_MINIMO DECIMAL(18,2),
    SUELDO_MAXIMO DECIMAL(18,2),
    DEPARTAMENTO_CODIGO VARCHAR(15),
    ESTATUS CHAR(1) DEFAULT 'A',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CARGOS PRIMARY KEY (CODIGO),
    CONSTRAINT FK_CARGOS_DEPARTAMENTO FOREIGN KEY (DEPARTAMENTO_CODIGO) REFERENCES DEPARTAMENTOS(CODIGO)
);

-- Tabla: EMPLEADOS
CREATE TABLE EMPLEADOS (
    CODIGO VARCHAR(15) NOT NULL,
    NOMBRE VARCHAR(160) NOT NULL,
    APELLIDO VARCHAR(160) NOT NULL,
    CEDULA VARCHAR(20) NOT NULL,
    RIF VARCHAR(20),
    FECHA_NACIMIENTO DATE,
    DIRECCION VARCHAR(255),
    TELEFONO VARCHAR(40),
    CELULAR VARCHAR(40),
    CORREO_ELECTRONICO VARCHAR(60),
    DEPARTAMENTO_CODIGO VARCHAR(15),
    CARGO_CODIGO VARCHAR(15),
    SUELDO_BASE DECIMAL(18,2),
    COMISION DECIMAL(18,2) DEFAULT 0,
    BONO_DECIMAL(18,2) DEFAULT 0,
    FECHA_INGRESO DATE NOT NULL,
    FECHA_EGRESO DATE,
    MOTIVO_EGRESO VARCHAR(255),
    ESTATUS CHAR(1) DEFAULT 'A', -- A=Activo, V=Vacaciones, I=Incapacidad, T=Terminado
    CUENTA_BANCARIA_CODIGO VARCHAR(15),
    TIPO_PERSONAL CHAR(1) DEFAULT 'O', -- O=Ordinario, T=Temporal, P=Prueba
    DIAS_VACACIONES INTEGER DEFAULT 15,
    DIAS_VACACIONES_DISFRUTADOS INTEGER DEFAULT 0,
    DIAS_VACACIONES_PENDIENTES INTEGER DEFAULT 15,
    CARGAS_FAMILIARES INTEGER DEFAULT 0,
    TIPO_SANGRE VARCHAR(5),
    TALLA_CAMISA VARCHAR(5),
    TALLA_PANTALON VARCHAR(5),
    FOTO BLOB SUB_TYPE BINARY,
    NOTAS VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_EMPLEADOS PRIMARY KEY (CODIGO),
    CONSTRAINT UK_EMPLEADOS_CEDULA UNIQUE (CEDULA),
    CONSTRAINT FK_EMPLEADOS_DEPARTAMENTO FOREIGN KEY (DEPARTAMENTO_CODIGO) REFERENCES DEPARTAMENTOS(CODIGO),
    CONSTRAINT FK_EMPLEADOS_CARGO FOREIGN KEY (CARGO_CODIGO) REFERENCES CARGOS(CODIGO),
    CONSTRAINT FK_EMPLEADOS_CUENTA FOREIGN KEY (CUENTA_BANCARIA_CODIGO) REFERENCES CUENTAS_BANCARIAS(CODIGO)
);

CREATE INDEX IDX_EMPLEADOS_CEDULA ON EMPLEADOS(CEDULA);
CREATE INDEX IDX_EMPLEADOS_NOMBRE ON EMPLEADOS(NOMBRE, APELLIDO);
CREATE INDEX IDX_EMPLEADOS_DEPARTAMENTO ON EMPLEADOS(DEPARTAMENTO_CODIGO);
CREATE INDEX IDX_EMPLEADOS_ESTADO ON EMPLEADOS(ESTATUS);

-- Tabla: ASIGNACIONES
CREATE TABLE ASIGNACIONES (
    CODIGO VARCHAR(15) NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(255),
    TIPO CHAR(1) DEFAULT 'F', -- F=Fijo, V=Variable, P=Porcentaje
    MONTO_FIJO DECIMAL(18,2),
    PORCENTAJE DECIMAL(5,2),
    AFECTA_BONO CHAR(1) DEFAULT 'S',
    AFECTA_VACACIONES CHAR(1) DEFAULT 'S',
    AFECTA_UTILIDADES CHAR(1) DEFAULT 'S',
    CUENTA_CONTABLE VARCHAR(22),
    ESTATUS CHAR(1) DEFAULT 'A',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_ASIGNACIONES PRIMARY KEY (CODIGO)
);

-- Tabla: DEDUCCIONES
CREATE TABLE DEDUCCIONES (
    CODIGO VARCHAR(15) NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(255),
    TIPO CHAR(1) DEFAULT 'L', -- L=Ley, V=Voluntaria
    PORCENTAJE DECIMAL(5,2),
    MONTO_FIJO DECIMAL(18,2),
    CUENTA_CONTABLE VARCHAR(22),
    ESTATUS CHAR(1) DEFAULT 'A',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_DEDUCCIONES PRIMARY KEY (CODIGO)
);

-- Datos iniciales de deducciones de ley en Venezuela
INSERT INTO DEDUCCIONES (CODIGO, NOMBRE, TIPO, PORCENTAJE, DESCRIPCION) VALUES
('IVSS', 'IVSS', 'L', 4.0, 'Instituto Venezolano de los Seguros Sociales'),
('FAOV', 'FAOV', 'L', 1.0, 'Fondo de Ahorro Obligatorio para la Vivienda'),
('INCES', 'INCES', 'L', 0.5, 'Instituto Nacional de Capacitación y Educación Socialista'),
('ISLR', 'ISLR', 'L', 0, 'Impuesto Sobre la Renta - Variable según tabla');

-- Tabla: NOMINA (Encabezado)
CREATE TABLE NOMINA (
    CORRELATIVO INTEGER NOT NULL,
    PERIODO VARCHAR(7) NOT NULL, -- Formato YYYY-MM
    TIPO_NOMINA CHAR(1) NOT NULL, -- R=Regular, V=Vacaciones, U=Utilidades, B=Bono
    FECHA_PAGO DATE NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,
    TOTAL_EMPLEADOS INTEGER,
    TOTAL_ASIGNACIONES DECIMAL(18,2) DEFAULT 0,
    TOTAL_DEDUCCIONES DECIMAL(18,2) DEFAULT 0,
    TOTAL_NETO DECIMAL(18,2) DEFAULT 0,
    TOTAL_PATRONAL DECIMAL(18,2) DEFAULT 0,
    ESTATUS CHAR(1) DEFAULT 'P', -- P=Pendiente, Q=Quitada, A=Anulada
    USUARIO_CODIGO VARCHAR(15),
    APROBADO_POR VARCHAR(15),
    FECHA_APROBACION DATE,
    NOTAS VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_NOMINA PRIMARY KEY (CORRELATIVO)
);

CREATE INDEX IDX_NOMINA_PERIODO ON NOMINA(PERIODO);
CREATE INDEX IDX_NOMINA_FECHA ON NOMINA(FECHA_PAGO);
CREATE INDEX IDX_NOMINA_ESTADO ON NOMINA(ESTATUS);

-- Tabla: NOMINA_DETALLE
CREATE TABLE NOMINA_DETALLE (
    CORRELATIVO INTEGER NOT NULL,
    EMPLEADO_CODIGO VARCHAR(15) NOT NULL,
    DIAS_TRABAJADOS DECIMAL(5,2),
    SUELDO_DEVENGADO DECIMAL(18,2),
    HORAS_EXTRAS DECIMAL(18,2) DEFAULT 0,
    COMISIONES DECIMAL(18,2) DEFAULT 0,
    BONOS DECIMAL(18,2) DEFAULT 0,
    TOTAL_ASIGNACIONES DECIMAL(18,2),
    TOTAL_DEDUCCIONES DECIMAL(18,2),
    SALDO_NETO DECIMAL(18,2),
    CUENTA_BANCARIA_CODIGO VARCHAR(15),
    FORMA_PAGO VARCHAR(20),
    PAGADO CHAR(1) DEFAULT 'F',
    FECHA_PAGO DATE,
    RECIBO_IMPRESO CHAR(1) DEFAULT 'F',
    CONSTRAINT PK_NOMINA_DETALLE PRIMARY KEY (CORRELATIVO, EMPLEADO_CODIGO),
    CONSTRAINT FK_NOMINA_DETALLE_NOMINA FOREIGN KEY (CORRELATIVO) REFERENCES NOMINA(CORRELATIVO) ON DELETE CASCADE,
    CONSTRAINT FK_NOMINA_DETALLE_EMPLEADO FOREIGN KEY (EMPLEADO_CODIGO) REFERENCES EMPLEADOS(CODIGO)
);

-- Tabla: NOMINA_ASIGNACIONES (Desglose)
CREATE TABLE NOMINA_ASIGNACIONES (
    CORRELATIVO INTEGER NOT NULL,
    EMPLEADO_CODIGO VARCHAR(15) NOT NULL,
    ASIGNACION_CODIGO VARCHAR(15) NOT NULL,
    MONTO DECIMAL(18,2) NOT NULL,
    PORCENTAJE DECIMAL(5,2),
    DIAS DECIMAL(5,2),
    NOTAS VARCHAR(255),
    CONSTRAINT PK_NOMINA_ASIGNACIONES PRIMARY KEY (CORRELATIVO, EMPLEADO_CODIGO, ASIGNACION_CODIGO),
    CONSTRAINT FK_NOMINA_ASIGNACIONES FOREIGN KEY (CORRELATIVO, EMPLEADO_CODIGO) REFERENCES NOMINA_DETALLE(CORRELATIVO, EMPLEADO_CODIGO) ON DELETE CASCADE
);

-- Tabla: NOMINA_DEDUCCIONES (Desglose)
CREATE TABLE NOMINA_DEDUCCIONES (
    CORRELATIVO INTEGER NOT NULL,
    EMPLEADO_CODIGO VARCHAR(15) NOT NULL,
    DEDUCCION_CODIGO VARCHAR(15) NOT NULL,
    MONTO DECIMAL(18,2) NOT NULL,
    PORCENTAJE DECIMAL(5,2),
    BASE_CALCULO DECIMAL(18,2),
    NOTAS VARCHAR(255),
    CONSTRAINT PK_NOMINA_DEDUCCIONES PRIMARY KEY (CORRELATIVO, EMPLEADO_CODIGO, DEDUCCION_CODIGO),
    CONSTRAINT FK_NOMINA_DEDUCCIONES FOREIGN KEY (CORRELATIVO, EMPLEADO_CODIGO) REFERENCES NOMINA_DETALLE(CORRELATIVO, EMPLEADO_CODIGO) ON DELETE CASCADE
);

-- Tabla: PRESTAMOS_EMPLEADOS
CREATE TABLE PRESTAMOS_EMPLEADOS (
    CORRELATIVO INTEGER NOT NULL,
    EMPLEADO_CODIGO VARCHAR(15) NOT NULL,
    MONTO DECIMAL(18,2) NOT NULL,
    SALDO DECIMAL(18,2) NOT NULL,
    CUOTAS INTEGER NOT NULL,
    CUOTAS_PAGADAS INTEGER DEFAULT 0,
    MONTO_CUOTA DECIMAL(18,2),
    FECHA_OTORGAMIENTO DATE NOT NULL,
    FECHA_VENCIMIENTO DATE,
    INTERES DECIMAL(5,2) DEFAULT 0,
    GARANTIA VARCHAR(255),
    FIADOR_CODIGO VARCHAR(15),
    ESTATUS CHAR(1) DEFAULT 'A', -- A=Activo, C=Cancelado, M=Mora
    NOTAS VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PRESTAMOS_EMPLEADOS PRIMARY KEY (CORRELATIVO),
    CONSTRAINT FK_PRESTAMOS_EMPLEADO FOREIGN KEY (EMPLEADO_CODIGO) REFERENCES EMPLEADOS(CODIGO),
    CONSTRAINT FK_PRESTAMOS_FIADOR FOREIGN KEY (FIADOR_CODIGO) REFERENCES EMPLEADOS(CODIGO)
);

CREATE INDEX IDX_PRESTAMOS_EMPLEADO ON PRESTAMOS_EMPLEADOS(EMPLEADO_CODIGO);
CREATE INDEX IDX_PRESTAMOS_ESTADO ON PRESTAMOS_EMPLEADOS(ESTATUS);

-- Tabla: PAGOS_PRESTAMOS
CREATE TABLE PAGOS_PRESTAMOS (
    CORRELATIVO INTEGER NOT NULL,
    PRESTAMO_CORRELATIVO INTEGER NOT NULL,
    NUMERO_CUOTA INTEGER NOT NULL,
    FECHA_PAGO DATE NOT NULL,
    MONTO_PAGO DECIMAL(18,2) NOT NULL,
    MONTO_CAPITAL DECIMAL(18,2),
    MONTO_INTERES DECIMAL(18,2),
    SALDO_ANTERIOR DECIMAL(18,2),
    SALDO_ACTUAL DECIMAL(18,2),
    NOMINA_CORRELATIVO INTEGER,
    NOTAS VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PAGOS_PRESTAMOS PRIMARY KEY (CORRELATIVO),
    CONSTRAINT FK_PAGOS_PRESTAMO FOREIGN KEY (PRESTAMO_CORRELATIVO) REFERENCES PRESTAMOS_EMPLEADOS(CORRELATIVO),
    CONSTRAINT FK_PAGOS_NOMINA FOREIGN KEY (NOMINA_CORRELATIVO) REFERENCES NOMINA(CORRELATIVO)
);

CREATE INDEX IDX_PAGOS_PRESTAMO ON PAGOS_PRESTAMOS(PRESTAMO_CORRELATIVO);
CREATE INDEX IDX_PAGOS_FECHA ON PAGOS_PRESTAMOS(FECHA_PAGO);

-- Tabla: VACACIONES_EMPLEADOS
CREATE TABLE VACACIONES_EMPLEADOS (
    CORRELATIVO INTEGER NOT NULL,
    EMPLEADO_CODIGO VARCHAR(15) NOT NULL,
    PERIODO VARCHAR(7) NOT NULL, -- Año del período
    DIAS_DERECHO INTEGER NOT NULL,
    DIAS_DISFRUTADOS INTEGER DEFAULT 0,
    DIAS_PAGADOS INTEGER DEFAULT 0,
    DIAS_PENDIENTES INTEGER COMPUTED BY (DIAS_DERECHO - DIAS_DISFRUTADOS),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    MONTO_VACACIONES DECIMAL(18,2),
    BONO_VACACIONAL DECIMAL(18,2),
    TOTAL_PAGAR DECIMAL(18,2),
    ESTATUS CHAR(1) DEFAULT 'P', -- P=Pendiente, D=Disfrutando, C=Completado
    NOMINA_CORRELATIVO INTEGER,
    NOTAS VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_VACACIONES_EMPLEADOS PRIMARY KEY (CORRELATIVO),
    CONSTRAINT FK_VACACIONES_EMPLEADO FOREIGN KEY (EMPLEADO_CODIGO) REFERENCES EMPLEADOS(CODIGO),
    CONSTRAINT FK_VACACIONES_NOMINA FOREIGN KEY (NOMINA_CORRELATIVO) REFERENCES NOMINA(CORRELATIVO)
);

CREATE INDEX IDX_VACACIONES_EMPLEADO ON VACACIONES_EMPLEADOS(EMPLEADO_CODIGO);
CREATE INDEX IDX_VACACIONES_PERIODO ON VACACIONES_EMPLEADOS(PERIODO);

-- Tabla: ASISTENCIA_EMPLEADOS
CREATE TABLE ASISTENCIA_EMPLEADOS (
    CORRELATIVO INTEGER NOT NULL,
    EMPLEADO_CODIGO VARCHAR(15) NOT NULL,
    FECHA DATE NOT NULL,
    HORA_ENTRADA TIME,
    HORA_SALIDA TIME,
    HORA_ENTRADA_ALMUERZO TIME,
    HORA_SALIDA_ALMUERZO TIME,
    HORAS_TRABAJADAS DECIMAL(5,2),
    HORAS_EXTRAS DECIMAL(5,2) DEFAULT 0,
    RETARDO INTEGER DEFAULT 0, -- Minutos de retardo
    JUSTIFICACION VARCHAR(255),
    ESTATUS CHAR(1) DEFAULT 'T', -- T=Trabajó, V=Vacaciones, F=Falta, I=Incapacidad, P=Permiso
    USUARIO_CODIGO VARCHAR(15),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_ASISTENCIA_EMPLEADOS PRIMARY KEY (CORRELATIVO),
    CONSTRAINT FK_ASISTENCIA_EMPLEADO FOREIGN KEY (EMPLEADO_CODIGO) REFERENCES EMPLEADOS(CODIGO),
    CONSTRAINT UK_ASISTENCIA_EMPLEADO_FECHA UNIQUE (EMPLEADO_CODIGO, FECHA)
);

CREATE INDEX IDX_ASISTENCIA_EMPLEADO ON ASISTENCIA_EMPLEADOS(EMPLEADO_CODIGO);
CREATE INDEX IDX_ASISTENCIA_FECHA ON ASISTENCIA_EMPLEADOS(FECHA);

-- ============================================================================
-- CONTINUARÁ... (Módulo Contabilidad)
-- ============================================================================
