-- ============================================================================
-- VIOLET ERP - BASE DE DATOS FIREBIRD SQL - PARTE 4
-- MÓDULO: CONTABILIDAD
-- ============================================================================

SET NAMES UTF8;

-- ============================================================================
-- 11. MÓDULO CONTABILIDAD
-- ============================================================================

-- Tabla: PLAN_CUENTAS
CREATE TABLE PLAN_CUENTAS (
    CUENTA_CODIGO VARCHAR(22) NOT NULL,
    CUENTA_NOMBRE VARCHAR(200) NOT NULL,
    CUENTA_NOMBRE_CORTO VARCHAR(50),
    CUENTA_TIPO CHAR(1) NOT NULL, -- A=Activo, P=Pasivo, O=Patrimonio, I=Ingreso, G=Gasto, C=Costo
    CUENTA_NATURALEZA CHAR(1) NOT NULL, -- D=Deudora, A=Acreedora
    CUENTA_PADRE_CODIGO VARCHAR(22),
    NIVEL SMALLINT DEFAULT 1,
    SALDO DECIMAL(18,2) DEFAULT 0,
    SALDO_INICIAL DECIMAL(18,2) DEFAULT 0,
    MOVIMIENTOS_DEBITO DECIMAL(18,2) DEFAULT 0,
    MOVIMIENTOS_CREDITO DECIMAL(18,2) DEFAULT 0,
    ES_MOVIMIENTO CHAR(1) DEFAULT 'S', -- S=Sí, N=No (cuenta de grupo)
    ES_DETALLE CHAR(1) DEFAULT 'S', -- S=Sí, N=No (cuenta analítica)
    REQUIERE_CENTRO_COSTO CHAR(1) DEFAULT 'N',
    REQUIERE_DIVISA CHAR(1) DEFAULT 'N',
    REQUIERE_TERCERO CHAR(1) DEFAULT 'N',
    CUENTA_CONTABLE_TERCERO VARCHAR(22),
    MONEDA_CODIGO VARCHAR(15),
    ESTATUS CHAR(1) DEFAULT 'A',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PLAN_CUENTAS PRIMARY KEY (CUENTA_CODIGO),
    CONSTRAINT FK_PLAN_CUENTAS_PADRE FOREIGN KEY (CUENTA_PADRE_CODIGO) REFERENCES PLAN_CUENTAS(CUENTA_CODIGO)
);

CREATE INDEX IDX_PLAN_CUENTAS_NOMBRE ON PLAN_CUENTAS(CUENTA_NOMBRE);
CREATE INDEX IDX_PLAN_CUENTAS_TIPO ON PLAN_CUENTAS(CUENTA_TIPO);
CREATE INDEX IDX_PLAN_CUENTAS_NIVEL ON PLAN_CUENTAS(NIVEL);
CREATE INDEX IDX_PLAN_CUENTAS_ESTADO ON PLAN_CUENTAS(ESTATUS);

-- Datos iniciales de plan de cuentas (Ejemplo básico)
INSERT INTO PLAN_CUENTAS (CUENTA_CODIGO, CUENTA_NOMBRE, CUENTA_TIPO, CUENTA_NATURALEZA, NIVEL, ES_MOVIMIENTO, ES_DETALLE) VALUES
('1', 'ACTIVO', 'A', 'D', 1, 'N', 'N'),
('1.01', 'ACTIVO CIRCULANTE', 'A', 'D', 2, 'N', 'N'),
('1.01.01', 'DISPONIBLES', 'A', 'D', 3, 'N', 'N'),
('1.01.01.0001', 'CAJA PRINCIPAL', 'A', 'D', 4, 'S', 'S'),
('1.01.01.0002', 'CAJA CHICA', 'A', 'D', 4, 'S', 'S'),
('1.01.02', 'BANCOS', 'A', 'D', 3, 'N', 'N'),
('1.01.02.0001', 'BANCO DE VENEZUELA', 'A', 'D', 4, 'S', 'S'),
('1.01.02.0002', 'BANCARIBE', 'A', 'D', 4, 'S', 'S'),
('1.01.03', 'CUENTAS POR COBRAR', 'A', 'D', 3, 'N', 'N'),
('1.01.03.0001', 'CLIENTES', 'A', 'D', 4, 'S', 'S'),
('1.01.04', 'INVENTARIOS', 'A', 'D', 3, 'N', 'N'),
('1.01.04.0001', 'MERCANCÍAS', 'A', 'D', 4, 'S', 'S'),
('1.02', 'ACTIVO NO CIRCULANTE', 'A', 'D', 2, 'N', 'N'),
('1.02.01', 'PROPIEDAD, PLANTA Y EQUIPO', 'A', 'D', 3, 'N', 'N'),
('1.02.01.0001', 'EQUIPOS DE CÓMPUTO', 'A', 'D', 4, 'S', 'S'),
('1.02.01.0002', 'MUEBLES Y EN SERES', 'A', 'D', 4, 'S', 'S'),
('1.02.01.0003', 'DEPRECIACIÓN ACUMULADA', 'A', 'A', 4, 'S', 'S'),
('2', 'PASIVO', 'P', 'A', 1, 'N', 'N'),
('2.01', 'PASIVO CIRCULANTE', 'P', 'A', 2, 'N', 'N'),
('2.01.01', 'CUENTAS POR PAGAR', 'P', 'A', 3, 'N', 'N'),
('2.01.01.0001', 'PROVEEDORES', 'P', 'A', 4, 'S', 'S'),
('2.01.02', 'IMPUESTOS POR PAGAR', 'P', 'A', 3, 'N', 'N'),
('2.01.02.0001', 'IVA DÉBITO FISCAL', 'P', 'A', 4, 'S', 'S'),
('2.01.02.0002', 'IVA CRÉDITO FISCAL', 'P', 'D', 4, 'S', 'S'),
('2.01.02.0003', 'RETENCIONES IVA POR PAGAR', 'P', 'A', 4, 'S', 'S'),
('2.01.02.0004', 'ISLR POR PAGAR', 'P', 'A', 4, 'S', 'S'),
('2.01.03', 'SUELDOS POR PAGAR', 'P', 'A', 3, 'N', 'N'),
('2.01.03.0001', 'SUELDOS', 'P', 'A', 4, 'S', 'S'),
('2.01.03.0002', 'IVSS POR PAGAR', 'P', 'A', 4, 'S', 'S'),
('2.01.03.0003', 'FAOV POR PAGAR', 'P', 'A', 4, 'S', 'S'),
('2.01.03.0004', 'INCES POR PAGAR', 'P', 'A', 4, 'S', 'S'),
('2.02', 'PASIVO NO CIRCULANTE', 'P', 'A', 2, 'N', 'N'),
('2.02.01', 'PRÉSTAMOS BANCARIOS', 'P', 'A', 3, 'N', 'N'),
('3', 'PATRIMONIO', 'O', 'A', 1, 'N', 'N'),
('3.01', 'CAPITAL SOCIAL', 'O', 'A', 2, 'N', 'N'),
('3.01.01', 'CAPITAL SUSCRITO', 'O', 'A', 3, 'S', 'S'),
('3.02', 'RESULTADOS ACUMULADOS', 'O', 'A', 2, 'N', 'N'),
('3.02.01', 'UTILIDADES DEL EJERCICIO', 'O', 'A', 3, 'S', 'S'),
('3.02.02', 'UTILIDADES DE AÑOS ANTERIORES', 'O', 'A', 3, 'S', 'S'),
('4', 'INGRESOS', 'I', 'A', 1, 'N', 'N'),
('4.01', 'VENTAS', 'I', 'A', 2, 'N', 'N'),
('4.01.01', 'VENTAS NACIONALES', 'I', 'A', 3, 'S', 'S'),
('4.01.02', 'VENTAS DE SERVICIOS', 'I', 'A', 3, 'S', 'S'),
('4.01.03', 'DEVOLUCIONES EN VENTAS', 'I', 'D', 3, 'S', 'S'),
('4.02', 'OTROS INGRESOS', 'I', 'A', 2, 'N', 'N'),
('4.02.01', 'INGRESOS FINANCIEROS', 'I', 'A', 3, 'S', 'S'),
('5', 'COSTOS', 'C', 'D', 1, 'N', 'N'),
('5.01', 'COSTO DE VENTAS', 'C', 'D', 2, 'N', 'N'),
('5.01.01', 'COSTO DE MERCANCÍAS', 'C', 'D', 3, 'S', 'S'),
('5.01.02', 'COSTO DE SERVICIOS', 'C', 'D', 3, 'S', 'S'),
('6', 'GASTOS', 'G', 'D', 1, 'N', 'N'),
('6.01', 'GASTOS DE VENTA', 'G', 'D', 2, 'N', 'N'),
('6.01.01', 'SUELDOS Y SALARIOS', 'G', 'D', 3, 'S', 'S'),
('6.01.02', 'ALQUILERES', 'G', 'D', 3, 'S', 'S'),
('6.01.03', 'SERVICIOS BÁSICOS', 'G', 'D', 3, 'S', 'S'),
('6.02', 'GASTOS DE ADMINISTRACIÓN', 'G', 'D', 2, 'N', 'N'),
('6.02.01', 'HONORARIOS PROFESIONALES', 'G', 'D', 3, 'S', 'S'),
('6.02.02', 'ÚTILES DE OFICINA', 'G', 'D', 3, 'S', 'S'),
('6.03', 'GASTOS FINANCIEROS', 'G', 'D', 2, 'N', 'N'),
('6.03.01', 'INTERESES BANCARIOS', 'G', 'D', 3, 'S', 'S');

-- Tabla: CENTROS_COSTO
CREATE TABLE CENTROS_COSTO (
    CODIGO VARCHAR(15) NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(255),
    CUENTA_PADRE_CODIGO VARCHAR(15),
    PRESUPUESTO DECIMAL(18,2),
    ESTATUS CHAR(1) DEFAULT 'A',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CENTROS_COSTO PRIMARY KEY (CODIGO)
);

-- Tabla: ASIENTOS_CONTABLES (Encabezado)
CREATE TABLE ASIENTOS_CONTABLES (
    CORRELATIVO INTEGER NOT NULL,
    NUMERO_ASIENTO VARCHAR(20) NOT NULL,
    FECHA DATE NOT NULL,
    FECHA_CONTABLE DATE,
    DESCRIPCION VARCHAR(255) NOT NULL,
    REFERENCIA VARCHAR(50),
    TOTAL_DEBITO DECIMAL(18,2) NOT NULL,
    TOTAL_CREDITO DECIMAL(18,2) NOT NULL,
    CUADRADO CHAR(1) DEFAULT 'S',
    FUENTE VARCHAR(20), -- MAN=Manual, VEN=Ventas, COM=Compras, BAN=Bancos, CAJ=Caja, NOM=Nómina
    DOCUMENTO_ORIGEN VARCHAR(20),
    PERIODO_CONTABLE VARCHAR(7), -- Formato YYYY-MM
    EJERCICIO_FISCAL VARCHAR(4),
    USUARIO_CODIGO VARCHAR(15),
    REVISADO_POR VARCHAR(15),
    FECHA_REVISION DATE,
    APROBADO_POR VARCHAR(15),
    FECHA_APROBACION DATE,
    ESTATUS CHAR(1) DEFAULT 'R', -- R=Registrado, A=Anulado
    ANULADO_POR VARCHAR(15),
    FECHA_ANULACION DATE,
    MOTIVO_ANULACION VARCHAR(255),
    NOTAS VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_ASIENTOS_CONTABLES PRIMARY KEY (CORRELATIVO),
    CONSTRAINT UK_ASIENTOS_NUMERO UNIQUE (NUMERO_ASIENTO),
    CONSTRAINT FK_ASIENTOS_USUARIO FOREIGN KEY (USUARIO_CODIGO) REFERENCES USUARIOS(CODIGO)
);

CREATE INDEX IDX_ASIENTOS_FECHA ON ASIENTOS_CONTABLES(FECHA);
CREATE INDEX IDX_ASIENTOS_NUMERO ON ASIENTOS_CONTABLES(NUMERO_ASIENTO);
CREATE INDEX IDX_ASIENTOS_PERIODO ON ASIENTOS_CONTABLES(PERIODO_CONTABLE);
CREATE INDEX IDX_ASIENTOS_ESTADO ON ASIENTOS_CONTABLES(ESTATUS);
CREATE INDEX IDX_ASIENTOS_FUENTE ON ASIENTOS_CONTABLES(FUENTE);

-- Tabla: ASIENTOS_DETALLE
CREATE TABLE ASIENTOS_DETALLE (
    CORRELATIVO INTEGER NOT NULL,
    LINEA INTEGER NOT NULL,
    CUENTA_CODIGO VARCHAR(22) NOT NULL,
    DESCRIPCION VARCHAR(255),
    DEBITO DECIMAL(18,2) DEFAULT 0,
    CREDITO DECIMAL(18,2) DEFAULT 0,
    CENTRO_COSTO_CODIGO VARCHAR(15),
    TERCERO_CODIGO VARCHAR(15), -- Cliente, Proveedor, Empleado
    TIPO_TERCERO CHAR(1), -- C=Cliente, P=Proveedor, E=Empleado
    MONEDA_CODIGO VARCHAR(15),
    TASA_CAMBIO DECIMAL(18,6) DEFAULT 1,
    MONTO_DIVISA DECIMAL(18,2),
    BASE_IMPONIBLE DECIMAL(18,2),
    PORC_IMPUESTO DECIMAL(5,2),
    MONTO_IMPUESTO DECIMAL(18,2),
    DOCUMENTO_REFERENCIA VARCHAR(20),
    NOTAS VARCHAR(255),
    CONSTRAINT PK_ASIENTOS_DETALLE PRIMARY KEY (CORRELATIVO, LINEA),
    CONSTRAINT FK_ASIENTOS_DETALLE_ASIENTO FOREIGN KEY (CORRELATIVO) REFERENCES ASIENTOS_CONTABLES(CORRELATIVO) ON DELETE CASCADE,
    CONSTRAINT FK_ASIENTOS_DETALLE_CUENTA FOREIGN KEY (CUENTA_CODIGO) REFERENCES PLAN_CUENTAS(CUENTA_CODIGO),
    CONSTRAINT FK_ASIENTOS_DETALLE_CENTRO_COSTO FOREIGN KEY (CENTRO_COSTO_CODIGO) REFERENCES CENTROS_COSTO(CODIGO)
);

CREATE INDEX IDX_ASIENTOS_DETALLE_CUENTA ON ASIENTOS_DETALLE(CUENTA_CODIGO);
CREATE INDEX IDX_ASIENTOS_DETALLE_CENTRO_COSTO ON ASIENTOS_DETALLE(CENTRO_COSTO_CODIGO);

-- Tabla: LIBRO_DIARIO
CREATE VIEW LIBRO_DIARIO AS
SELECT 
    A.NUMERO_ASIENTO,
    A.FECHA,
    A.DESCRIPCION,
    A.FUENTE,
    A.DOCUMENTO_ORIGEN,
    D.LINEA,
    D.CUENTA_CODIGO,
    C.CUENTA_NOMBRE,
    D.DESCRIPCION AS DESCRIPCION_DETALLE,
    D.DEBITO,
    D.CREDITO,
    D.CENTRO_COSTO_CODIGO,
    D.TERCERO_CODIGO,
    A.PERIODO_CONTABLE
FROM ASIENTOS_CONTABLES A
INNER JOIN ASIENTOS_DETALLE D ON A.CORRELATIVO = D.CORRELATIVO
INNER JOIN PLAN_CUENTAS C ON D.CUENTA_CODIGO = C.CUENTA_CODIGO
WHERE A.ESTATUS = 'R'
ORDER BY A.FECHA, A.NUMERO_ASIENTO, D.LINEA;

-- Tabla: LIBRO_MAYOR
CREATE VIEW LIBRO_MAYOR AS
SELECT 
    D.CUENTA_CODIGO,
    C.CUENTA_NOMBRE,
    C.CUENTA_TIPO,
    A.PERIODO_CONTABLE,
    SUM(D.DEBITO) AS TOTAL_DEBITOS,
    SUM(D.CREDITO) AS TOTAL_CREDITOS,
    SUM(D.DEBITO) - SUM(D.CREDITO) AS SALDO
FROM ASIENTOS_DETALLE D
INNER JOIN ASIENTOS_CONTABLES A ON D.CORRELATIVO = A.CORRELATIVO
INNER JOIN PLAN_CUENTAS C ON D.CUENTA_CODIGO = C.CUENTA_CODIGO
WHERE A.ESTATUS = 'R'
GROUP BY D.CUENTA_CODIGO, C.CUENTA_NOMBRE, C.CUENTA_TIPO, A.PERIODO_CONTABLE
ORDER BY D.CUENTA_CODIGO, A.PERIODO_CONTABLE;

-- Tabla: BALANCE_COMPROBACION
CREATE VIEW BALANCE_COMPROBACION AS
SELECT 
    D.CUENTA_CODIGO,
    C.CUENTA_NOMBRE,
    C.CUENTA_TIPO,
    C.CUENTA_NATURALEZA,
    C.SALDO_INICIAL,
    SUM(D.DEBITO) AS MOVIMIENTOS_DEBITO,
    SUM(D.CREDITO) AS MOVIMIENTOS_CREDITO,
    CASE C.CUENTA_NATURALEZA
        WHEN 'D' THEN C.SALDO_INICIAL + SUM(D.DEBITO) - SUM(D.CREDITO)
        WHEN 'A' THEN C.SALDO_INICIAL - SUM(D.DEBITO) + SUM(D.CREDITO)
    END AS SALDO_FINAL
FROM ASIENTOS_DETALLE D
INNER JOIN ASIENTOS_CONTABLES A ON D.CORRELATIVO = A.CORRELATIVO
INNER JOIN PLAN_CUENTAS C ON D.CUENTA_CODIGO = C.CUENTA_CODIGO
WHERE A.ESTATUS = 'R'
GROUP BY D.CUENTA_CODIGO, C.CUENTA_NOMBRE, C.CUENTA_TIPO, C.CUENTA_NATURALEZA, C.SALDO_INICIAL
ORDER BY D.CUENTA_CODIGO;

-- Tabla: LIBRO_VENTAS (Para fines fiscales)
CREATE TABLE LIBRO_VENTAS (
    CORRELATIVO INTEGER NOT NULL,
    PERIODO VARCHAR(7) NOT NULL, -- Formato YYYY-MM
    FECHA_COMPROBANTE DATE NOT NULL,
    NUMERO_COMPROBANTE VARCHAR(20),
    RIF_CLIENTE VARCHAR(20) NOT NULL,
    NOMBRE_CLIENTE VARCHAR(160) NOT NULL,
    NUMERO_FACTURA VARCHAR(20) NOT NULL,
    NUMERO_CONTROL VARCHAR(20),
    TIPO_OPERACION CHAR(1), -- R=Registro, A=Anulación
    TOTAL_VENTA DECIMAL(18,2) NOT NULL,
    BASE_IMPONIBLE DECIMAL(18,2),
    PORC_ALICUOTA DECIMAL(5,2),
    IMPUESTO_IVA DECIMAL(18,2),
    IMPUESTO_IVA_RETENIDO DECIMAL(18,2),
    VENTA_EXENTA DECIMAL(18,2),
    VENTA_CERO DECIMAL(18,2),
    DESCUENTOS DECIMAL(18,2),
    IGTF DECIMAL(18,2) DEFAULT 0,
    VENTA_CORRELATIVO INTEGER,
    ASIENTO_CORRELATIVO INTEGER,
    USUARIO_CODIGO VARCHAR(15),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_LIBRO_VENTAS PRIMARY KEY (CORRELATIVO),
    CONSTRAINT FK_LIBRO_VENTAS_VENTA FOREIGN KEY (VENTA_CORRELATIVO) REFERENCES VENTAS(CORRELATIVO),
    CONSTRAINT FK_LIBRO_VENTAS_ASIENTO FOREIGN KEY (ASIENTO_CORRELATIVO) REFERENCES ASIENTOS_CONTABLES(CORRELATIVO)
);

CREATE INDEX IDX_LIBRO_VENTAS_PERIODO ON LIBRO_VENTAS(PERIODO);
CREATE INDEX IDX_LIBRO_VENTAS_FECHA ON LIBRO_VENTAS(FECHA_COMPROBANTE);
CREATE INDEX IDX_LIBRO_VENTAS_CLIENTE ON LIBRO_VENTAS(RIF_CLIENTE);

-- Tabla: LIBRO_COMPRAS (Para fines fiscales)
CREATE TABLE LIBRO_COMPRAS (
    CORRELATIVO INTEGER NOT NULL,
    PERIODO VARCHAR(7) NOT NULL, -- Formato YYYY-MM
    FECHA_COMPROBANTE DATE NOT NULL,
    NUMERO_COMPROBANTE VARCHAR(20),
    RIF_PROVEEDOR VARCHAR(20) NOT NULL,
    NOMBRE_PROVEEDOR VARCHAR(160) NOT NULL,
    NUMERO_FACTURA VARCHAR(20) NOT NULL,
    NUMERO_CONTROL VARCHAR(20),
    TIPO_OPERACION CHAR(1), -- R=Registro, A=Anulación
    TOTAL_COMPRA DECIMAL(18,2) NOT NULL,
    BASE_IMPONIBLE DECIMAL(18,2),
    PORC_ALICUOTA DECIMAL(5,2),
    IMPUESTO_IVA DECIMAL(18,2),
    IMPUESTO_IVA_RETENIDO DECIMAL(18,2),
    COMPRA_EXENTA DECIMAL(18,2),
    DESCUENTOS DECIMAL(18,2),
    IGTF DECIMAL(18,2) DEFAULT 0,
    ISLR_RETENIDO DECIMAL(18,2) DEFAULT 0,
    COMPRA_CORRELATIVO INTEGER,
    ASIENTO_CORRELATIVO INTEGER,
    USUARIO_CODIGO VARCHAR(15),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_LIBRO_COMPRAS PRIMARY KEY (CORRELATIVO),
    CONSTRAINT FK_LIBRO_COMPRAS_COMPRA FOREIGN KEY (COMPRA_CORRELATIVO) REFERENCES COMPRAS(CORRELATIVO),
    CONSTRAINT FK_LIBRO_COMPRAS_ASIENTO FOREIGN KEY (ASIENTO_CORRELATIVO) REFERENCES ASIENTOS_CONTABLES(CORRELATIVO)
);

CREATE INDEX IDX_LIBRO_COMPRAS_PERIODO ON LIBRO_COMPRAS(PERIODO);
CREATE INDEX IDX_LIBRO_COMPRAS_FECHA ON LIBRO_COMPRAS(FECHA_COMPROBANTE);
CREATE INDEX IDX_LIBRO_COMPRAS_PROVEEDOR ON LIBRO_COMPRAS(RIF_PROVEEDOR);

-- Tabla: COMPROBANTES_FISCALES
CREATE TABLE COMPROBANTES_FISCALES (
    CORRELATIVO INTEGER NOT NULL,
    TIPO_COMPROBANTE VARCHAR(10) NOT NULL, -- RIVA=Retención IVA, RISLR=Retención ISLR
    NUMERO_COMPROBANTE VARCHAR(20) NOT NULL,
    FECHA_EMISION DATE NOT NULL,
    PERIODO_FISCAL VARCHAR(7), -- Formato YYYY-MM
    TERCERO_CODIGO VARCHAR(15),
    TIPO_TERCERO CHAR(1), -- C=Cliente, P=Proveedor
    TOTAL_RETENCION DECIMAL(18,2),
    DOCUMENTO_AFECTADO VARCHAR(20),
    ASIENTO_CORRELATIVO INTEGER,
    IMPRESO CHAR(1) DEFAULT 'F',
    FECHA_IMPRESION TIMESTAMP,
    ENVIADO CHAR(1) DEFAULT 'F',
    FECHA_ENVIO TIMESTAMP,
    EMAIL_ENVIO VARCHAR(60),
    USUARIO_CODIGO VARCHAR(15),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_COMPROBANTES_FISCALES PRIMARY KEY (CORRELATIVO),
    CONSTRAINT UK_COMPROBANTE_NUMERO UNIQUE (TIPO_COMPROBANTE, NUMERO_COMPROBANTE)
);

-- ============================================================================
-- 12. TABLAS DE AUDITORÍA Y CONTROL
-- ============================================================================

-- Tabla: AUDITORIA
CREATE TABLE AUDITORIA (
    CORRELATIVO INTEGER NOT NULL,
    TABLA VARCHAR(50) NOT NULL,
    REGISTRO_ID VARCHAR(50) NOT NULL,
    ACCION CHAR(1) NOT NULL, -- I=Insert, U=Update, D=Delete
    DATOS_ANTERIORES BLOB SUB_TYPE TEXT,
    DATOS_NUEVOS BLOB SUB_TYPE TEXT,
    USUARIO_CODIGO VARCHAR(15),
    ESTACION VARCHAR(30),
    IP_ADDRESS VARCHAR(45),
    FECHA_HORA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_AUDITORIA PRIMARY KEY (CORRELATIVO)
);

CREATE INDEX IDX_AUDITORIA_TABLA ON AUDITORIA(TABLA);
CREATE INDEX IDX_AUDITORIA_FECHA ON AUDITORIA(FECHA_HORA);
CREATE INDEX IDX_AUDITORIA_USUARIO ON AUDITORIA(USUARIO_CODIGO);
CREATE INDEX IDX_AUDITORIA_ACCION ON AUDITORIA(ACCION);

-- Tabla: SECUENCIAS
CREATE TABLE SECUENCIAS (
    NOMBRE VARCHAR(50) NOT NULL,
    ULTIMO_VALOR INTEGER DEFAULT 0,
    INCREMENTO INTEGER DEFAULT 1,
    MINIMO INTEGER DEFAULT 1,
    MAXIMO INTEGER DEFAULT 2147483647,
    CICLICA CHAR(1) DEFAULT 'N',
    DESCRIPCION VARCHAR(255),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_SECUENCIAS PRIMARY KEY (NOMBRE)
);

-- Datos iniciales de secuencias
INSERT INTO SECUENCIAS (NOMBRE, ULTIMO_VALOR, INCREMENTO, DESCRIPCION) VALUES
('CLIENTES', 0, 1, 'Secuencia para clientes'),
('PROVEEDORES', 0, 1, 'Secuencia para proveedores'),
('PRODUCTOS', 0, 1, 'Secuencia para productos'),
('VENTAS', 0, 1, 'Secuencia para ventas'),
('COMPRAS', 0, 1, 'Secuencia para compras'),
('CXC', 0, 1, 'Secuencia para cuentas por cobrar'),
('CXP', 0, 1, 'Secuencia para cuentas por pagar'),
('ASIENTOS', 0, 1, 'Secuencia para asientos contables'),
('NOMINA', 0, 1, 'Secuencia para nómina'),
('EMPLEADOS', 0, 1, 'Secuencia para empleados');

-- ============================================================================
-- FIN DEL ESQUEMA DE BASE DE DATOS
-- ============================================================================
