-- ============================================================================
-- VIOLET ERP - STORED PROCEDURES FIREBIRD SQL
-- Basado en ValeryProfesional
-- ============================================================================

SET NAMES UTF8;

-- ============================================================================
-- 1. PROCEDIMIENTOS DE CÁLCULO FISCAL
-- ============================================================================

-- Procedimiento: CALCULAR_RETENCION_IVA
-- Calcula la retención de IVA (75% o 100% según tipo de contribuyente)
CREATE OR ALTER PROCEDURE CALCULAR_RETENCION_IVA (
    MONTO_IVA DECIMAL(18,2),
    CONTRIBUYENTE_ESPECIAL CHAR(1)
)
RETURNS (
    PORCENTAJE DECIMAL(5,2),
    MONTO_RETENIDO DECIMAL(18,2)
)
AS
BEGIN
    -- Si es contribuyente especial, retiene 100%
    -- Si es ordinario, retiene 75%
    IF (CONTRIBUYENTE_ESPECIAL = 'T') THEN
        PORCENTAJE = 100;
    ELSE
        PORCENTAJE = 75;
    
    MONTO_RETENIDO = (MONTO_IVA * PORCENTAJE) / 100;
    
    SUSPEND;
END;

-- Procedimiento: CALCULAR_IGTF
-- Calcula el IGTF (3% sobre pagos en divisas)
CREATE OR ALTER PROCEDURE CALCULAR_IGTF (
    TOTAL_OPERACION DECIMAL(18,2),
    ES_PAGO_DIVISAS CHAR(1)
)
RETURNS (
    TASA DECIMAL(5,2),
    MONTO_IGTF DECIMAL(18,2),
    TOTAL_CON_IGTF DECIMAL(18,2)
)
AS
BEGIN
    IF (ES_PAGO_DIVISAS = 'T') THEN
        TASA = 3;
        MONTO_IGTF = (TOTAL_OPERACION * TASA) / 100;
        TOTAL_CON_IGTF = TOTAL_OPERACION + MONTO_IGTF;
    ELSE
        TASA = 0;
        MONTO_IGTF = 0;
        TOTAL_CON_IGTF = TOTAL_OPERACION;
    
    SUSPEND;
END;

-- Procedimiento: CALCULAR_IVA
-- Calcula el IVA de una base imponible
CREATE OR ALTER PROCEDURE CALCULAR_IVA (
    BASE_IMPONIBLE DECIMAL(18,2),
    ALICUOTA DECIMAL(5,2)
)
RETURNS (
    MONTO_IVA DECIMAL(18,2),
    TOTAL_OPERACION DECIMAL(18,2)
)
AS
BEGIN
    MONTO_IVA = (BASE_IMPONIBLE * ALICUOTA) / 100;
    TOTAL_OPERACION = BASE_IMPONIBLE + MONTO_IVA;
    
    SUSPEND;
END;

-- Procedimiento: CALCULAR_RETENCION_ISLR
-- Calcula la retención de ISLR según el concepto
CREATE OR ALTER PROCEDURE CALCULAR_RETENCION_ISLR (
    BASE_IMPONIBLE DECIMAL(18,2),
    CONCEPTO VARCHAR(50)
)
RETURNS (
    PORCENTAJE DECIMAL(5,2),
    MONTO_RETENIDO DECIMAL(18,2)
)
AS
BEGIN
    -- Porcentajes comunes de retención ISLR en Venezuela
    IF (CONCEPTO CONTAINING 'HONORARIOS') THEN
        PORCENTAJE = 3;
    ELSE IF (CONCEPTO CONTAINING 'COMISION') THEN
        PORCENTAJE = 3;
    ELSE IF (CONCEPTO CONTAINING 'TRANSPORTE') THEN
        PORCENTAJE = 2;
    ELSE IF (CONCEPTO CONTAINING 'PUBLICIDAD') THEN
        PORCENTAJE = 2;
    ELSE IF (CONCEPTO CONTAINING 'SERVICIOS') THEN
        PORCENTAJE = 3;
    ELSE IF (CONCEPTO CONTAINING 'ALQUILER') THEN
        PORCENTAJE = 3;
    ELSE IF (CONCEPTO CONTAINING 'INTERES') THEN
        PORCENTAJE = 5;
    ELSE
        PORCENTAJE = 3; -- Porcentaje por defecto
    
    MONTO_RETENIDO = (BASE_IMPONIBLE * PORCENTAJE) / 100;
    
    SUSPEND;
END;

-- Procedimiento: CALCULAR_RETENCION_MUNICIPAL
-- Calcula la retención municipal según el municipio
CREATE OR ALTER PROCEDURE CALCULAR_RETENCION_MUNICIPAL (
    BASE_IMPONIBLE DECIMAL(18,2),
    MUNICIPIO VARCHAR(50)
)
RETURNS (
    PORCENTAJE DECIMAL(5,2),
    MONTO_RETENIDO DECIMAL(18,2)
)
AS
BEGIN
    -- Porcentajes comunes por municipio en Venezuela
    MUNICIPIO = UPPER(MUNICIPIO);
    
    IF (MUNICIPIO CONTAINING 'CARACAS') THEN
        PORCENTAJE = 2;
    ELSE IF (MUNICIPIO CONTAINING 'MARACAIBO') THEN
        PORCENTAJE = 2;
    ELSE IF (MUNICIPIO CONTAINING 'VALENCIA') THEN
        PORCENTAJE = 2;
    ELSE IF (MUNICIPIO CONTAINING 'BARQUISIMETO') THEN
        PORCENTAJE = 2;
    ELSE IF (MUNICIPIO CONTAINING 'GUAYANA') THEN
        PORCENTAJE = 1.5;
    ELSE
        PORCENTAJE = 1; -- Porcentaje general por defecto
    
    MONTO_RETENIDO = (BASE_IMPONIBLE * PORCENTAJE) / 100;
    
    SUSPEND;
END;

-- ============================================================================
-- 2. PROCEDIMIENTOS DE SECUENCIAS
-- ============================================================================

-- Procedimiento: OBTENER_SECUENCIA
-- Obtiene el siguiente número de una secuencia
CREATE OR ALTER PROCEDURE OBTENER_SECUENCIA (
    NOMBRE_SECUENCIA VARCHAR(50)
)
RETURNS (
    PROXIMO_NUMERO INTEGER
)
AS
DECLARE VARIABLE ULTIMO INTEGER;
DECLARE VARIABLE INCREMENTO INTEGER;
BEGIN
    SELECT ULTIMO_VALOR, INCREMENTO
    FROM SECUENCIAS
    WHERE NOMBRE = :NOMBRE_SECUENCIA
    INTO :ULTIMO, :INCREMENTO;
    
    IF (ULTIMO IS NULL) THEN
        ULTIMO = 0;
    
    IF (INCREMENTO IS NULL) THEN
        INCREMENTO = 1;
    
    PROXIMO_NUMERO = ULTIMO + INCREMENTO;
    
    -- Actualizar la secuencia
    UPDATE SECUENCIAS
    SET ULTIMO_VALOR = :PROXIMO_NUMERO,
        UPDATED_AT = CURRENT_TIMESTAMP
    WHERE NOMBRE = :NOMBRE_SECUENCIA;
    
    SUSPEND;
END;

-- Procedimiento: REINICIAR_SECUENCIA
-- Reinicia una secuencia a un valor específico
CREATE OR ALTER PROCEDURE REINICIAR_SECUENCIA (
    NOMBRE_SECUENCIA VARCHAR(50),
    NUEVO_VALOR INTEGER
)
AS
BEGIN
    UPDATE SECUENCIAS
    SET ULTIMO_VALOR = :NUEVO_VALOR,
        UPDATED_AT = CURRENT_TIMESTAMP
    WHERE NOMBRE = :NOMBRE_SECUENCIA;
END;

-- ============================================================================
-- 3. PROCEDIMIENTOS DE DOCUMENTOS
-- ============================================================================

-- Procedimiento: GENERAR_NUMERO_DOCUMENTO
-- Genera un número de documento con formato
CREATE OR ALTER PROCEDURE GENERAR_NUMERO_DOCUMENTO (
    TIPO_DOCUMENTO VARCHAR(10),
    SUCURSAL_CODIGO VARCHAR(15)
)
RETURNS (
    NUMERO_DOCUMENTO VARCHAR(20)
)
AS
DECLARE VARIABLE ULTIMO_NUMERO INTEGER;
DECLARE VARIABLE PREFIJO VARCHAR(5);
DECLARE VARIABLE LONGITUD INTEGER;
DECLARE VARIABLE NUMERO_CEROS VARCHAR(20);
BEGIN
    -- Obtener información de la numeración
    SELECT ULTIMO_NUMERO, PREFIJO, LONGITUD
    FROM NUMERACION_DOCUMENTOS
    WHERE TIPO_DOCUMENTO = :TIPO_DOCUMENTO
      AND (SUCURSAL_CODIGO = :SUCURSAL_CODIGO OR SUCURSAL_CODIGO IS NULL)
    INTO :ULTIMO_NUMERO, :PREFIJO, :LONGITUD;
    
    IF (ULTIMO_NUMERO IS NULL) THEN
        ULTIMO_NUMERO = 0;
    
    IF (PREFIJO IS NULL) THEN
        PREFIJO = '';
    
    IF (LONGITUD IS NULL) THEN
        LONGITUD = 8;
    
    -- Incrementar el número
    ULTIMO_NUMERO = ULTIMO_NUMERO + 1;
    
    -- Actualizar la numeración
    UPDATE NUMERACION_DOCUMENTOS
    SET ULTIMO_NUMERO = :ULTIMO_NUMERO,
        UPDATED_AT = CURRENT_TIMESTAMP
    WHERE TIPO_DOCUMENTO = :TIPO_DOCUMENTO
      AND (SUCURSAL_CODIGO = :SUCURSAL_CODIGO OR SUCURSAL_CODIGO IS NULL);
    
    -- Generar el número con ceros a la izquierda
    NUMERO_CEROS = '00000000000000000000';
    NUMERO_DOCUMENTO = PREFIJO || SUBSTRING(NUMERO_CEROS FROM 1 FOR (LONGITUD - CHAR_LENGTH(ULTIMO_NUMERO))) || ULTIMO_NUMERO;
    
    SUSPEND;
END;

-- ============================================================================
-- 4. PROCEDIMIENTOS DE INVENTARIO
-- ============================================================================

-- Procedimiento: ACTUALIZAR_EXISTENCIA
-- Actualiza la existencia de un producto después de un movimiento
CREATE OR ALTER PROCEDURE ACTUALIZAR_EXISTENCIA (
    PRODUCTO_CODIGO VARCHAR(15),
    DEPOSITO_CODIGO VARCHAR(15),
    CANTIDAD DECIMAL(18,4),
    TIPO_MOVIMIENTO CHAR(3), -- ENT=Entrada, SAL=Salida
    COSTO DECIMAL(18,4)
)
AS
DECLARE VARIABLE EXISTENCIA_ACTUAL DECIMAL(18,4);
DECLARE VARIABLE COSTO_PROMEDIO DECIMAL(18,4);
DECLARE VARIABLE NUEVO_COSTO_PROMEDIO DECIMAL(18,4);
DECLARE VARIABLE TOTAL_COSTO DECIMAL(18,2);
BEGIN
    -- Verificar si existe el registro de existencia
    SELECT COALESCE(CANTIDAD, 0), COALESCE(COSTO_PROMEDIO, 0)
    FROM EXISTENCIAS
    WHERE PRODUCTO_CODIGO = :PRODUCTO_CODIGO
      AND DEPOSITO_CODIGO = :DEPOSITO_CODIGO
    INTO :EXISTENCIA_ACTUAL, :COSTO_PROMEDIO;
    
    IF (EXISTENCIA_ACTUAL IS NULL) THEN
        EXISTENCIA_ACTUAL = 0;
    
    IF (COSTO_PROMEDIO IS NULL) THEN
        COSTO_PROMEDIO = 0;
    
    -- Procesar según el tipo de movimiento
    IF (TIPO_MOVIMIENTO = 'ENT') THEN
        -- Entrada: recalcular costo promedio
        TOTAL_COSTO = (EXISTENCIA_ACTUAL * COSTO_PROMEDIO) + (CANTIDAD * COSTO);
        NUEVO_COSTO_PROMEDIO = TOTAL_COSTO / (EXISTENCIA_ACTUAL + CANTIDAD);
        
        -- Actualizar o insertar existencia
        UPDATE OR INSERT INTO EXISTENCIAS (
            PRODUCTO_CODIGO,
            DEPOSITO_CODIGO,
            CANTIDAD,
            COSTO_PROMEDIO,
            ULTIMA_COMPRA
        ) VALUES (
            :PRODUCTO_CODIGO,
            :DEPOSITO_CODIGO,
            EXISTENCIA_ACTUAL + CANTIDAD,
            :NUEVO_COSTO_PROMEDIO,
            CURRENT_DATE
        ) MATCHING (PRODUCTO_CODIGO, DEPOSITO_CODIGO);
        
    ELSE IF (TIPO_MOVIMIENTO = 'SAL') THEN
        -- Salida: disminuir existencia al costo promedio actual
        UPDATE OR INSERT INTO EXISTENCIAS (
            PRODUCTO_CODIGO,
            DEPOSITO_CODIGO,
            CANTIDAD,
            COSTO_PROMEDIO,
            ULTIMA_VENTA
        ) VALUES (
            :PRODUCTO_CODIGO,
            :DEPOSITO_CODIGO,
            EXISTENCIA_ACTUAL - CANTIDAD,
            :COSTO_PROMEDIO,
            CURRENT_DATE
        ) MATCHING (PRODUCTO_CODIGO, DEPOSITO_CODIGO);
END;

-- Procedimiento: VERIFICAR_STOCK
-- Verifica si hay suficiente stock para una venta
CREATE OR ALTER PROCEDURE VERIFICAR_STOCK (
    PRODUCTO_CODIGO VARCHAR(15),
    DEPOSITO_CODIGO VARCHAR(15),
    CANTIDAD_SOLICITADA DECIMAL(18,4)
)
RETURNS (
    STOCK_DISPONIBLE DECIMAL(18,4),
    SUFICIENTE CHAR(1)
)
AS
BEGIN
    SELECT COALESCE(CANTIDAD, 0)
    FROM EXISTENCIAS
    WHERE PRODUCTO_CODIGO = :PRODUCTO_CODIGO
      AND DEPOSITO_CODIGO = :DEPOSITO_CODIGO
    INTO :STOCK_DISPONIBLE;
    
    IF (STOCK_DISPONIBLE IS NULL) THEN
        STOCK_DISPONIBLE = 0;
    
    IF (STOCK_DISPONIBLE >= CANTIDAD_SOLICITADA) THEN
        SUFICIENTE = 'S';
    ELSE
        SUFICIENTE = 'N';
    
    SUSPEND;
END;

-- ============================================================================
-- 5. PROCEDIMIENTOS DE CLIENTES Y PROVEEDORES
-- ============================================================================

-- Procedimiento: ACTUALIZAR_SALDO_CLIENTE
-- Actualiza el saldo total de un cliente
CREATE OR ALTER PROCEDURE ACTUALIZAR_SALDO_CLIENTE (
    CLIENTE_CODIGO VARCHAR(15)
)
AS
DECLARE VARIABLE TOTAL_DEBITOS DECIMAL(18,2);
DECLARE VARIABLE TOTAL_CREDITOS DECIMAL(18,2);
DECLARE VARIABLE TOTAL_ANTICIPOS DECIMAL(18,2);
BEGIN
    -- Sumar todos los débitos (ventas, notas de débito)
    SELECT COALESCE(SUM(TOTAL_OPERACION), 0)
    FROM CXC
    WHERE CLIENTE_CODIGO = :CLIENTE_CODIGO
      AND ESTATUS <> 'C'
    INTO :TOTAL_DEBITOS;
    
    -- Sumar todos los créditos (pagos, notas de crédito)
    SELECT COALESCE(SUM(MONTO), 0)
    FROM PAGOS_CXC
    WHERE CXC_CORRELATIVO IN (
        SELECT CORRELATIVO FROM CXC WHERE CLIENTE_CODIGO = :CLIENTE_CODIGO
    )
    INTO :TOTAL_CREDITOS;
    
    -- Sumar anticipos
    SELECT COALESCE(SUM(ANTICIPO), 0)
    FROM VENTAS
    WHERE CLIENTE_CODIGO = :CLIENTE_CODIGO
      AND ESTATUS = 'R'
    INTO :TOTAL_ANTICIPOS;
    
    -- Actualizar el cliente
    UPDATE CLIENTES
    SET TOTAL_DEBITOS = :TOTAL_DEBITOS,
        TOTAL_CREDITOS = :TOTAL_CREDITOS + :TOTAL_ANTICIPOS,
        TOTAL_SALDO = :TOTAL_DEBITOS - :TOTAL_CREDITOS - :TOTAL_ANTICIPOS,
        UPDATED_AT = CURRENT_TIMESTAMP
    WHERE CODIGO = :CLIENTE_CODIGO;
END;

-- Procedimiento: ACTUALIZAR_SALDO_PROVEEDOR
-- Actualiza el saldo total de un proveedor
CREATE OR ALTER PROCEDURE ACTUALIZAR_SALDO_PROVEEDOR (
    PROVEEDOR_CODIGO VARCHAR(15)
)
AS
DECLARE VARIABLE TOTAL_DEBITOS DECIMAL(18,2);
DECLARE VARIABLE TOTAL_CREDITOS DECIMAL(18,2);
BEGIN
    -- Sumar todos los débitos (compras)
    SELECT COALESCE(SUM(TOTAL_OPERACION), 0)
    FROM CXP
    WHERE PROVEEDOR_CODIGO = :PROVEEDOR_CODIGO
      AND ESTATUS <> 'C'
    INTO :TOTAL_DEBITOS;
    
    -- Sumar todos los créditos (pagos)
    SELECT COALESCE(SUM(MONTO), 0)
    FROM PAGOS_CXP
    WHERE CXP_CORRELATIVO IN (
        SELECT CORRELATIVO FROM CXP WHERE PROVEEDOR_CODIGO = :PROVEEDOR_CODIGO
    )
    INTO :TOTAL_CREDITOS;
    
    -- Actualizar el proveedor
    UPDATE PROVEEDORES
    SET TOTAL_DEBITOS = :TOTAL_DEBITOS,
        TOTAL_CREDITOS = :TOTAL_CREDITOS,
        TOTAL_SALDO = :TOTAL_DEBITOS - :TOTAL_CREDITOS,
        UPDATED_AT = CURRENT_TIMESTAMP
    WHERE CODIGO = :PROVEEDOR_CODIGO;
END;

-- ============================================================================
-- 6. PROCEDIMIENTOS DE CONCILIACIÓN
-- ============================================================================

-- Procedimiento: CONCILIAR_MOVIMIENTO_BANCO
-- Marca un movimiento bancario como conciliado
CREATE OR ALTER PROCEDURE CONCILIAR_MOVIMIENTO_BANCO (
    MOVIMIENTO_CORRELATIVO INTEGER,
    PERIODO_CONCILIACION VARCHAR(7)
)
AS
BEGIN
    UPDATE MOVIMIENTOS_BANCOS
    SET CONCILIADO = 'T',
        FECHA_CONCILIACION = CURRENT_DATE,
        PERIODO_CONCILIACION = :PERIODO_CONCILIACION
    WHERE CORRELATIVO = :MOVIMIENTO_CORRELATIVO;
END;

-- Procedimiento: DESCONCILIAR_MOVIMIENTO_BANCO
-- Marca un movimiento bancario como no conciliado
CREATE OR ALTER PROCEDURE DESCONCILIAR_MOVIMIENTO_BANCO (
    MOVIMIENTO_CORRELATIVO INTEGER
)
AS
BEGIN
    UPDATE MOVIMIENTOS_BANCOS
    SET CONCILIADO = 'F',
        FECHA_CONCILIACION = NULL,
        PERIODO_CONCILIACION = NULL
    WHERE CORRELATIVO = :MOVIMIENTO_CORRELATIVO;
END;

-- ============================================================================
-- 7. PROCEDIMIENTOS DE REPORTES
-- ============================================================================

-- Procedimiento: REPORTE_LIBRO_VENTAS
-- Genera el libro de ventas para un período fiscal
CREATE OR ALTER PROCEDURE REPORTE_LIBRO_VENTAS (
    PERIODO_INICIO VARCHAR(7),
    PERIODO_FIN VARCHAR(7)
)
RETURNS (
    FECHA_COMPROBANTE DATE,
    NUMERO_COMPROBANTE VARCHAR(20),
    RIF_CLIENTE VARCHAR(20),
    NOMBRE_CLIENTE VARCHAR(160),
    NUMERO_FACTURA VARCHAR(20),
    NUMERO_CONTROL VARCHAR(20),
    TOTAL_VENTA DECIMAL(18,2),
    BASE_IMPONIBLE DECIMAL(18,2),
    IMPUESTO_IVA DECIMAL(18,2),
    IMPUESTO_IVA_RETENIDO DECIMAL(18,2),
    VENTA_EXENTA DECIMAL(18,2),
    IGTF DECIMAL(18,2)
)
AS
BEGIN
    FOR SELECT
        V.FECHA_EMISION,
        V.DOCUMENTO,
        C.RIF,
        C.NOMBRE,
        V.DOCUMENTO,
        V.NUMERO_CONTROL,
        V.TOTAL_OPERACION,
        V.TOTAL_BASE_IMPONIBLE,
        V.TOTAL_IMPUESTO_FISCAL,
        V.TOTAL_RETENCION_IVA,
        V.TOTAL_EXENTO,
        COALESCE((SELECT SUM(IGTF) FROM PAGOS_VENTAS PV WHERE PV.VENTA_CORRELATIVO = V.CORRELATIVO), 0)
    FROM VENTAS V
    INNER JOIN CLIENTES C ON V.CLIENTE_CODIGO = C.CODIGO
    WHERE V.ESTATUS = 'R'
      AND V.IMPACTA_CONTABILIDAD = 'S'
      AND SUBSTRING(V.FECHA_EMISION FROM 1 FOR 7) BETWEEN :PERIODO_INICIO AND :PERIODO_FIN
    ORDER BY V.FECHA_EMISION, V.DOCUMENTO
    INTO
        :FECHA_COMPROBANTE,
        :NUMERO_COMPROBANTE,
        :RIF_CLIENTE,
        :NOMBRE_CLIENTE,
        :NUMERO_FACTURA,
        :NUMERO_CONTROL,
        :TOTAL_VENTA,
        :BASE_IMPONIBLE,
        :IMPUESTO_IVA,
        :IMPUESTO_IVA_RETENIDO,
        :VENTA_EXENTA,
        :IGTF
    DO
        SUSPEND;
END;

-- Procedimiento: REPORTE_LIBRO_COMPRAS
-- Genera el libro de compras para un período fiscal
CREATE OR ALTER PROCEDURE REPORTE_LIBRO_COMPRAS (
    PERIODO_INICIO VARCHAR(7),
    PERIODO_FIN VARCHAR(7)
)
RETURNS (
    FECHA_COMPROBANTE DATE,
    NUMERO_COMPROBANTE VARCHAR(20),
    RIF_PROVEEDOR VARCHAR(20),
    NOMBRE_PROVEEDOR VARCHAR(160),
    NUMERO_FACTURA VARCHAR(20),
    NUMERO_CONTROL VARCHAR(20),
    TOTAL_COMPRA DECIMAL(18,2),
    BASE_IMPONIBLE DECIMAL(18,2),
    IMPUESTO_IVA DECIMAL(18,2),
    IMPUESTO_IVA_RETENIDO DECIMAL(18,2),
    COMPRA_EXENTA DECIMAL(18,2),
    ISLR_RETENIDO DECIMAL(18,2)
)
AS
BEGIN
    FOR SELECT
        C.FECHA_DOCUMENTO,
        C.DOCUMENTO,
        P.RIF,
        P.NOMBRE,
        C.DOCUMENTO,
        C.NUMERO_CONTROL,
        C.TOTAL_OPERACION,
        C.TOTAL_BASE_IMPONIBLE,
        C.TOTAL_IMPUESTO_FISCAL,
        C.TOTAL_RETENCION_IVA,
        C.TOTAL_EXENTO,
        C.TOTAL_RETENCION_ISLR
    FROM COMPRAS C
    INNER JOIN PROVEEDORES P ON C.PROVEEDOR_CODIGO = P.CODIGO
    WHERE C.ESTATUS = 'R'
      AND C.IMPACTA_CONTABILIDAD = 'S'
      AND SUBSTRING(C.FECHA_DOCUMENTO FROM 1 FOR 7) BETWEEN :PERIODO_INICIO AND :PERIODO_FIN
    ORDER BY C.FECHA_DOCUMENTO, C.DOCUMENTO
    INTO
        :FECHA_COMPROBANTE,
        :NUMERO_COMPROBANTE,
        :RIF_PROVEEDOR,
        :NOMBRE_PROVEEDOR,
        :NUMERO_FACTURA,
        :NUMERO_CONTROL,
        :TOTAL_COMPRA,
        :BASE_IMPONIBLE,
        :IMPUESTO_IVA,
        :IMPUESTO_IVA_RETENIDO,
        :COMPRA_EXENTA,
        :ISLR_RETENIDO
    DO
        SUSPEND;
END;

-- ============================================================================
-- FIN DE LOS STORED PROCEDURES
-- ============================================================================
