# 🟣 Violet ERP - Esquema de Base de Datos Completo

Basado en el análisis del sistema ValeryProfesional original.

## 📊 Motor de Base de Datos

**Original:** Firebird 2.5.2
**Migración:** SQLite (local) / PostgreSQL (producción)

---

## 📁 Tablas Principales por Módulo

### 1. CLIENTES (CXC)

```sql
CREATE TABLE CLIENTES (
    CODIGO VARCHAR(15) PRIMARY KEY,
    NOMBRE VARCHAR(160) NOT NULL,
    REFERENCIA VARCHAR(20),
    CONTACTO VARCHAR(50),
    VENDEDOR_CODIGO VARCHAR(15),
    ZONA_VENTA_CODIGO VARCHAR(15),
    LISTA_PRECIOS_CODIGO VARCHAR(15),
    CUENTA_CONTABLE VARCHAR(22),
    RIF VARCHAR(20) NOT NULL,
    NIT VARCHAR(20),
    DIRECCION VARCHAR(160),
    CIUDAD VARCHAR(40),
    ESTADO VARCHAR(40),
    PAIS VARCHAR(40),
    CODIGO_POSTAL VARCHAR(10),
    TELEFONOS VARCHAR(40),
    FAX VARCHAR(40),
    CORREO_ELECTRONICO VARCHAR(60),
    LIMITE_CREDITO DECIMAL(18,2) DEFAULT 0,
    DIAS_CREDITO SMALLINT DEFAULT 0,
    CREDITO_DISPONIBLE DECIMAL(18,2),
    TOTAL_DEBITOS DECIMAL(18,2),
    TOTAL_CREDITOS DECIMAL(18,2),
    TOTAL_ANTICIPOS DECIMAL(18,2),
    TOTAL_SALDO DECIMAL(18,2),
    DENOMINACION_FISCAL VARCHAR(2), -- CO=Común, GB=Gran Contribuyente, NO=No contribuyente
    PRECIO_VENTA CHAR(1), -- 1-7 (listas de precios)
    RETENCION DECIMAL(5,2) DEFAULT 0,
    DESCUENTO DECIMAL(5,2) DEFAULT 0,
    EDITAR_DATOS_FISCALES CHAR(1) DEFAULT 'F',
    ACEPTAR_CHEQUE CHAR(1) DEFAULT 'F',
    REQUIERE_CLAVE CHAR(1) DEFAULT 'F',
    NOTAS VARCHAR(120),
    MAXIMO_MONTO_VENTA DECIMAL(18,2),
    MAXIMO_CREDITO DECIMAL(18,2),
    ULTIMA_VENTA_CONTADO TIMESTAMP,
    MONTO_ULTIMA_VENTA_CONTADO DECIMAL(18,2),
    ULTIMA_VENTA_CREDITO TIMESTAMP,
    MONTO_ULTIMA_VENTA_CREDITO DECIMAL(18,2),
    ULTIMO_PAGO TIMESTAMP,
    MONTO_ULTIMO_PAGO DECIMAL(18,2),
    ESTATUS CHAR(1) DEFAULT 'A', -- A=Activo, I=Inactivo
    FECHA_INICIO DATE,
    GRUPO_CLIENTES_CODIGO VARCHAR(15),
    MUNICIPIO VARCHAR(40),
    CONTRIBUYENTE_ESPECIAL CHAR(1) DEFAULT 'F',
    TIPO_VENTA CHAR(2),
    TIPO_CLIENTE CHAR(2),
    DV VARCHAR(2), -- Dígito verificador (Panamá)
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
```

### 2. VENTAS

```sql
CREATE TABLE VENTAS (
    CORRELATIVO INTEGER PRIMARY KEY AUTOINCREMENT,
    CORRELATIVO_CODIGO SMALLINT,
    DOCUMENTO VARCHAR(10) NOT NULL,
    TIPO_DOCUMENTO CHAR(3) NOT NULL, -- FAC, FCR, NCR, NDB, PED, ODD, PRS, NET, FPV
    CLIENTE_CODIGO VARCHAR(15) NOT NULL,
    CLIENTE_NOMBRE VARCHAR(160),
    CLIENTE_RIF VARCHAR(20),
    CLIENTE_NIT VARCHAR(20),
    CLIENTE_CONTACTO VARCHAR(50),
    CLIENTE_DIRECCION VARCHAR(160),
    CLIENTE_TELEFONOS VARCHAR(40),
    CLIENTE_FAX VARCHAR(40),
    CLIENTE_CORREO_E VARCHAR(60),
    CLIENTE_ZONA VARCHAR(15),
    CLIENTE_TIPO_PRECIO CHAR(1),
    DENOMINACION_FISCAL VARCHAR(2),
    MONEDA_CODIGO VARCHAR(15),
    FACTOR_CAMBIO DECIMAL(18,6) DEFAULT 1,
    FECHA_EMISION DATE NOT NULL,
    HORA_EMISION TIME,
    DIAS_VENCIMIENTO SMALLINT DEFAULT 0,
    FECHA_VENCIMIENTO DATE,
    DEPOSITO_CODIGO VARCHAR(15),
    VENDEDOR_CODIGO VARCHAR(15),
    ORDEN_DE_COMPRA VARCHAR(10),
    FECHA_ORDEN_COMPRA DATE,
    RETENCION DECIMAL(18,2) DEFAULT 0,
    CONTADO DECIMAL(18,2) DEFAULT 0,
    CREDITO DECIMAL(18,2) DEFAULT 0,
    ANTICIPO DECIMAL(18,2) DEFAULT 0,
    TOTAL_CANCELADO DECIMAL(18,2),
    VUELTO DECIMAL(18,2) DEFAULT 0,
    TOTAL_BRUTO_LINEAS DECIMAL(18,2),
    TOTAL_DESCUENTO_LINEAS DECIMAL(18,2),
    TOTAL_NETO_LINEAS DECIMAL(18,2),
    TOTAL_IMPUESTO_LINEAS DECIMAL(18,2),
    TOTAL_LINEAS DECIMAL(18,2),
    DESCUENTO_1 DECIMAL(18,2) DEFAULT 0,
    PORC_DESCUENTO_1 DECIMAL(5,2) DEFAULT 0,
    DESCUENTO_2 DECIMAL(18,2) DEFAULT 0,
    PORC_DESCUENTO_2 DECIMAL(5,2) DEFAULT 0,
    FLETE DECIMAL(18,2) DEFAULT 0,
    PORC_FLETE DECIMAL(5,2) DEFAULT 0,
    TOTAL_NETO DECIMAL(18,2),
    IMPUESTO DECIMAL(18,2),
    PORC_IMPUESTO DECIMAL(5,2) DEFAULT 16,
    TOTAL_IMPUESTO_MUNICIPAL DECIMAL(18,2) DEFAULT 0,
    TOTAL_IMPUESTO_ADICIONAL DECIMAL(18,2) DEFAULT 0,
    TOTAL_OPERACION DECIMAL(18,2),
    TOTAL_BASE_IMPONIBLE_LINEAS DECIMAL(18,2),
    TOTAL_IMPUESTO_FISCAL_LINEAS DECIMAL(18,2),
    TOTAL_EXENTO_LINEAS DECIMAL(18,2),
    TOTAL_BASE_IMPONIBLE DECIMAL(18,2),
    TOTAL_IMPUESTO_FISCAL DECIMAL(18,2),
    TOTAL_EXENTO DECIMAL(18,2),
    TOTAL_COSTO DECIMAL(18,2),
    ESTACION VARCHAR(30),
    USUARIO_CODIGO VARCHAR(15),
    TEMPORAL CHAR(1) DEFAULT 'F',
    ASIGNAR_COSTO DECIMAL(18,2),
    PORC_RETENCION DECIMAL(5,2),
    CORRELATIVO_CXC INTEGER,
    MOTIVO_CODIGO VARCHAR(15),
    TOTAL_COSTO_PROMEDIO DECIMAL(18,2),
    IMPUESTO_IVA_CODIGO VARCHAR(15),
    TOTAL_RETENCION_IVA DECIMAL(18,2) DEFAULT 0,
    PORC_RETENCION_IVA DECIMAL(5,2) DEFAULT 75,
    DOCUMENTO_RETENCION_IVA VARCHAR(20),
    CONTROL_INTERNO CHAR(2),
    DOCUMENTO_NCR VARCHAR(10),
    NUMERO_CONTROL VARCHAR(10),
    FECHA_RECEPCION_RTP DATE,
    FECHA_HORA_IMPRESION TIMESTAMP,
    FECHA_Y_HORA TIMESTAMP,
    TOTAL_IMPUESTO_AL_LICOR DECIMAL(18,2) DEFAULT 0,
    FECHA_HORA_REGISTRO TIMESTAMP,
    TOTAL_COSTO_IMP DECIMAL(18,2),
    TOTAL_COSTO_PROMEDIO_IMP DECIMAL(18,2),
    TOTAL_CANTIDAD_ITEMS DECIMAL(18,4),
    TOTAL_ITEMS INTEGER,
    TIPO_TRANSACCION VARCHAR(15),
    ESTATUS CHAR(1) DEFAULT 'R', -- R=Registrada, A=Anulada
    IMPACTA_INVENTARIO CHAR(1) DEFAULT 'S',
    IMPACTA_CONTABILIDAD CHAR(1) DEFAULT 'S',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Índices
CREATE INDEX IDX_VENTAS_DOCUMENTO ON VENTAS(DOCUMENTO);
CREATE INDEX IDX_VENTAS_CLIENTE ON VENTAS(CLIENTE_CODIGO);
CREATE INDEX IDX_VENTAS_FECHA ON VENTAS(FECHA_EMISION);
CREATE INDEX IDX_VENTAS_TIPO ON VENTAS(TIPO_DOCUMENTO);
CREATE INDEX IDX_VENTAS_ESTATUS ON VENTAS(ESTATUS);
```

### 3. VENTAS_DESGLOSE (Detalle de Ventas)

```sql
CREATE TABLE VENTAS_DESGLOSE (
    CORRELATIVO INTEGER NOT NULL,
    CODIGO INTEGER NOT NULL,
    TIPO_REGISTRO CHAR(1) DEFAULT 'P', -- P=Producto, S=Servicio
    PRODUCTO_CODIGO VARCHAR(15),
    PRODUCTO_NOMBRE VARCHAR(160),
    PRODUCTO_DESCRIPCION VARCHAR(255),
    PRODUCTO_REFERENCIA VARCHAR(20),
    CANTIDAD DECIMAL(18,4) NOT NULL,
    UNIDAD_CODIGO VARCHAR(15),
    PRECIO DECIMAL(18,6) NOT NULL,
    PORC_DESCUENTO DECIMAL(5,2) DEFAULT 0,
    DESCUENTO DECIMAL(18,2) DEFAULT 0,
    BRUTO DECIMAL(18,2),
    NETO DECIMAL(18,2),
    IMPUESTO DECIMAL(18,2),
    TOTAL DECIMAL(18,2),
    COSTO DECIMAL(18,4),
    COSTO_PROMEDIO DECIMAL(18,4),
    ALICUOTA_IVA DECIMAL(5,2) DEFAULT 16,
    IMPUESTO_IVA_CODIGO VARCHAR(15),
    EXENTO CHAR(1) DEFAULT 'F',
    IMPUESTO_MUNICIPAL DECIMAL(18,2) DEFAULT 0,
    IMPUESTO_ADICIONAL DECIMAL(18,2) DEFAULT 0,
    SERIAL VARCHAR(50),
    LOTE VARCHAR(50),
    FECHA_VENCIMIENTO DATE,
    DEPOSITO_CODIGO VARCHAR(15),
    ORDEN INTEGER,
    PRIMARY KEY (CORRELATIVO, CODIGO),
    FOREIGN KEY (CORRELATIVO) REFERENCES VENTAS(CORRELATIVO) ON DELETE CASCADE
);

CREATE INDEX IDX_VENTAS_DESGLOSE_PRODUCTO ON VENTAS_DESGLOSE(PRODUCTO_CODIGO);
CREATE INDEX IDX_VENTAS_DESGLOSE_LOTE ON VENTAS_DESGLOSE(LOTE);
```

### 4. VENTAS_DESGLOSE_IMPUESTO

```sql
CREATE TABLE VENTAS_DESGLOSE_IMPUESTO (
    CORRELATIVO INTEGER NOT NULL,
    CODIGO INTEGER NOT NULL,
    ALICUOTA DECIMAL(5,2) NOT NULL,
    BASE_IMPONIBLE DECIMAL(18,2) NOT NULL,
    IMPUESTO DECIMAL(18,2) NOT NULL,
    EXENTO CHAR(1) DEFAULT 'F',
    PRIMARY KEY (CORRELATIVO, CODIGO, ALICUOTA),
    FOREIGN KEY (CORRELATIVO) REFERENCES VENTAS(CORRELATIVO) ON DELETE CASCADE
);
```

### 5. CXC (Cuentas por Cobrar)

```sql
CREATE TABLE CXC (
    CORRELATIVO INTEGER PRIMARY KEY AUTOINCREMENT,
    CLIENTE_CODIGO VARCHAR(15) NOT NULL,
    DOCUMENTO VARCHAR(10) NOT NULL,
    TIPO_DOCUMENTO CHAR(3),
    FECHA DATE NOT NULL,
    FECHA_VENCIMIENTO DATE,
    TOTAL_OPERACION DECIMAL(18,2) NOT NULL,
    TOTAL_BASE_IMPONIBLE DECIMAL(18,2),
    TOTAL_IMPUESTO DECIMAL(18,2),
    SALDO DECIMAL(18,2) NOT NULL,
    ESTATUS CHAR(1) DEFAULT 'P', -- P=Pendiente, C=Cancelado
    VENTA_CORRELATIVO INTEGER,
    USUARIO_CODIGO VARCHAR(15),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CLIENTE_CODIGO) REFERENCES CLIENTES(CODIGO),
    FOREIGN KEY (VENTA_CORRELATIVO) REFERENCES VENTAS(CORRELATIVO)
);

CREATE INDEX IDX_CXC_CLIENTE ON CXC(CLIENTE_CODIGO);
CREATE INDEX IDX_CXC_DOCUMENTO ON CXC(DOCUMENTO);
CREATE INDEX IDX_CXC_ESTADO ON CXC(ESTATUS);
CREATE INDEX IDX_CXC_VENCIMIENTO ON CXC(FECHA_VENCIMIENTO);
```

---

## 🔧 Triggers y Stored Procedures

### Trigger: VENTAS_AI0 (After Insert)

```sql
-- Este trigger se ejecuta después de insertar una venta
-- Actualiza el CXC si es venta a crédito
-- Actualiza el inventario
-- Actualiza el contabilidad

CREATE TRIGGER VENTAS_AI0
AFTER INSERT ON VENTAS
FOR EACH ROW
BEGIN
    -- Si es venta a crédito, crear registro en CXC
    IF NEW.CREDITO > 0 THEN
        INSERT INTO CXC (
            CLIENTE_CODIGO,
            DOCUMENTO,
            TIPO_DOCUMENTO,
            FECHA,
            FECHA_VENCIMIENTO,
            TOTAL_OPERACION,
            TOTAL_BASE_IMPONIBLE,
            TOTAL_IMPUESTO,
            SALDO,
            ESTATUS,
            VENTA_CORRELATIVO,
            CREATED_AT
        ) VALUES (
            NEW.CLIENTE_CODIGO,
            NEW.DOCUMENTO,
            'FCR',
            NEW.FECHA_EMISION,
            NEW.FECHA_VENCIMIENTO,
            NEW.TOTAL_OPERACION,
            NEW.TOTAL_BASE_IMPONIBLE,
            NEW.TOTAL_IMPUESTO,
            NEW.CREDITO,
            'P',
            NEW.CORRELATIVO,
            CURRENT_TIMESTAMP
        );
    END IF;
    
    -- Actualizar inventario (si impacta inventario)
    IF NEW.IMPACTA_INVENTARIO = 'S' THEN
        -- El detalle se maneja en otro trigger
        UPDATE CONFIGuracion
        SET ULTIMA_ACTUALIZACION = CURRENT_TIMESTAMP
        WHERE PARAMETRO = 'INVENTARIO';
    END IF;
END;
```

### Stored Procedure: CALCULAR_RETENCION_IVA

```sql
CREATE PROCEDURE CALCULAR_RETENCION_IVA(
    MONTO_IVA DECIMAL(18,2),
    CONTRIBUYENTE_ESPECIAL CHAR(1)
)
RETURNS (
    PORCENTAJE DECIMAL(5,2),
    MONTO_RETENIDO DECIMAL(18,2)
)
AS
BEGIN
    -- Si es contribuyente especial, retiene 100%
    -- Si es ordinario, retiene 75%
    IF CONTRIBUYENTE_ESPECIAL = 'T' THEN
        PORCENTAJE = 100;
    ELSE
        PORCENTAJE = 75;
    END IF;
    
    MONTO_RETENIDO = (MONTO_IVA * PORCENTAJE) / 100;
    
    SUSPEND;
END
```

### Stored Procedure: CALCULAR_IGTF

```sql
CREATE PROCEDURE CALCULAR_IGTF(
    TOTAL_OPERACION DECIMAL(18,2),
    ES_PAGO_DIVISAS CHAR(1)
)
RETURNS (
    TASA DECIMAL(5,2),
    MONTO_IGTF DECIMAL(18,2),
    TOTAL_CON_IGTF DECIMAL(18,2)
)
AS
BEGIN
    IF ES_PAGO_DIVISAS = 'T' THEN
        TASA = 3;
        MONTO_IGTF = (TOTAL_OPERACION * TASA) / 100;
        TOTAL_CON_IGTF = TOTAL_OPERACION + MONTO_IGTF;
    ELSE
        TASA = 0;
        MONTO_IGTF = 0;
        TOTAL_CON_IGTF = TOTAL_OPERACION;
    END IF;
    
    SUSPEND;
END
```

---

## 📊 Tablas de Configuración

### CONFIGURACION

```sql
CREATE TABLE CONFIGURACION (
    PARAMETRO VARCHAR(50) PRIMARY KEY,
    VALOR VARCHAR(500),
    DESCRIPCION VARCHAR(255),
    TIPO CHAR(1), -- T=Texto, N=Numérico, B=Booleano, F=Fecha
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Datos iniciales
INSERT INTO CONFIGURACION (PARAMETRO, VALOR, DESCRIPCION, TIPO) VALUES
('EMPRESA_NOMBRE', 'MI EMPRESA C.A.', 'Nombre de la empresa', 'T'),
('EMPRESA_RIF', 'J-12345678-9', 'RIF de la empresa', 'T'),
('EMPRESA_DIRECCION', 'Dirección fiscal', 'Dirección de la empresa', 'T'),
('ALICUOTA_IVA', '16', 'Alícuota general de IVA', 'N'),
('PORC_RETENCION_IVA', '75', 'Porcentaje de retención IVA ordinario', 'N'),
('PORC_RETENCION_IVA_ESPECIAL', '100', 'Porcentaje de retención IVA especial', 'N'),
('TASA_IGTF', '3', 'Tasa del IGTF', 'N'),
('CONTRIBUYENTE_ESPECIAL', 'F', 'Es contribuyente especial', 'B'),
('MONEDA_LOCAL', 'VES', 'Moneda local', 'T'),
('EJERCICIO_FISCAL', '2026', 'Año del ejercicio fiscal', 'N');
```

### NUMERACION_DOCUMENTOS

```sql
CREATE TABLE NUMERACION_DOCUMENTOS (
    TIPO_DOCUMENTO VARCHAR(10) PRIMARY KEY,
    DESCRIPCION VARCHAR(100),
    ULTIMO_NUMERO INTEGER DEFAULT 0,
    PREFIJO VARCHAR(5),
    LONGITUD INTEGER DEFAULT 8,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Datos iniciales
INSERT INTO NUMERACION_DOCUMENTOS (TIPO_DOCUMENTO, DESCRIPCION, ULTIMO_NUMERO, PREFIJO) VALUES
('FAC', 'Factura', 0, 'FAC'),
('FCR', 'Factura Crédito', 0, 'FCR'),
('NCR', 'Nota Crédito', 0, 'NCR'),
('NDB', 'Nota Débito', 0, 'NDB'),
('PED', 'Pedido', 0, 'PED'),
('ODD', 'Orden Despacho', 0, 'ODD'),
('PRS', 'Presupuesto', 0, 'PRS');
```

---

## 📝 Tablas de Auditoría

### AUDITORIA

```sql
CREATE TABLE AUDITORIA (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TABLA VARCHAR(50) NOT NULL,
    REGISTRO_ID VARCHAR(50) NOT NULL,
    ACCION CHAR(1) NOT NULL, -- I=Insert, U=Update, D=Delete
    DATOS_ANTERIORES TEXT, -- JSON con los datos anteriores
    DATOS_NUEVOS TEXT, -- JSON con los datos nuevos
    USUARIO_CODIGO VARCHAR(15),
    ESTACION VARCHAR(30),
    FECHA_HORA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_AUDITORIA_TABLA ON AUDITORIA(TABLA);
CREATE INDEX IDX_AUDITORIA_FECHA ON AUDITORIA(FECHA_HORA);
CREATE INDEX IDX_AUDITORIA_USUARIO ON AUDITORIA(USUARIO_CODIGO);
```

---

## 🎯 Vistas Principales

### VISTA_LIBRO_VENTAS

```sql
CREATE VIEW VISTA_LIBRO_VENTAS AS
SELECT 
    V.FECHA_EMISION AS FECHA,
    V.DOCUMENTO AS NUMERO_FACTURA,
    V.NUMERO_CONTROL,
    C.RIF AS RIF_CLIENTE,
    C.NOMBRE AS NOMBRE_CLIENTE,
    V.TOTAL_BASE_IMPONIBLE AS BASE_IMPONIBLE,
    V.TOTAL_IMPUESTO_FISCAL AS IMPUESTO_IVA,
    V.TOTAL_EXENTO AS VENTA_EXENTA,
    V.TOTAL_RETENCION_IVA AS RETENCION_IVA,
    V.TOTAL_OPERACION AS TOTAL_VENTA
FROM VENTAS V
INNER JOIN CLIENTES C ON V.CLIENTE_CODIGO = C.CODIGO
WHERE V.ESTATUS = 'R'
  AND V.IMPACTA_CONTABILIDAD = 'S'
ORDER BY V.FECHA_EMISION, V.DOCUMENTO;
```

### VISTA_LIBRO_COMPRAS

```sql
CREATE VIEW VISTA_LIBRO_COMPRAS AS
SELECT 
    C.FECHA_DOCUMENTO AS FECHA,
    C.DOCUMENTO AS NUMERO_FACTURA,
    C.NUMERO_CONTROL,
    P.RIF AS RIF_PROVEEDOR,
    P.NOMBRE AS NOMBRE_PROVEEDOR,
    C.TOTAL_BASE_IMPONIBLE AS BASE_IMPONIBLE,
    C.TOTAL_IMPUESTO_FISCAL AS IMPUESTO_IVA,
    C.TOTAL_EXENTO AS COMPRA_EXENTA,
    C.TOTAL_RETENCION_IVA AS RETENCION_IVA,
    C.TOTAL_RETENCION_ISLR AS RETENCION_ISLR,
    C.TOTAL_OPERACION AS TOTAL_COMPRA
FROM COMPRAS C
INNER JOIN PROVEEDORES P ON C.PROVEEDOR_CODIGO = P.CODIGO
WHERE C.ESTATUS = 'R'
  AND C.IMPACTA_CONTABILIDAD = 'S'
ORDER BY C.FECHA_DOCUMENTO, C.DOCUMENTO;
```

---

## 📌 Notas de Migración

### Consideraciones Firebird → SQLite/PostgreSQL

1. **Tipos de Datos:**
   - `DECIMAL(18,2)` → `DECIMAL(18,2)` (igual)
   - `DOUBLE PRECISION` → `REAL` o `DOUBLE PRECISION`
   - `DATE` → `DATE` (igual)
   - `TIME` → `TIME` (igual)
   - `TIMESTAMP` → `DATETIME` (SQLite) / `TIMESTAMP` (PostgreSQL)

2. **Autoincrement:**
   - Firebird: `GENERATOR` + `TRIGGER`
   - SQLite: `AUTOINCREMENT`
   - PostgreSQL: `SERIAL` o `IDENTITY`

3. **Triggers:**
   - La sintaxis varía ligeramente entre motores
   - Revisar cada trigger cuidadosamente

4. **Stored Procedures:**
   - Firebird: `RETURNS` + `SUSPEND`
   - PostgreSQL: `RETURNS TABLE` + `RETURN QUERY`
   - SQLite: No soporta SP, usar funciones o lógica en aplicación

---

**Fecha de Creación:** 2026-03-28
**Basado en:** ValeryProfesional / Violet ERP
**Versión:** 1.0.0
