/* =============================================================================
   VIOLET ERP - Esquema Firebird
   Basado en ValeryProfesional
   ============================================================================= */

SET NAMES UTF8;
SET SQL DIALECT 3;

/* =============================================================================
   TABLAS BÁSICAS
   ============================================================================= */

/* UNIDADES */
CREATE TABLE UNIDADES (
    CODIGO VARCHAR(15) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    CONSTRAINT PK_UNIDADES PRIMARY KEY (CODIGO)
);

/* MONEDA */
CREATE TABLE MONEDA (
    CODIGO VARCHAR(15) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    NOTAS VARCHAR(120),
    FACTOR_CAMBIO DOUBLE PRECISION DEFAULT 1,
    DIAS_CADUCIDAD SMALLINT DEFAULT 0,
    PROXIMO_CAMBIO DATE,
    MONEDA_PRINCIPAL CHAR(1) DEFAULT 'N',
    CADUCA CHAR(1) DEFAULT 'N',
    FACTOR_CAMBIO_COMPRA DOUBLE PRECISION,
    TIPO_APLICACION_FACTOR_VENTA CHAR(1),
    TIPO_APLICACION_FACTOR_COMPRA CHAR(1),
    SIMBOLO VARCHAR(5),
    CONSTRAINT PK_MONEDA PRIMARY KEY (CODIGO)
);

/* ZONAS */
CREATE TABLE ZONAS (
    CODIGO VARCHAR(15) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    CONSTRAINT PK_ZONAS PRIMARY KEY (CODIGO)
);

/* DEPOSITOS */
CREATE TABLE DEPOSITOS (
    CODIGO VARCHAR(15) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    DIRECCION VARCHAR(160),
    TELEFONOS VARCHAR(40),
    UBICACION VARCHAR(50),
    TIPO CHAR(1) DEFAULT 'F',
    CONSTRAINT PK_DEPOSITOS PRIMARY KEY (CODIGO)
);

/* USUARIOS */
CREATE TABLE USUARIOS (
    CODIGO VARCHAR(15) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    CLAVE VARCHAR(50),
    CORREO_E VARCHAR(60),
    BLOQUEADO CHAR(1) DEFAULT 'N',
    CAMBIAR_CLAVE CHAR(1) DEFAULT 'S',
    ULTIMO_ACCESO TIMESTAMP,
    CONSTRAINT PK_USUARIOS PRIMARY KEY (CODIGO)
);

/* PERFILES */
CREATE TABLE PERFILES (
    CODIGO VARCHAR(15) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(120),
    CONSTRAINT PK_PERFILES PRIMARY KEY (CODIGO)
);

/* PERMISOS */
CREATE TABLE PERMISOS (
    PERFIL_CODIGO VARCHAR(15) NOT NULL,
    PROCESO_CODIGO VARCHAR(15) NOT NULL,
    INSERTAR CHAR(1) DEFAULT 'N',
    MODIFICAR CHAR(1) DEFAULT 'N',
    ELIMINAR CHAR(1) DEFAULT 'N',
    CONSULTAR CHAR(1) DEFAULT 'S',
    PROCESAR CHAR(1) DEFAULT 'N',
    CONSTRAINT PK_PERMISOS PRIMARY KEY (PERFIL_CODIGO, PROCESO_CODIGO),
    CONSTRAINT FK_PERMISOS_PERFILES FOREIGN KEY (PERFIL_CODIGO) REFERENCES PERFILES(CODIGO)
);

/* =============================================================================
   CLIENTES
   ============================================================================= */

CREATE TABLE CLIENTES (
    CODIGO VARCHAR(15) NOT NULL,
    NOMBRE VARCHAR(160) NOT NULL,
    RIF VARCHAR(20),
    NIT VARCHAR(20),
    CONTACTO VARCHAR(50),
    DIRECCION VARCHAR(160),
    TELEFONOS VARCHAR(40),
    FAX VARCHAR(40),
    CORREO_E VARCHAR(60),
    ZONA_CODIGO VARCHAR(15),
    TIPO_PRECIO CHAR(1) DEFAULT 'A',
    CREDITO_APROBADO CHAR(1) DEFAULT 'N',
    LIMITE_CREDITO DOUBLE PRECISION DEFAULT 0,
    SALDO_ACTUAL DOUBLE PRECISION DEFAULT 0,
    ULTIMA_COMPRA DATE,
    ACTIVO CHAR(1) DEFAULT 'S',
    CONSTRAINT PK_CLIENTES PRIMARY KEY (CODIGO),
    CONSTRAINT FK_CLIENTES_ZONAS FOREIGN KEY (ZONA_CODIGO) REFERENCES ZONAS(CODIGO)
);

/* =============================================================================
   PROVEEDORES
   ============================================================================= */

CREATE TABLE PROVEEDORES (
    CODIGO VARCHAR(15) NOT NULL,
    NOMBRE VARCHAR(160) NOT NULL,
    RIF VARCHAR(20),
    NIT VARCHAR(20),
    CONTACTO VARCHAR(50),
    DIRECCION VARCHAR(160),
    TELEFONOS VARCHAR(40),
    FAX VARCHAR(40),
    CORREO_E VARCHAR(60),
    LIMITE_CREDITO DOUBLE PRECISION DEFAULT 0,
    SALDO_ACTUAL DOUBLE PRECISION DEFAULT 0,
    DIAS_CREDITO SMALLINT DEFAULT 0,
    ACTIVO CHAR(1) DEFAULT 'S',
    CONSTRAINT PK_PROVEEDORES PRIMARY KEY (CODIGO)
);

/* =============================================================================
   PRODUCTOS
   ============================================================================= */

CREATE TABLE PRODUCTOS (
    CODIGO VARCHAR(15) NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    NOMBRE_CORTO VARCHAR(50),
    DESCRIPCION VARCHAR(250),
    UNIDAD_CODIGO VARCHAR(15) NOT NULL,
    MARCA VARCHAR(50),
    LINEA VARCHAR(50),
    CATEGORIA VARCHAR(50),
    COSTO_ACTUAL DOUBLE PRECISION DEFAULT 0,
    PRECIO_VENTA DOUBLE PRECISION DEFAULT 0,
    PRECIO_VENTA_1 DOUBLE PRECISION DEFAULT 0,
    PRECIO_VENTA_2 DOUBLE PRECISION DEFAULT 0,
    PRECIO_VENTA_3 DOUBLE PRECISION DEFAULT 0,
    EXISTENCIA_ACTUAL DOUBLE PRECISION DEFAULT 0,
    EXISTENCIA_MINIMA DOUBLE PRECISION DEFAULT 0,
    EXISTENCIA_MAXIMA DOUBLE PRECISION DEFAULT 0,
    UBICACION VARCHAR(50),
    PESO DOUBLE PRECISION,
    VOLUMEN DOUBLE PRECISION,
    IMPUESTO_CODIGO VARCHAR(15),
    IMPUESTO_TASA DOUBLE PRECISION DEFAULT 0,
    ACTIVO CHAR(1) DEFAULT 'S',
    CONSTRAINT PK_PRODUCTOS PRIMARY KEY (CODIGO),
    CONSTRAINT FK_PRODUCTOS_UNIDADES FOREIGN KEY (UNIDAD_CODIGO) REFERENCES UNIDADES(CODIGO)
);

/* =============================================================================
   COMPRAS
   ============================================================================= */

CREATE TABLE COMPRAS (
    CORRELATIVO INTEGER NOT NULL,
    DOCUMENTO VARCHAR(10) NOT NULL,
    TIPO_DOCUMENTO CHAR(3) NOT NULL,
    PROVEEDOR_CODIGO VARCHAR(15) NOT NULL,
    PROVEEDOR_NOMBRE VARCHAR(160),
    PROVEEDOR_RIF VARCHAR(20),
    MONEDA_CODIGO VARCHAR(15) DEFAULT 'DOP',
    FACTOR_CAMBIO DOUBLE PRECISION DEFAULT 1,
    FECHA_EMISION DATE NOT NULL,
    FECHA_REGISTRO DATE NOT NULL,
    DIAS_CREDITO SMALLINT DEFAULT 0,
    FECHA_VENCIMIENTO DATE,
    DEPOSITO_CODIGO VARCHAR(15) NOT NULL,
    TOTAL_BRUTO_LINEAS DOUBLE PRECISION DEFAULT 0,
    TOTAL_DESCUENTO_LINEAS DOUBLE PRECISION DEFAULT 0,
    TOTAL_NETO_LINEAS DOUBLE PRECISION DEFAULT 0,
    TOTAL_IMPUESTO_LINEAS DOUBLE PRECISION DEFAULT 0,
    TOTAL_LINEAS DOUBLE PRECISION DEFAULT 0,
    DESCUENTO_1 DOUBLE PRECISION DEFAULT 0,
    PORC_DESCUENTO_1 DOUBLE PRECISION DEFAULT 0,
    DESCUENTO_2 DOUBLE PRECISION DEFAULT 0,
    PORC_DESCUENTO_2 DOUBLE PRECISION DEFAULT 0,
    TOTAL_NETO DOUBLE PRECISION DEFAULT 0,
    IMPUESTO DOUBLE PRECISION DEFAULT 0,
    PORC_IMPUESTO DOUBLE PRECISION DEFAULT 0,
    TOTAL_IMPUESTO_MUNICIPAL DOUBLE PRECISION DEFAULT 0,
    TOTAL_IMPUESTO_ADICIONAL DOUBLE PRECISION DEFAULT 0,
    TOTAL_OPERACION DOUBLE PRECISION DEFAULT 0,
    TOTAL_BASE_IMPONIBLE DOUBLE PRECISION DEFAULT 0,
    TOTAL_IMPUESTO_FISCAL DOUBLE PRECISION DEFAULT 0,
    TOTAL_EXENTO DOUBLE PRECISION DEFAULT 0,
    USUARIO_CODIGO VARCHAR(15) NOT NULL,
    ANULADA CHAR(1) DEFAULT 'N',
    FECHA_ANULACION DATE,
    USUARIO_ANULA_CODIGO VARCHAR(15),
    MOTIVO_ANULACION VARCHAR(120),
    NUMERO_CONTROL VARCHAR(10),
    CONSTRAINT PK_COMPRAS PRIMARY KEY (CORRELATIVO),
    CONSTRAINT FK_COMPRAS_PROVEEDORES FOREIGN KEY (PROVEEDOR_CODIGO) REFERENCES PROVEEDORES(CODIGO),
    CONSTRAINT FK_COMPRAS_DEPOSITOS FOREIGN KEY (DEPOSITO_CODIGO) REFERENCES DEPOSITOS(CODIGO),
    CONSTRAINT FK_COMPRAS_USUARIOS FOREIGN KEY (USUARIO_CODIGO) REFERENCES USUARIOS(CODIGO)
);

CREATE TABLE COMPRAS_DESGLOSE (
    CORRELATIVO INTEGER NOT NULL,
    LINEA SMALLINT NOT NULL,
    PRODUCTO_CODIGO VARCHAR(15) NOT NULL,
    PRODUCTO_NOMBRE VARCHAR(100),
    CANTIDAD DOUBLE PRECISION NOT NULL,
    COSTO_UNITARIO DOUBLE PRECISION NOT NULL,
    COSTO_TOTAL DOUBLE PRECISION NOT NULL,
    DESCUENTO DOUBLE PRECISION DEFAULT 0,
    IMPUESTO DOUBLE PRECISION DEFAULT 0,
    TOTAL DOUBLE PRECISION NOT NULL,
    DEPOSITO_CODIGO VARCHAR(15) NOT NULL,
    CONSTRAINT PK_COMPRAS_DESGLOSE PRIMARY KEY (CORRELATIVO, LINEA),
    CONSTRAINT FK_COMPRAS_DESGLOSE_COMPRAS FOREIGN KEY (CORRELATIVO) REFERENCES COMPRAS(CORRELATIVO) ON DELETE CASCADE,
    CONSTRAINT FK_COMPRAS_DESGLOSE_PRODUCTOS FOREIGN KEY (PRODUCTO_CODIGO) REFERENCES PRODUCTOS(CODIGO)
);

/* =============================================================================
   VENTAS
   ============================================================================= */

CREATE TABLE VENTAS (
    CORRELATIVO INTEGER NOT NULL,
    DOCUMENTO VARCHAR(10) NOT NULL,
    TIPO_DOCUMENTO CHAR(3) NOT NULL,
    CLIENTE_CODIGO VARCHAR(15) NOT NULL,
    CLIENTE_NOMBRE VARCHAR(160),
    CLIENTE_RIF VARCHAR(20),
    CLIENTE_NIT VARCHAR(20),
    CLIENTE_CONTACTO VARCHAR(50),
    CLIENTE_DIRECCION VARCHAR(160),
    CLIENTE_TELEFONOS VARCHAR(40),
    CLIENTE_CORREO_E VARCHAR(60),
    CLIENTE_ZONA VARCHAR(15),
    CLIENTE_TIPO_PRECIO CHAR(1),
    DENOMINACION_FISCAL VARCHAR(2),
    MONEDA_CODIGO VARCHAR(15) DEFAULT 'DOP',
    FACTOR_CAMBIO DOUBLE PRECISION DEFAULT 1,
    FECHA_EMISION DATE NOT NULL,
    HORA_EMISION TIME NOT NULL,
    DIAS_VENCIMIENTO SMALLINT DEFAULT 0,
    FECHA_VENCIMIENTO DATE,
    DEPOSITO_CODIGO VARCHAR(15) NOT NULL,
    VENDEDOR_CODIGO VARCHAR(15),
    ORDEN_DE_COMPRA VARCHAR(10),
    FECHA_ORDEN_COMPRA DATE,
    CONTADO DOUBLE PRECISION DEFAULT 0,
    CREDITO DOUBLE PRECISION DEFAULT 0,
    ANTICIPO DOUBLE PRECISION DEFAULT 0,
    TOTAL_CANCELADO DOUBLE PRECISION DEFAULT 0,
    VUELTO DOUBLE PRECISION DEFAULT 0,
    TOTAL_BRUTO_LINEAS DOUBLE PRECISION DEFAULT 0,
    TOTAL_DESCUENTO_LINEAS DOUBLE PRECISION DEFAULT 0,
    TOTAL_NETO_LINEAS DOUBLE PRECISION DEFAULT 0,
    TOTAL_IMPUESTO_LINEAS DOUBLE PRECISION DEFAULT 0,
    TOTAL_LINEAS DOUBLE PRECISION DEFAULT 0,
    DESCUENTO_1 DOUBLE PRECISION DEFAULT 0,
    PORC_DESCUENTO_1 DOUBLE PRECISION DEFAULT 0,
    DESCUENTO_2 DOUBLE PRECISION DEFAULT 0,
    PORC_DESCUENTO_2 DOUBLE PRECISION DEFAULT 0,
    FLETE DOUBLE PRECISION DEFAULT 0,
    PORC_FLETE DOUBLE PRECISION DEFAULT 0,
    TOTAL_NETO DOUBLE PRECISION DEFAULT 0,
    IMPUESTO DOUBLE PRECISION DEFAULT 0,
    PORC_IMPUESTO DOUBLE PRECISION DEFAULT 0,
    TOTAL_IMPUESTO_MUNICIPAL DOUBLE PRECISION DEFAULT 0,
    TOTAL_IMPUESTO_ADICIONAL DOUBLE PRECISION DEFAULT 0,
    TOTAL_OPERACION DOUBLE PRECISION DEFAULT 0,
    TOTAL_BASE_IMPONIBLE DOUBLE PRECISION DEFAULT 0,
    TOTAL_IMPUESTO_FISCAL DOUBLE PRECISION DEFAULT 0,
    TOTAL_EXENTO DOUBLE PRECISION DEFAULT 0,
    TOTAL_COSTO DOUBLE PRECISION DEFAULT 0,
    ESTACION VARCHAR(30),
    USUARIO_CODIGO VARCHAR(15) NOT NULL,
    TEMPORAL CHAR(1) DEFAULT 'N',
    PORC_RETENCION DOUBLE PRECISION DEFAULT 0,
    CORRELATIVO_CXC INTEGER,
    IMPUESTO_IVA_CODIGO VARCHAR(15),
    TOTAL_RETENCION_IVA DOUBLE PRECISION DEFAULT 0,
    PORC_RETENCION_IVA DOUBLE PRECISION DEFAULT 0,
    DOCUMENTO_RETENCION_IVA VARCHAR(20),
    CONTROL_INTERNO CHAR(2),
    DOCUMENTO_NCR VARCHAR(10),
    NUMERO_CONTROL VARCHAR(10),
    FECHA_HORA_REGISTRO TIMESTAMP,
    ANULADA CHAR(1) DEFAULT 'N',
    FECHA_ANULACION DATE,
    USUARIO_ANULA_CODIGO VARCHAR(15),
    MOTIVO_ANULACION VARCHAR(120),
    CONSTRAINT PK_VENTAS PRIMARY KEY (CORRELATIVO),
    CONSTRAINT FK_VENTAS_CLIENTES FOREIGN KEY (CLIENTE_CODIGO) REFERENCES CLIENTES(CODIGO),
    CONSTRAINT FK_VENTAS_DEPOSITOS FOREIGN KEY (DEPOSITO_CODIGO) REFERENCES DEPOSITOS(CODIGO),
    CONSTRAINT FK_VENTAS_USUARIOS FOREIGN KEY (USUARIO_CODIGO) REFERENCES USUARIOS(CODIGO)
);

CREATE TABLE VENTAS_DESGLOSE (
    CORRELATIVO INTEGER NOT NULL,
    LINEA SMALLINT NOT NULL,
    PRODUCTO_CODIGO VARCHAR(15) NOT NULL,
    PRODUCTO_NOMBRE VARCHAR(100),
    CANTIDAD DOUBLE PRECISION NOT NULL,
    PRECIO_UNITARIO DOUBLE PRECISION NOT NULL,
    PRECIO_TOTAL DOUBLE PRECISION NOT NULL,
    DESCUENTO DOUBLE PRECISION DEFAULT 0,
    IMPUESTO DOUBLE PRECISION DEFAULT 0,
    TOTAL DOUBLE PRECISION NOT NULL,
    COSTO_UNITARIO DOUBLE PRECISION DEFAULT 0,
    COSTO_TOTAL DOUBLE PRECISION DEFAULT 0,
    DEPOSITO_CODIGO VARCHAR(15) NOT NULL,
    CONSTRAINT PK_VENTAS_DESGLOSE PRIMARY KEY (CORRELATIVO, LINEA),
    CONSTRAINT FK_VENTAS_DESGLOSE_VENTAS FOREIGN KEY (CORRELATIVO) REFERENCES VENTAS(CORRELATIVO) ON DELETE CASCADE,
    CONSTRAINT FK_VENTAS_DESGLOSE_PRODUCTOS FOREIGN KEY (PRODUCTO_CODIGO) REFERENCES PRODUCTOS(CODIGO)
);

/* =============================================================================
   CUENTAS POR COBRAR (CXC)
   ============================================================================= */

CREATE TABLE CXC (
    CORRELATIVO INTEGER NOT NULL,
    DOCUMENTO VARCHAR(10) NOT NULL,
    TIPO_DOCUMENTO CHAR(3) NOT NULL,
    CLIENTE_CODIGO VARCHAR(15) NOT NULL,
    CLIENTE_NOMBRE VARCHAR(160),
    FECHA_DOCUMENTO DATE NOT NULL,
    FECHA_VENCIMIENTO DATE NOT NULL,
    MONEDA_CODIGO VARCHAR(15) DEFAULT 'DOP',
    FACTOR_CAMBIO DOUBLE PRECISION DEFAULT 1,
    TOTAL_OPERACION DOUBLE PRECISION NOT NULL,
    SALDO_ACTUAL DOUBLE PRECISION NOT NULL,
    USUARIO_CODIGO VARCHAR(15) NOT NULL,
    VENTA_CORRELATIVO INTEGER,
    ANULADO CHAR(1) DEFAULT 'N',
    CONSTRAINT PK_CXC PRIMARY KEY (CORRELATIVO),
    CONSTRAINT FK_CXC_CLIENTES FOREIGN KEY (CLIENTE_CODIGO) REFERENCES CLIENTES(CODIGO),
    CONSTRAINT FK_CXC_USUARIOS FOREIGN KEY (USUARIO_CODIGO) REFERENCES USUARIOS(CODIGO)
);

/* =============================================================================
   CUENTAS POR PAGAR (CXP)
   ============================================================================= */

CREATE TABLE CXP (
    CORRELATIVO INTEGER NOT NULL,
    DOCUMENTO VARCHAR(10) NOT NULL,
    TIPO_DOCUMENTO CHAR(3) NOT NULL,
    PROVEEDOR_CODIGO VARCHAR(15) NOT NULL,
    PROVEEDOR_NOMBRE VARCHAR(160),
    FECHA_DOCUMENTO DATE NOT NULL,
    FECHA_VENCIMIENTO DATE NOT NULL,
    MONEDA_CODIGO VARCHAR(15) DEFAULT 'DOP',
    FACTOR_CAMBIO DOUBLE PRECISION DEFAULT 1,
    TOTAL_OPERACION DOUBLE PRECISION NOT NULL,
    SALDO_ACTUAL DOUBLE PRECISION NOT NULL,
    USUARIO_CODIGO VARCHAR(15) NOT NULL,
    COMPRA_CORRELATIVO INTEGER,
    ANULADO CHAR(1) DEFAULT 'N',
    CONSTRAINT PK_CXP PRIMARY KEY (CORRELATIVO),
    CONSTRAINT FK_CXP_PROVEEDORES FOREIGN KEY (PROVEEDOR_CODIGO) REFERENCES PROVEEDORES(CODIGO),
    CONSTRAINT FK_CXP_USUARIOS FOREIGN KEY (USUARIO_CODIGO) REFERENCES USUARIOS(CODIGO)
);

/* =============================================================================
   CAJA
   ============================================================================= */

CREATE TABLE CAJA (
    CORRELATIVO INTEGER NOT NULL,
    TIPO_MOVIMIENTO CHAR(1) NOT NULL,
    CONCEPTO VARCHAR(120) NOT NULL,
    FECHA DATE NOT NULL,
    HORA TIME NOT NULL,
    MONEDA_CODIGO VARCHAR(15) DEFAULT 'DOP',
    FACTOR_CAMBIO DOUBLE PRECISION DEFAULT 1,
    DEBE DOUBLE PRECISION DEFAULT 0,
    HABER DOUBLE PRECISION DEFAULT 0,
    SALDO DOUBLE PRECISION DEFAULT 0,
    USUARIO_CODIGO VARCHAR(15) NOT NULL,
    DOCUMENTO_REFERENCIA VARCHAR(20),
    CONSTRAINT PK_CAJA PRIMARY KEY (CORRELATIVO),
    CONSTRAINT FK_CAJA_USUARIOS FOREIGN KEY (USUARIO_CODIGO) REFERENCES USUARIOS(CODIGO)
);

/* =============================================================================
   BANCOS
   ============================================================================= */

CREATE TABLE BANCOS (
    CODIGO VARCHAR(15) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    CUENTA VARCHAR(20) NOT NULL,
    TIPO_CUENTA VARCHAR(20),
    MONEDA_CODIGO VARCHAR(15) DEFAULT 'DOP',
    SALDO_ACTUAL DOUBLE PRECISION DEFAULT 0,
    ACTIVO CHAR(1) DEFAULT 'S',
    CONSTRAINT PK_BANCOS PRIMARY KEY (CODIGO)
);

CREATE TABLE MOVIMIENTOS_BANCARIOS (
    CORRELATIVO INTEGER NOT NULL,
    BANCO_CODIGO VARCHAR(15) NOT NULL,
    TIPO_MOVIMIENTO CHAR(1) NOT NULL,
    CONCEPTO VARCHAR(120) NOT NULL,
    FECHA DATE NOT NULL,
    NUMERO_CHEQUE VARCHAR(20),
    MONEDA_CODIGO VARCHAR(15) DEFAULT 'DOP',
    FACTOR_CAMBIO DOUBLE PRECISION DEFAULT 1,
    DEBE DOUBLE PRECISION DEFAULT 0,
    HABER DOUBLE PRECISION DEFAULT 0,
    SALDO DOUBLE PRECISION DEFAULT 0,
    USUARIO_CODIGO VARCHAR(15) NOT NULL,
    DOCUMENTO_REFERENCIA VARCHAR(20),
    CONSTRAINT PK_MOVIMIENTOS_BANCARIOS PRIMARY KEY (CORRELATIVO),
    CONSTRAINT FK_MOVIMIENTOS_BANCOS FOREIGN KEY (BANCO_CODIGO) REFERENCES BANCOS(CODIGO),
    CONSTRAINT FK_MOVIMIENTOS_USUARIOS FOREIGN KEY (USUARIO_CODIGO) REFERENCES USUARIOS(CODIGO)
);

/* =============================================================================
   CONTABILIDAD
   ============================================================================= */

CREATE TABLE CUENTAS_CONTABLES (
    CODIGO VARCHAR(20) NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    TIPO CHAR(1) NOT NULL,
    NIVEL SMALLINT DEFAULT 1,
    PADRE_CODIGO VARCHAR(20),
    ACTIVA CHAR(1) DEFAULT 'S',
    CONSTRAINT PK_CUENTAS_CONTABLES PRIMARY KEY (CODIGO),
    CONSTRAINT FK_CUENTAS_CONTABLES_PADRE FOREIGN KEY (PADRE_CODIGO) REFERENCES CUENTAS_CONTABLES(CODIGO)
);

CREATE TABLE ASIENTOS_CONTABLES (
    CORRELATIVO INTEGER NOT NULL,
    FECHA DATE NOT NULL,
    DESCRIPCION VARCHAR(250) NOT NULL,
    REFERENCIA VARCHAR(20),
    USUARIO_CODIGO VARCHAR(15) NOT NULL,
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_ASIENTOS_CONTABLES PRIMARY KEY (CORRELATIVO),
    CONSTRAINT FK_ASIENTOS_USUARIOS FOREIGN KEY (USUARIO_CODIGO) REFERENCES USUARIOS(CODIGO)
);

CREATE TABLE ASIENTOS_DETALLE (
    CORRELATIVO INTEGER NOT NULL,
    LINEA SMALLINT NOT NULL,
    CUENTA_CODIGO VARCHAR(20) NOT NULL,
    DESCRIPCION VARCHAR(120),
    DEBE DOUBLE PRECISION DEFAULT 0,
    HABER DOUBLE PRECISION DEFAULT 0,
    CONSTRAINT PK_ASIENTOS_DETALLE PRIMARY KEY (CORRELATIVO, LINEA),
    CONSTRAINT FK_ASIENTOS_DETALLE_ASIENTOS FOREIGN KEY (CORRELATIVO) REFERENCES ASIENTOS_CONTABLES(CORRELATIVO) ON DELETE CASCADE,
    CONSTRAINT FK_ASIENTOS_DETALLE_CUENTAS FOREIGN KEY (CUENTA_CODIGO) REFERENCES CUENTAS_CONTABLES(CODIGO)
);

/* =============================================================================
   AUDITORIA
   ============================================================================= */

CREATE TABLE AUDITORIA (
    CORRELATIVO INTEGER NOT NULL,
    USUARIO_CODIGO VARCHAR(15),
    FECHA_HORA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TABLA_AFECTADA VARCHAR(50),
    REGISTRO_AFECTADO VARCHAR(50),
    ACCION CHAR(1) NOT NULL,
    DATOS_ANTERIORES BLOB SUB_TYPE TEXT,
    DATOS_NUEVOS BLOB SUB_TYPE TEXT,
    ESTACION VARCHAR(30),
    CONSTRAINT PK_AUDITORIA PRIMARY KEY (CORRELATIVO)
);

/* =============================================================================
   NUMERACION DE DOCUMENTOS
   ============================================================================= */

CREATE TABLE NUMEROS_DOCUMENTOS (
    TIPO_DOCUMENTO CHAR(3) NOT NULL,
    DEPOSITO_CODIGO VARCHAR(15) NOT NULL,
    ULTIMO_NUMERO INTEGER DEFAULT 0,
    CONSTRAINT PK_NUMEROS_DOCUMENTOS PRIMARY KEY (TIPO_DOCUMENTO, DEPOSITO_CODIGO),
    CONSTRAINT FK_NUMEROS_DOCUMENTOS_DEPOSITOS FOREIGN KEY (DEPOSITO_CODIGO) REFERENCES DEPOSITOS(CODIGO)
);

/* =============================================================================
   INDICES
   ============================================================================= */

CREATE INDEX IDX_CLIENTES_NOMBRE ON CLIENTES(NOMBRE);
CREATE INDEX IDX_PROVEEDORES_NOMBRE ON PROVEEDORES(NOMBRE);
CREATE INDEX IDX_PRODUCTOS_NOMBRE ON PRODUCTOS(NOMBRE);
CREATE INDEX IDX_COMPRAS_FECHA ON COMPRAS(FECHA_EMISION);
CREATE INDEX IDX_VENTAS_FECHA ON VENTAS(FECHA_EMISION);
CREATE INDEX IDX_CXC_CLIENTE ON CXC(CLIENTE_CODIGO);
CREATE INDEX IDX_CXP_PROVEEDOR ON CXP(PROVEEDOR_CODIGO);
CREATE INDEX IDX_CAJA_FECHA ON CAJA(FECHA);
CREATE INDEX IDX_AUDITORIA_FECHA ON AUDITORIA(FECHA_HORA);

/* =============================================================================
   TABLAS PARA SINCRONIZACIÓN HÍBRIDA
   ============================================================================= */

/* NODOS DE SINCRONIZACIÓN */
CREATE TABLE SYNC_NODES (
    NODE_ID VARCHAR(100) NOT NULL,
    NODE_URL VARCHAR(500) NOT NULL,
    NODE_ROLE VARCHAR(20) DEFAULT 'SLAVE',
    ACTIVE CHAR(1) DEFAULT 'S',
    LAST_HEARTBEAT TIMESTAMP,
    REGISTERED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    NODE_NAME VARCHAR(100),
    NODE_VERSION VARCHAR(20),
    CONSTRAINT PK_SYNC_NODES PRIMARY KEY (NODE_ID)
);

/* LOG DE SINCRONIZACIÓN */
CREATE TABLE SYNC_LOGS (
    ID VARCHAR(50) NOT NULL,
    TABLE_NAME VARCHAR(100) NOT NULL,
    RECORD_ID VARCHAR(100) NOT NULL,
    ACTION VARCHAR(20) NOT NULL,
    PAYLOAD BLOB SUB_TYPE TEXT,
    SYNC_STATUS VARCHAR(20) DEFAULT 'PENDING',
    ATTEMPTS INTEGER DEFAULT 0,
    LAST_ERROR VARCHAR(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    NODE_ID VARCHAR(100),
    MASTER_RESPONSE BLOB SUB_TYPE TEXT,
    SYNCED_AT TIMESTAMP,
    CONSTRAINT PK_SYNC_LOGS PRIMARY KEY (ID)
);

/* COLA DE SINCRONIZACIÓN */
CREATE TABLE SYNC_QUEUE (
    ID VARCHAR(50) NOT NULL,
    PRIORITY INTEGER DEFAULT 0,
    TABLE_NAME VARCHAR(100) NOT NULL,
    RECORD_ID VARCHAR(100) NOT NULL,
    ACTION VARCHAR(20) NOT NULL,
    PAYLOAD BLOB SUB_TYPE TEXT,
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PROCESSED_AT TIMESTAMP,
    NODE_ID VARCHAR(100),
    CONSTRAINT PK_SYNC_QUEUE PRIMARY KEY (ID)
);

/* CONFIGURACIÓN DE SINCRONIZACIÓN */
CREATE TABLE SYNC_CONFIG (
    KEY VARCHAR(100) NOT NULL,
    VALUE VARCHAR(500) NOT NULL,
    DESCRIPTION VARCHAR(255),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_SYNC_CONFIG PRIMARY KEY (KEY)
);

/* ÍNDICES PARA SINCRONIZACIÓN */
CREATE INDEX IDX_SYNC_LOGS_STATUS ON SYNC_LOGS(SYNC_STATUS);
CREATE INDEX IDX_SYNC_LOGS_NODE ON SYNC_LOGS(NODE_ID);
CREATE INDEX IDX_SYNC_LOGS_CREATED ON SYNC_LOGS(CREATED_AT);
CREATE INDEX IDX_SYNC_QUEUE_STATUS ON SYNC_QUEUE(STATUS);
CREATE INDEX IDX_SYNC_QUEUE_PRIORITY ON SYNC_QUEUE(PRIORITY);

/* DATOS POR DEFECTO PARA SINCRONIZACIÓN */
INSERT INTO SYNC_CONFIG (KEY, VALUE, DESCRIPTION) VALUES 
    ('SYNC_ENABLED', 'S', 'Sincronización habilitada');
INSERT INTO SYNC_CONFIG (KEY, VALUE, DESCRIPTION) VALUES 
    ('SYNC_INTERVAL', '15000', 'Intervalo de sincronización en ms');
INSERT INTO SYNC_CONFIG (KEY, VALUE, DESCRIPTION) VALUES 
    ('SYNC_BATCH_SIZE', '20', 'Cantidad de registros por lote');
INSERT INTO SYNC_CONFIG (KEY, VALUE, DESCRIPTION) VALUES 
    ('SYNC_MAX_RETRIES', '5', 'Máximos reintentos por registro');

/* =============================================================================
   TRIGGERS PARA AUDITORIA
   ============================================================================= */

SET TERM ^ ;

CREATE OR ALTER TRIGGER AUDITORIA_VENTAS_AI FOR VENTAS
ACTIVE AFTER INSERT POSITION 1
AS
BEGIN
    INSERT INTO AUDITORIA (USUARIO_CODIGO, TABLA_AFECTADA, REGISTRO_AFECTADO, ACCION, ESTACION)
    VALUES (NEW.USUARIO_CODIGO, 'VENTAS', CAST(NEW.CORRELATIVO AS VARCHAR(50)), 'I', 'SERVER');
END^

CREATE OR ALTER TRIGGER AUDITORIA_VENTAS_AU FOR VENTAS
ACTIVE AFTER UPDATE POSITION 1
AS
BEGIN
    INSERT INTO AUDITORIA (USUARIO_CODIGO, TABLA_AFECTADA, REGISTRO_AFECTADO, ACCION, ESTACION)
    VALUES (NEW.USUARIO_CODIGO, 'VENTAS', CAST(NEW.CORRELATIVO AS VARCHAR(50)), 'U', 'SERVER');
END^

CREATE OR ALTER TRIGGER AUDITORIA_VENTAS_AD FOR VENTAS
ACTIVE AFTER DELETE POSITION 1
AS
BEGIN
    INSERT INTO AUDITORIA (USUARIO_CODIGO, TABLA_AFECTADA, REGISTRO_AFECTADO, ACCION, ESTACION)
    VALUES (USER, 'VENTAS', CAST(OLD.CORRELATIVO AS VARCHAR(50)), 'D', 'SERVER');
END^

SET TERM ; ^

COMMIT WORK;
